
var createFFmpegCore = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(createFFmpegCore) {
  createFFmpegCore = createFFmpegCore || {};


var e;e||(e=typeof createFFmpegCore !== 'undefined' ? createFFmpegCore : {});var aa,ba;e.ready=new Promise(function(a,b){aa=a;ba=b});e.quit=function(a){if(e.onExit)e.onExit(a);throw new ca(a);};e.exit=da;ea=h=function(){};var fa={},ha;for(ha in e)e.hasOwnProperty(ha)&&(fa[ha]=e[ha]);var ia=[],ja="./this.program";function ka(a,b){throw b;}var la=!1,l=!1,t=!1,ma=!1;la="object"===typeof window;l="function"===typeof importScripts;
t="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ma=!la&&!t&&!l;var u=e.ENVIRONMENT_IS_PTHREAD||!1,x="";function na(a){return e.locateFile?e.locateFile(a,x):x+a}var oa,pa,qa,ra,sa;
if(t){x=l?require("path").dirname(x)+"/":__dirname+"/";oa=function(a,b){ra||(ra=require("fs"));sa||(sa=require("path"));a=sa.normalize(a);return ra.readFileSync(a,b?null:"utf8")};qa=function(a){a=oa(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ja=process.argv[1].replace(/\\/g,"/"));ia=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ca))throw a;});process.on("unhandledRejection",z);ka=function(a){process.exit(a)};e.inspect=
function(){return"[Emscripten Module object]"};var ta;try{ta=require("worker_threads")}catch(a){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),a;}global.Worker=ta.Worker}else if(ma)"undefined"!=typeof read&&(oa=function(a){return read(a)}),qa=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ia=scriptArgs:
"undefined"!=typeof arguments&&(ia=arguments),"function"===typeof quit&&(ka=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(la||l)l?x=self.location.href:"undefined"!==typeof document&&document.currentScript&&(x=document.currentScript.src),_scriptDir&&(x=_scriptDir),0!==x.indexOf("blob:")?x=x.substr(0,x.lastIndexOf("/")+1):x="",t?(oa=function(a,b){ra||(ra=
require("fs"));sa||(sa=require("path"));a=sa.normalize(a);return ra.readFileSync(a,b?null:"utf8")},qa=function(a){a=oa(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a}):(oa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(qa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),pa=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";
d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)});t&&"undefined"===typeof performance&&(global.performance=require("perf_hooks").performance);var ea=e.print||console.log.bind(console),h=e.printErr||console.warn.bind(console);for(ha in fa)fa.hasOwnProperty(ha)&&(e[ha]=fa[ha]);fa=null;e.arguments&&(ia=e.arguments);e.thisProgram&&(ja=e.thisProgram);e.quit&&(ka=e.quit);var ua,va=0,wa;e.wasmBinary&&(wa=e.wasmBinary);
var noExitRuntime=e.noExitRuntime||!0;"object"!==typeof WebAssembly&&z("no native wasm support detected");var xa,ya,za=!1;function assert(a,b){a||z("Assertion failed: "+b)}function Aa(a){var b=e["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function Ba(a,b,c,d){var f={string:function(q){var r=0;if(null!==q&&void 0!==q&&0!==q){var y=(q.length<<2)+1;r=Ca(y);Da(q,r,y)}return r},array:function(q){var r=Ca(q.length);A.set(q,r);return r}},g=Aa(a),k=[];a=0;if(d)for(var m=0;m<d.length;m++){var p=f[c[m]];p?(0===a&&(a=B()),k[m]=p(d[m])):k[m]=d[m]}c=g.apply(null,k);c=function(q){return"string"===b?C(q):"boolean"===b?!!q:q}(c);0!==a&&D(a);return c}
function Ea(a){var b=new TextDecoder(a);this.decode=function(c){c.buffer instanceof SharedArrayBuffer&&(c=new Uint8Array(c));return b.decode.call(b,c)}}var Fa="undefined"!==typeof TextDecoder?new Ea("utf8"):void 0;
function Ga(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Fa)return Fa.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function C(a){return a?Ga(Ha,a,void 0):""}
function Ia(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var m=a.charCodeAt(++g);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}function Da(a,b,c){return Ia(a,Ha,b,c)}
function Ja(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new Ea("utf-16le");function Ka(a){var b=Ja(a)+1,c=E(b);c&&Ia(a,A,c,b);return c}function La(a){var b=Ja(a)+1,c=Ca(b);Ia(a,A,c,b);return c}function Ma(a,b,c){for(var d=0;d<a.length;++d)A[b++>>0]=a.charCodeAt(d);c||(A[b>>0]=0)}var Na,A,Ha,H,Oa,I,J,Pa,Qa;u&&(Na=e.buffer);
var Ra=e.INITIAL_MEMORY||2146435072;
if(u)xa=e.wasmMemory,Na=e.buffer;else if(e.wasmMemory)xa=e.wasmMemory;else if(xa=new WebAssembly.Memory({initial:Ra/65536,maximum:Ra/65536,shared:!0}),!(xa.buffer instanceof SharedArrayBuffer))throw h("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),t&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),Error("bad memory");
xa&&(Na=xa.buffer);Ra=Na.byteLength;var Sa=Na;Na=Sa;e.HEAP8=A=new Int8Array(Sa);e.HEAP16=H=new Int16Array(Sa);e.HEAP32=I=new Int32Array(Sa);e.HEAPU8=Ha=new Uint8Array(Sa);e.HEAPU16=Oa=new Uint16Array(Sa);e.HEAPU32=J=new Uint32Array(Sa);e.HEAPF32=Pa=new Float32Array(Sa);e.HEAPF64=Qa=new Float64Array(Sa);var K,Ta=[],Ua=[],Va=[],Wa=[];function Xa(){u||(e.noFSInit||L.Lc.yd||L.Lc(),L.ge=!1,M.root=L.Ob(M,{},null),$a(Ua))}function ab(){var a=e.preRun.shift();Ta.unshift(a)}var bb=0,cb=null,db=null;
function eb(){assert(!u,"addRunDependency cannot be used in a pthread worker");bb++;e.monitorRunDependencies&&e.monitorRunDependencies(bb)}function fb(){bb--;e.monitorRunDependencies&&e.monitorRunDependencies(bb);if(0==bb&&(null!==cb&&(clearInterval(cb),cb=null),db)){var a=db;db=null;a()}}e.preloadedImages={};e.preloadedAudios={};
function z(a){if(e.onAbort)e.onAbort(a);u&&console.error("Pthread aborting at "+Error().stack);h(a);za=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function gb(){return N.startsWith("data:application/octet-stream;base64,")}var N;N="ffmpeg-core.wasm";gb()||(N=na(N));function hb(){var a=N;try{if(a==N&&wa)return new Uint8Array(wa);if(qa)return qa(a);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function ib(){if(!wa&&(la||l)){if("function"===typeof fetch&&!N.startsWith("file://"))return fetch(N,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+N+"'";return a.arrayBuffer()}).catch(function(){return hb()});if(pa)return new Promise(function(a,b){pa(N,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return hb()})}
var P,Q,kb={5410468:function(){throw"Canceled!";},5410486:function(a,b){setTimeout(function(){jb(a,b)},0)}};function $a(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.Nf;"number"===typeof c?void 0===b.Kc?K.get(c)():K.get(c)(b.Kc):c(void 0===b.Kc?null:b.Kc)}}}
function lb(a,b){if(0>=a||a>A.length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(I,mb>>2),d=0;if(c==a&&Atomics.compareExchange(I,mb>>2,c,0)==c&&(--b,d=1,0>=b))return 1;a=Atomics.notify(I,a>>2,b);if(0<=a)return a+d;throw"Atomics.notify returned an unexpected value "+a;}e._emscripten_futex_wake=lb;
function nb(a){if(u)throw"Internal Error! cancelThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cancelThread!";T.jc[a].worker.postMessage({cmd:"cancel"})}function ob(a){if(u)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cleanupThread!";var b=T.jc[a];b&&(I[a+12>>2]=0,T.dd(b.worker))}
var T={pc:[],oc:[],Jd:[],Rf:function(){},Qe:function(){for(var a=E(228),b=0;57>b;++b)J[a/4+b]=0;I[a+12>>2]=a;b=a+152;I[b>>2]=b;var c=E(512);for(b=0;128>b;++b)J[c/4+b]=0;Atomics.store(J,a+100>>2,c);Atomics.store(J,a+40>>2,a);pb(a,!l,1);qb(a)},Re:function(){T.receiveObjectTransfer=T.hf;T.threadInit=T.uf;T.threadCancel=T.sf;T.threadExit=T.tf;T.setExitStatus=T.nf},jc:{},hd:[],kf:function(){for(;0<T.hd.length;)T.hd.pop()();u&&rb()&&sb()},me:function(a,b){Atomics.store(J,a+56>>2,1);Atomics.store(J,a+60>>
2,0);T.kf();Atomics.store(J,a+4>>2,b);Atomics.store(J,a+0>>2,1);lb(a+0,2147483647);pb(0,0,0)},nf:function(){},tf:function(a){var b=rb();b&&(T.me(b,a),u&&postMessage({cmd:"exit"}))},sf:function(){T.me(rb(),-1);postMessage({cmd:"cancelDone"})},rf:function(){for(var a in T.jc){var b=T.jc[a];b&&b.worker&&T.dd(b.worker)}T.jc={};for(a=0;a<T.pc.length;++a){var c=T.pc[a];c.terminate()}T.pc=[];for(a=0;a<T.oc.length;++a)c=T.oc[a],b=c.cc,T.ud(b),c.terminate();T.oc=[]},ud:function(a){if(a){if(a.kc){var b=I[a.kc+
100>>2];I[a.kc+100>>2]=0;tb(b);tb(a.kc)}a.kc=0;a.qd&&a.wc&&tb(a.wc);a.wc=0;a.worker&&(a.worker.cc=null)}},dd:function(a){T.lf(function(){delete T.jc[a.cc.kc];T.pc.push(a);T.oc.splice(T.oc.indexOf(a),1);T.ud(a.cc);a.cc=void 0})},lf:function(a){I[ub>>2]=0;try{a()}finally{I[ub>>2]=1}},hf:function(){},uf:function(){for(var a in T.Jd)T.Jd[a]()},Ve:function(a,b){a.onmessage=function(c){var d=c.data,f=d.cmd;a.cc&&(T.He=a.cc.kc);if(d.targetThread&&d.targetThread!=rb()){var g=T.jc[d.ag];g?g.worker.postMessage(c.data,
d.transferList):console.error('Internal error! Worker sent a message "'+f+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===f)vb();else if("spawnThread"===f)xb(c.data);else if("cleanupThread"===f)ob(d.thread);else if("killThread"===f){c=d.thread;if(u)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";I[c+12>>2]=0;c=T.jc[c];c.worker.terminate();
T.ud(c);T.oc.splice(T.oc.indexOf(c.worker),1);c.worker.cc=void 0}else if("cancelThread"===f)nb(d.thread);else if("loaded"===f)a.loaded=!0,b&&b(a),a.Rc&&(a.Rc(),delete a.Rc);else if("print"===f)ea("Thread "+d.threadId+": "+d.text);else if("printErr"===f)h("Thread "+d.threadId+": "+d.text);else if("alert"===f)alert("Thread "+d.threadId+": "+d.text);else if("exit"===f)a.cc&&Atomics.load(J,a.cc.kc+64>>2)&&T.dd(a);else if("exitProcess"===f)try{da(d.returnCode)}catch(k){if(k instanceof ca)return;throw k;
}else"cancelDone"===f?T.dd(a):"objectTransfer"!==f&&("setimmediate"===c.data.target?a.postMessage(c.data):h("worker sent an unknown command "+f));T.He=void 0};a.onerror=function(c){h("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message)};t&&(a.on("message",function(c){a.onmessage({data:c})}),a.on("error",function(c){a.onerror(c)}),a.on("exit",function(){}));a.postMessage({cmd:"load",urlOrBlob:e.mainScriptUrlOrBlob||_scriptDir,wasmMemory:xa,wasmModule:ya})},xe:function(){var a=na("ffmpeg-core.worker.js");
T.pc.push(new Worker(a))},Me:function(){0==T.pc.length&&(T.xe(),T.Ve(T.pc[0]));return T.pc.pop()},Ef:function(a){for(a=performance.now()+a;performance.now()<a;);}};e.establishStackSpace=function(a,b){yb(a,b);D(a)};e.invokeEntryPoint=function(a,b){return K.get(a)(b)};var Ab=0;function Bb(){return noExitRuntime||0<Ab}e.keepRuntimeAlive=Bb;var Cb;
t?Cb=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:u?Cb=function(){return performance.now()-e.__performance_now_clock_drift}:"undefined"!==typeof dateNow?Cb=dateNow:Cb=function(){return performance.now()};function Db(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Cb();else return I[Eb()>>2]=28,-1;I[b>>2]=a/1E3|0;I[b+4>>2]=a%1E3*1E6|0;return 0}function Fb(a,b){T.hd.push(function(){K.get(a)(b)})}
function Gb(a,b){a=new Date(1E3*I[a>>2]);I[b>>2]=a.getUTCSeconds();I[b+4>>2]=a.getUTCMinutes();I[b+8>>2]=a.getUTCHours();I[b+12>>2]=a.getUTCDate();I[b+16>>2]=a.getUTCMonth();I[b+20>>2]=a.getUTCFullYear()-1900;I[b+24>>2]=a.getUTCDay();I[b+36>>2]=0;I[b+32>>2]=0;I[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;Gb.Md||(Gb.Md=Ka("GMT"));I[b+40>>2]=Gb.Md;return b}
function Hb(){function a(k){return(k=k.toTimeString().match(/\(([A-Za-z ]+)\)$/))?k[1]:"GMT"}if(u)return U(2,1);if(!Hb.ye){Hb.ye=!0;var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var f=d.getTimezoneOffset(),g=Math.max(b,f);I[Ib()>>2]=60*g;I[Jb()>>2]=Number(b!=f);c=a(c);d=a(d);c=Ka(c);d=Ka(d);f<b?(I[Kb()>>2]=c,I[Kb()+4>>2]=d):(I[Kb()>>2]=d,I[Kb()+4>>2]=c)}}
function Lb(a,b){Hb();a=new Date(1E3*I[a>>2]);I[b>>2]=a.getSeconds();I[b+4>>2]=a.getMinutes();I[b+8>>2]=a.getHours();I[b+12>>2]=a.getDate();I[b+16>>2]=a.getMonth();I[b+20>>2]=a.getFullYear()-1900;I[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);I[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;I[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;I[b+32>>2]=a;a=I[Kb()+(a?4:0)>>2];
I[b+40>>2]=a;return b}function Mb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Nb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Mb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Ob(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Pb(a){if("/"===a)return"/";a=Nb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function Qb(a,b){return Nb(a+"/"+b)}
function Rb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(t)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){z("randomDevice")}}
function Sb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:L.cwd();if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Mb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}
function Tb(a,b){function c(k){for(var m=0;m<k.length&&""===k[m];m++);for(var p=k.length-1;0<=p&&""===k[p];p--);return m>p?[]:k.slice(m,p-m+1)}a=Sb(a).substr(1);b=Sb(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),f=d,g=0;g<d;g++)if(a[g]!==b[g]){f=g;break}d=[];for(g=f;g<a.length;g++)d.push("..");d=d.concat(b.slice(f));return d.join("/")}var Ub=[];function Vb(a,b){Ub[a]={input:[],output:[],Bc:b};L.Id(a,Wb)}
var Wb={open:function(a){var b=Ub[a.node.rdev];if(!b)throw new L.Ib(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Bc.flush(a.tty)},flush:function(a){a.tty.Bc.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Bc.ce)throw new L.Ib(60);for(var f=0,g=0;g<d;g++){try{var k=a.tty.Bc.ce(a.tty)}catch(m){throw new L.Ib(29);}if(void 0===k&&0===f)throw new L.Ib(6);if(null===k||void 0===k)break;f++;b[c+g]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.Bc.Ed)throw new L.Ib(60);
try{for(var f=0;f<d;f++)a.tty.Bc.Ed(a.tty,b[c+f])}catch(g){throw new L.Ib(29);}d&&(a.node.timestamp=Date.now());return f}},Yb={ce:function(a){if(!a.input.length){var b=null;if(t){var c=Buffer.xc?Buffer.xc(256):new Buffer(256),d=0;try{d=ra.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(f.toString().includes("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Xb(b,!0)}return a.input.shift()},Ed:function(a,b){null===b||10===b?(ea(Ga(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ea(Ga(a.output,0)),a.output=[])}},Zb={Ed:function(a,b){null===b||10===b?(h(Ga(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(h(Ga(a.output,0)),a.output=[])}},V={ic:null,Ob:function(){return V.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(L.Se(c)||L.isFIFO(c))throw new L.Ib(63);V.ic||(V.ic={dir:{node:{bc:V.Jb.bc,Tb:V.Jb.Tb,lookup:V.Jb.lookup,fc:V.Jb.fc,rename:V.Jb.rename,unlink:V.Jb.unlink,rmdir:V.Jb.rmdir,readdir:V.Jb.readdir,symlink:V.Jb.symlink},stream:{Wb:V.Kb.Wb}},file:{node:{bc:V.Jb.bc,Tb:V.Jb.Tb},stream:{Wb:V.Kb.Wb,read:V.Kb.read,write:V.Kb.write,Jc:V.Kb.Jc,zc:V.Kb.zc,Ac:V.Kb.Ac}},link:{node:{bc:V.Jb.bc,Tb:V.Jb.Tb,readlink:V.Jb.readlink},stream:{}},Qd:{node:{bc:V.Jb.bc,Tb:V.Jb.Tb},
stream:L.Ae}});c=L.createNode(a,b,c,d);L.Rb(c.mode)?(c.Jb=V.ic.dir.node,c.Kb=V.ic.dir.stream,c.Lb={}):L.isFile(c.mode)?(c.Jb=V.ic.file.node,c.Kb=V.ic.file.stream,c.Pb=0,c.Lb=null):L.rc(c.mode)?(c.Jb=V.ic.link.node,c.Kb=V.ic.link.stream):L.Mc(c.mode)&&(c.Jb=V.ic.Qd.node,c.Kb=V.ic.Qd.stream);c.timestamp=Date.now();a&&(a.Lb[b]=c,a.timestamp=c.timestamp);return c},Of:function(a){return a.Lb?a.Lb.subarray?a.Lb.subarray(0,a.Pb):new Uint8Array(a.Lb):new Uint8Array(0)},Xd:function(a,b){var c=a.Lb?a.Lb.length:
0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Lb,a.Lb=new Uint8Array(b),0<a.Pb&&a.Lb.set(c.subarray(0,a.Pb),0))},jf:function(a,b){if(a.Pb!=b)if(0==b)a.Lb=null,a.Pb=0;else{var c=a.Lb;a.Lb=new Uint8Array(b);c&&a.Lb.set(c.subarray(0,Math.min(b,a.Pb)));a.Pb=b}},Jb:{bc:function(a){var b={};b.dev=L.Mc(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;L.Rb(a.mode)?b.size=4096:L.isFile(a.mode)?b.size=a.Pb:L.rc(a.mode)?b.size=a.link.length:b.size=
0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Od=4096;b.blocks=Math.ceil(b.size/b.Od);return b},Tb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&V.jf(a,b.size)},lookup:function(){throw L.vd[44];},fc:function(a,b,c,d){return V.createNode(a,b,c,d)},rename:function(a,b,c){if(L.Rb(a.mode)){try{var d=L.ec(b,c)}catch(g){}if(d)for(var f in d.Lb)throw new L.Ib(55);}delete a.parent.Lb[a.name];
a.parent.timestamp=Date.now();a.name=c;b.Lb[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.Lb[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=L.ec(a,b),d;for(d in c.Lb)throw new L.Ib(55);delete a.Lb[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.Lb)a.Lb.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=V.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(!L.rc(a.mode))throw new L.Ib(28);return a.link}},
Kb:{read:function(a,b,c,d,f){var g=a.node.Lb;if(f>=a.node.Pb)return 0;a=Math.min(a.node.Pb-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Lb||a.Lb.subarray)){if(g)return a.Lb=b.subarray(c,c+d),a.Pb=d;if(0===a.Pb&&0===f)return a.Lb=b.slice(c,c+d),a.Pb=d;if(f+d<=a.Pb)return a.Lb.set(b.subarray(c,c+d),f),d}V.Xd(a,f+d);if(a.Lb.subarray&&b.subarray)a.Lb.set(b.subarray(c,
c+d),f);else for(g=0;g<d;g++)a.Lb[f+g]=b[c+g];a.Pb=Math.max(a.Pb,f+d);return d},Wb:function(a,b,c){1===c?b+=a.position:2===c&&L.isFile(a.node.mode)&&(b+=a.node.Pb);if(0>b)throw new L.Ib(28);return b},Jc:function(a,b,c){V.Xd(a.node,b+c);a.node.Pb=Math.max(a.node.Pb,b+c)},zc:function(a,b,c,d,f,g){if(0!==b)throw new L.Ib(28);if(!L.isFile(a.node.mode))throw new L.Ib(43);a=a.node.Lb;if(g&2||a.buffer!==Na){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;g=
65536*Math.ceil(c/65536);for(b=E(g);c<g;)A[b+c++]=0;c=b;if(!c)throw new L.Ib(48);A.set(a,c)}else d=!1,c=a.byteOffset;return{gf:c,pd:d}},Ac:function(a,b,c,d,f){if(!L.isFile(a.node.mode))throw new L.Ib(43);if(f&2)return 0;V.Kb.write(a,b,0,d,c,!1);return 0}}},W={md:16895,Ic:33279,Gd:null,Ob:function(a){function b(g){g=g.split("/");for(var k=d,m=0;m<g.length-1;m++){var p=g.slice(0,m+1).join("/");f[p]||(f[p]=W.createNode(k,g[m],W.md,0));k=f[p]}return k}function c(g){g=g.split("/");return g[g.length-1]}
assert(l);W.Gd||(W.Gd=new FileReaderSync);var d=W.createNode(null,"/",W.md,0),f={};Array.prototype.forEach.call(a.Dd.files||[],function(g){W.createNode(b(g.name),c(g.name),W.Ic,0,g,g.lastModifiedDate)});(a.Dd.blobs||[]).forEach(function(g){W.createNode(b(g.name),c(g.name),W.Ic,0,g.data)});(a.Dd.packages||[]).forEach(function(g){g.metadata.files.forEach(function(k){var m=k.filename.substr(1);W.createNode(b(m),c(m),W.Ic,0,g.blob.slice(k.start,k.end))})});return d},createNode:function(a,b,c,d,f,g){d=
L.createNode(a,b,c);d.mode=c;d.Jb=W.Jb;d.Kb=W.Kb;d.timestamp=(g||new Date).getTime();assert(W.Ic!==W.md);c===W.Ic?(d.size=f.size,d.Lb=f):(d.size=4096,d.Lb={});a&&(a.Lb[b]=d);return d},Jb:{bc:function(a){return{dev:1,ino:a.id,mode:a.mode,nlink:1,uid:0,gid:0,rdev:void 0,size:a.size,atime:new Date(a.timestamp),mtime:new Date(a.timestamp),ctime:new Date(a.timestamp),Od:4096,blocks:Math.ceil(a.size/4096)}},Tb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp)},
lookup:function(){throw new L.Ib(44);},fc:function(){throw new L.Ib(63);},rename:function(){throw new L.Ib(63);},unlink:function(){throw new L.Ib(63);},rmdir:function(){throw new L.Ib(63);},readdir:function(a){var b=[".",".."],c;for(c in a.Lb)a.Lb.hasOwnProperty(c)&&b.push(c);return b},symlink:function(){throw new L.Ib(63);},readlink:function(){throw new L.Ib(63);}},Kb:{read:function(a,b,c,d,f){if(f>=a.node.size)return 0;a=a.node.Lb.slice(f,f+d);d=W.Gd.readAsArrayBuffer(a);b.set(new Uint8Array(d),
c);return a.size},write:function(){throw new L.Ib(29);},Wb:function(a,b,c){1===c?b+=a.position:2===c&&L.isFile(a.node.mode)&&(b+=a.node.size);if(0>b)throw new L.Ib(28);return b}}},L={root:null,Pc:[],Ud:{},streams:[],af:1,hc:null,Td:"/",yd:!1,ge:!0,Ub:{},pe:{je:{te:1,ue:2}},Ib:null,vd:{},Yd:null,gd:0,Nb:function(a,b){a=Sb(L.cwd(),a);b=b||{};if(!a)return{path:"",node:null};var c={td:!0,Hd:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Hd)throw new L.Ib(32);a=Mb(a.split("/").filter(function(k){return!!k}),
!1);var f=L.root;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=L.ec(f,a[d]);c=Qb(c,a[d]);L.sc(f)&&(!g||g&&b.td)&&(f=f.Oc.root);if(!g||b.ac)for(g=0;L.rc(f.mode);)if(f=L.readlink(c),c=Sb(Ob(c),f),f=L.Nb(c,{Hd:b.Hd}).node,40<g++)throw new L.Ib(32);}return{path:c,node:f}},mc:function(a){for(var b;;){if(L.Zc(a))return a=a.Ob.he,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},xd:function(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|
0;return(a+c>>>0)%L.hc.length},ee:function(a){var b=L.xd(a.parent.id,a.name);a.uc=L.hc[b];L.hc[b]=a},fe:function(a){var b=L.xd(a.parent.id,a.name);if(L.hc[b]===a)L.hc[b]=a.uc;else for(b=L.hc[b];b;){if(b.uc===a){b.uc=a.uc;break}b=b.uc}},ec:function(a,b){var c=L.Ye(a);if(c)throw new L.Ib(c,a);for(c=L.hc[L.xd(a.id,b)];c;c=c.uc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return L.lookup(a,b)},createNode:function(a,b,c,d){a=new L.qe(a,b,c,d);L.ee(a);return a},sd:function(a){L.fe(a)},Zc:function(a){return a===
a.parent},sc:function(a){return!!a.Oc},isFile:function(a){return 32768===(a&61440)},Rb:function(a){return 16384===(a&61440)},rc:function(a){return 40960===(a&61440)},Mc:function(a){return 8192===(a&61440)},Se:function(a){return 24576===(a&61440)},isFIFO:function(a){return 4096===(a&61440)},isSocket:function(a){return 49152===(a&49152)},Ke:{r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},$e:function(a){var b=L.Ke[a];if("undefined"===typeof b)throw Error("Unknown file open mode: "+a);return b},Zd:function(a){var b=
["r","w","rw"][a&3];a&512&&(b+="w");return b},nc:function(a,b){if(L.ge)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Ye:function(a){var b=L.nc(a,"x");return b?b:a.Jb.lookup?0:2},Cd:function(a,b){try{return L.ec(a,b),20}catch(c){}return L.nc(a,"wx")},$c:function(a,b,c){try{var d=L.ec(a,b)}catch(f){return f.Mb}if(a=L.nc(a,"wx"))return a;if(c){if(!L.Rb(d.mode))return 54;if(L.Zc(d)||L.mc(d)===L.cwd())return 10}else if(L.Rb(d.mode))return 31;
return 0},Ze:function(a,b){return a?L.rc(a.mode)?32:L.Rb(a.mode)&&("r"!==L.Zd(b)||b&512)?31:L.nc(a,L.Zd(b)):44},se:4096,bf:function(a,b){b=b||L.se;for(a=a||0;a<=b;a++)if(!L.streams[a])return a;throw new L.Ib(33);},dc:function(a){return L.streams[a]},Sd:function(a,b,c){L.nd||(L.nd=function(){},L.nd.prototype={object:{get:function(){return this.node},set:function(g){this.node=g}}});var d=new L.nd,f;for(f in a)d[f]=a[f];a=d;b=L.bf(b,c);a.fd=b;return L.streams[b]=a},Be:function(a){L.streams[a]=null},
Ae:{open:function(a){a.Kb=L.Le(a.node.rdev).Kb;a.Kb.open&&a.Kb.open(a)},Wb:function(){throw new L.Ib(70);}},Bd:function(a){return a>>8},Tf:function(a){return a&255},tc:function(a,b){return a<<8|b},Id:function(a,b){L.Ud[a]={Kb:b}},Le:function(a){return L.Ud[a]},be:function(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.Pc)}return b},oe:function(a,b){function c(k){L.gd--;return b(k)}function d(k){if(k){if(!d.Ie)return d.Ie=!0,c(k)}else++g>=f.length&&c(null)}"function"===typeof a&&
(b=a,a=!1);L.gd++;1<L.gd&&h("warning: "+L.gd+" FS.syncfs operations in flight at once, probably just doing extra work");var f=L.be(L.root.Ob),g=0;f.forEach(function(k){if(!k.type.oe)return d(null);k.type.oe(k,a,d)})},Ob:function(a,b,c){var d="/"===c,f=!c;if(d&&L.root)throw new L.Ib(10);if(!d&&!f){var g=L.Nb(c,{td:!1});c=g.path;g=g.node;if(L.sc(g))throw new L.Ib(10);if(!L.Rb(g.mode))throw new L.Ib(54);}b={type:a,Dd:b,he:c,Pc:[]};a=a.Ob(b);a.Ob=b;b.root=a;d?L.root=a:g&&(g.Oc=b,g.Ob&&g.Ob.Pc.push(b));
return a},Bf:function(a){a=L.Nb(a,{td:!1});if(!L.sc(a.node))throw new L.Ib(28);a=a.node;var b=a.Oc,c=L.be(b);Object.keys(L.hc).forEach(function(d){for(d=L.hc[d];d;){var f=d.uc;c.includes(d.Ob)&&L.sd(d);d=f}});a.Oc=null;a.Ob.Pc.splice(a.Ob.Pc.indexOf(b),1)},lookup:function(a,b){return a.Jb.lookup(a,b)},fc:function(a,b,c){var d=L.Nb(a,{parent:!0}).node;a=Pb(a);if(!a||"."===a||".."===a)throw new L.Ib(28);var f=L.Cd(d,a);if(f)throw new L.Ib(f);if(!d.Jb.fc)throw new L.Ib(63);return d.Jb.fc(d,a,b,c)},create:function(a,
b){return L.fc(a,(void 0!==b?b:438)&4095|32768,0)},mkdir:function(a,b){return L.fc(a,(void 0!==b?b:511)&1023|16384,0)},Vf:function(a,b){a=a.split("/");for(var c="",d=0;d<a.length;++d)if(a[d]){c+="/"+a[d];try{L.mkdir(c,b)}catch(f){if(20!=f.Mb)throw f;}}},ad:function(a,b,c){"undefined"===typeof c&&(c=b,b=438);return L.fc(a,b|8192,c)},symlink:function(a,b){if(!Sb(a))throw new L.Ib(44);var c=L.Nb(b,{parent:!0}).node;if(!c)throw new L.Ib(44);b=Pb(b);var d=L.Cd(c,b);if(d)throw new L.Ib(d);if(!c.Jb.symlink)throw new L.Ib(63);
return c.Jb.symlink(c,b,a)},rename:function(a,b){var c=Ob(a),d=Ob(b),f=Pb(a),g=Pb(b);var k=L.Nb(a,{parent:!0});var m=k.node;k=L.Nb(b,{parent:!0});k=k.node;if(!m||!k)throw new L.Ib(44);if(m.Ob!==k.Ob)throw new L.Ib(75);var p=L.ec(m,f);d=Tb(a,d);if("."!==d.charAt(0))throw new L.Ib(28);d=Tb(b,c);if("."!==d.charAt(0))throw new L.Ib(55);try{var q=L.ec(k,g)}catch(r){}if(p!==q){c=L.Rb(p.mode);if(f=L.$c(m,f,c))throw new L.Ib(f);if(f=q?L.$c(k,g,c):L.Cd(k,g))throw new L.Ib(f);if(!m.Jb.rename)throw new L.Ib(63);
if(L.sc(p)||q&&L.sc(q))throw new L.Ib(10);if(k!==m&&(f=L.nc(m,"w")))throw new L.Ib(f);try{L.Ub.willMovePath&&L.Ub.willMovePath(a,b)}catch(r){h("FS.trackingDelegate['willMovePath']('"+a+"', '"+b+"') threw an exception: "+r.message)}L.fe(p);try{m.Jb.rename(p,k,g)}catch(r){throw r;}finally{L.ee(p)}try{if(L.Ub.onMovePath)L.Ub.onMovePath(a,b)}catch(r){h("FS.trackingDelegate['onMovePath']('"+a+"', '"+b+"') threw an exception: "+r.message)}}},rmdir:function(a){var b=L.Nb(a,{parent:!0}).node,c=Pb(a),d=L.ec(b,
c),f=L.$c(b,c,!0);if(f)throw new L.Ib(f);if(!b.Jb.rmdir)throw new L.Ib(63);if(L.sc(d))throw new L.Ib(10);try{L.Ub.willDeletePath&&L.Ub.willDeletePath(a)}catch(g){h("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.Jb.rmdir(b,c);L.sd(d);try{if(L.Ub.onDeletePath)L.Ub.onDeletePath(a)}catch(g){h("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}},readdir:function(a){a=L.Nb(a,{ac:!0}).node;if(!a.Jb.readdir)throw new L.Ib(54);return a.Jb.readdir(a)},
unlink:function(a){var b=L.Nb(a,{parent:!0}).node,c=Pb(a),d=L.ec(b,c),f=L.$c(b,c,!1);if(f)throw new L.Ib(f);if(!b.Jb.unlink)throw new L.Ib(63);if(L.sc(d))throw new L.Ib(10);try{L.Ub.willDeletePath&&L.Ub.willDeletePath(a)}catch(g){h("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.Jb.unlink(b,c);L.sd(d);try{if(L.Ub.onDeletePath)L.Ub.onDeletePath(a)}catch(g){h("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}},readlink:function(a){a=L.Nb(a).node;
if(!a)throw new L.Ib(44);if(!a.Jb.readlink)throw new L.Ib(28);return Sb(L.mc(a.parent),a.Jb.readlink(a))},stat:function(a,b){a=L.Nb(a,{ac:!b}).node;if(!a)throw new L.Ib(44);if(!a.Jb.bc)throw new L.Ib(63);return a.Jb.bc(a)},lstat:function(a){return L.stat(a,!0)},chmod:function(a,b,c){a="string"===typeof a?L.Nb(a,{ac:!c}).node:a;if(!a.Jb.Tb)throw new L.Ib(63);a.Jb.Tb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},lchmod:function(a,b){L.chmod(a,b,!0)},fchmod:function(a,b){a=L.dc(a);if(!a)throw new L.Ib(8);
L.chmod(a.node,b)},chown:function(a,b,c,d){a="string"===typeof a?L.Nb(a,{ac:!d}).node:a;if(!a.Jb.Tb)throw new L.Ib(63);a.Jb.Tb(a,{timestamp:Date.now()})},lchown:function(a,b,c){L.chown(a,b,c,!0)},fchown:function(a,b,c){a=L.dc(a);if(!a)throw new L.Ib(8);L.chown(a.node,b,c)},truncate:function(a,b){if(0>b)throw new L.Ib(28);a="string"===typeof a?L.Nb(a,{ac:!0}).node:a;if(!a.Jb.Tb)throw new L.Ib(63);if(L.Rb(a.mode))throw new L.Ib(31);if(!L.isFile(a.mode))throw new L.Ib(28);var c=L.nc(a,"w");if(c)throw new L.Ib(c);
a.Jb.Tb(a,{size:b,timestamp:Date.now()})},Mf:function(a,b){a=L.dc(a);if(!a)throw new L.Ib(8);if(0===(a.flags&2097155))throw new L.Ib(28);L.truncate(a.node,b)},cg:function(a,b,c){a=L.Nb(a,{ac:!0}).node;a.Jb.Tb(a,{timestamp:Math.max(b,c)})},open:function(a,b,c,d,f){if(""===a)throw new L.Ib(44);b="string"===typeof b?L.$e(b):b;c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=Nb(a);try{g=L.Nb(a,{ac:!(b&131072)}).node}catch(m){}}var k=!1;if(b&64)if(g){if(b&128)throw new L.Ib(20);
}else g=L.fc(a,c,0),k=!0;if(!g)throw new L.Ib(44);L.Mc(g.mode)&&(b&=-513);if(b&65536&&!L.Rb(g.mode))throw new L.Ib(54);if(!k&&(c=L.Ze(g,b)))throw new L.Ib(c);b&512&&L.truncate(g,0);b&=-131713;d=L.Sd({node:g,path:L.mc(g),flags:b,seekable:!0,position:0,Kb:g.Kb,Af:[],error:!1},d,f);d.Kb.open&&d.Kb.open(d);!e.logReadFiles||b&1||(L.Fd||(L.Fd={}),a in L.Fd||(L.Fd[a]=1,h("FS.trackingDelegate error on read file: "+a)));try{L.Ub.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=L.pe.je.te),0!==(b&2097155)&&(f|=L.pe.je.ue),
L.Ub.onOpenFile(a,f))}catch(m){h("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d},close:function(a){if(L.Nc(a))throw new L.Ib(8);a.qc&&(a.qc=null);try{a.Kb.close&&a.Kb.close(a)}catch(b){throw b;}finally{L.Be(a.fd)}a.fd=null},Nc:function(a){return null===a.fd},Wb:function(a,b,c){if(L.Nc(a))throw new L.Ib(8);if(!a.seekable||!a.Kb.Wb)throw new L.Ib(70);if(0!=c&&1!=c&&2!=c)throw new L.Ib(28);a.position=a.Kb.Wb(a,b,c);a.Af=[];return a.position},read:function(a,
b,c,d,f){if(0>d||0>f)throw new L.Ib(28);if(L.Nc(a))throw new L.Ib(8);if(1===(a.flags&2097155))throw new L.Ib(8);if(L.Rb(a.node.mode))throw new L.Ib(31);if(!a.Kb.read)throw new L.Ib(28);var g="undefined"!==typeof f;if(!g)f=a.position;else if(!a.seekable)throw new L.Ib(70);b=a.Kb.read(a,b,c,d,f);g||(a.position+=b);return b},write:function(a,b,c,d,f,g){if(0>d||0>f)throw new L.Ib(28);if(L.Nc(a))throw new L.Ib(8);if(0===(a.flags&2097155))throw new L.Ib(8);if(L.Rb(a.node.mode))throw new L.Ib(31);if(!a.Kb.write)throw new L.Ib(28);
a.seekable&&a.flags&1024&&L.Wb(a,0,2);var k="undefined"!==typeof f;if(!k)f=a.position;else if(!a.seekable)throw new L.Ib(70);b=a.Kb.write(a,b,c,d,f,g);k||(a.position+=b);try{if(a.path&&L.Ub.onWriteToFile)L.Ub.onWriteToFile(a.path)}catch(m){h("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+m.message)}return b},Jc:function(a,b,c){if(L.Nc(a))throw new L.Ib(8);if(0>b||0>=c)throw new L.Ib(28);if(0===(a.flags&2097155))throw new L.Ib(8);if(!L.isFile(a.node.mode)&&!L.Rb(a.node.mode))throw new L.Ib(43);
if(!a.Kb.Jc)throw new L.Ib(138);a.Kb.Jc(a,b,c)},zc:function(a,b,c,d,f,g){if(0!==(f&2)&&0===(g&2)&&2!==(a.flags&2097155))throw new L.Ib(2);if(1===(a.flags&2097155))throw new L.Ib(2);if(!a.Kb.zc)throw new L.Ib(43);return a.Kb.zc(a,b,c,d,f,g)},Ac:function(a,b,c,d,f){return a&&a.Kb.Ac?a.Kb.Ac(a,b,c,d,f):0},Xf:function(){return 0},yc:function(a,b,c){if(!a.Kb.yc)throw new L.Ib(59);return a.Kb.yc(a,b,c)},readFile:function(a,b){b=b||{};b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&
"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var c,d=L.open(a,b.flags);a=L.stat(a).size;var f=new Uint8Array(a);L.read(d,f,0,a,0);"utf8"===b.encoding?c=Ga(f,0):"binary"===b.encoding&&(c=f);L.close(d);return c},writeFile:function(a,b,c){c=c||{};c.flags=c.flags||577;a=L.open(a,c.flags,c.mode);if("string"===typeof b){var d=new Uint8Array(Ja(b)+1);b=Ia(b,d,0,d.length);L.write(a,d,0,b,void 0,c.ze)}else if(ArrayBuffer.isView(b))L.write(a,b,0,b.byteLength,void 0,c.ze);else throw Error("Unsupported data type");
L.close(a)},cwd:function(){return L.Td},chdir:function(a){a=L.Nb(a,{ac:!0});if(null===a.node)throw new L.Ib(44);if(!L.Rb(a.node.mode))throw new L.Ib(54);var b=L.nc(a.node,"x");if(b)throw new L.Ib(b);L.Td=a.path},De:function(){L.mkdir("/tmp");L.mkdir("/home");L.mkdir("/home/web_user")},Ce:function(){L.mkdir("/dev");L.Id(L.tc(1,3),{read:function(){return 0},write:function(b,c,d,f){return f}});L.ad("/dev/null",L.tc(1,3));Vb(L.tc(5,0),Yb);Vb(L.tc(6,0),Zb);L.ad("/dev/tty",L.tc(5,0));L.ad("/dev/tty1",L.tc(6,
0));var a=Rb();L.lc("/dev","random",a);L.lc("/dev","urandom",a);L.mkdir("/dev/shm");L.mkdir("/dev/shm/tmp")},Fe:function(){L.mkdir("/proc");var a=L.mkdir("/proc/self");L.mkdir("/proc/self/fd");L.Ob({Ob:function(){var b=L.createNode(a,"fd",16895,73);b.Jb={lookup:function(c,d){var f=L.dc(+d);if(!f)throw new L.Ib(8);c={parent:null,Ob:{he:"fake"},Jb:{readlink:function(){return f.path}}};return c.parent=c}};return b}},{},"/proc/self/fd")},Ge:function(){e.stdin?L.lc("/dev","stdin",e.stdin):L.symlink("/dev/tty",
"/dev/stdin");e.stdout?L.lc("/dev","stdout",null,e.stdout):L.symlink("/dev/tty","/dev/stdout");e.stderr?L.lc("/dev","stderr",null,e.stderr):L.symlink("/dev/tty1","/dev/stderr");L.open("/dev/stdin",0);L.open("/dev/stdout",1);L.open("/dev/stderr",1)},Wd:function(){L.Ib||(L.Ib=function(a,b){this.node=b;this.mf=function(c){this.Mb=c};this.mf(a);this.message="FS error"},L.Ib.prototype=Error(),L.Ib.prototype.constructor=L.Ib,[44].forEach(function(a){L.vd[a]=new L.Ib(a);L.vd[a].stack="<generic error, no stack>"}))},
qf:function(){L.Wd();L.hc=Array(4096);L.Ob(V,{},"/");L.De();L.Ce();L.Fe();L.Yd={MEMFS:V,WORKERFS:W}},Lc:function(a,b,c){L.Lc.yd=!0;L.Wd();e.stdin=a||e.stdin;e.stdout=b||e.stdout;e.stderr=c||e.stderr;L.Ge()},quit:function(){L.Lc.yd=!1;var a=e._fflush;a&&a(0);for(a=0;a<L.streams.length;a++){var b=L.streams[a];b&&L.close(b)}},wd:function(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c},Lf:function(a,b){a=L.rd(a,b);return a.exists?a.object:null},rd:function(a,b){try{var c=L.Nb(a,{ac:!b});a=c.path}catch(f){}var d=
{Zc:!1,exists:!1,error:0,name:null,path:null,object:null,cf:!1,ef:null,df:null};try{c=L.Nb(a,{parent:!0}),d.cf=!0,d.ef=c.path,d.df=c.node,d.name=Pb(a),c=L.Nb(a,{ac:!b}),d.exists=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.Zc="/"===c.path}catch(f){d.error=f.Mb}return d},If:function(a,b){a="string"===typeof a?a:L.mc(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Qb(a,c);try{L.mkdir(d)}catch(f){}a=d}}return d},Ee:function(a,b,c,d,f){a=Qb("string"===typeof a?a:L.mc(a),
b);return L.create(a,L.wd(d,f))},Rd:function(a,b,c,d,f,g){a=b?Qb("string"===typeof a?a:L.mc(a),b):a;d=L.wd(d,f);f=L.create(a,d);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}L.chmod(f,d|146);a=L.open(f,577);L.write(a,c,0,c.length,0,g);L.close(a);L.chmod(f,d)}return f},lc:function(a,b,c,d){a=Qb("string"===typeof a?a:L.mc(a),b);b=L.wd(!!c,!!d);L.lc.Bd||(L.lc.Bd=64);var f=L.tc(L.lc.Bd++,0);L.Id(f,{open:function(g){g.seekable=!1},close:function(){d&&
d.buffer&&d.buffer.length&&d(10)},read:function(g,k,m,p){for(var q=0,r=0;r<p;r++){try{var y=c()}catch(F){throw new L.Ib(29);}if(void 0===y&&0===q)throw new L.Ib(6);if(null===y||void 0===y)break;q++;k[m+r]=y}q&&(g.node.timestamp=Date.now());return q},write:function(g,k,m,p){for(var q=0;q<p;q++)try{d(k[m+q])}catch(r){throw new L.Ib(29);}p&&(g.node.timestamp=Date.now());return q}});return L.ad(a,b,f)},$d:function(a){if(a.zd||a.Te||a.link||a.Lb)return!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");
if(oa)try{a.Lb=Xb(oa(a.url),!0),a.Pb=a.Lb.length}catch(b){throw new L.Ib(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");},Hf:function(a,b,c,d,f){function g(){this.Ad=!1;this.xc=[]}g.prototype.get=function(q){if(!(q>this.length-1||0>q)){var r=q%this.chunkSize;return this.de(q/this.chunkSize|0)[r]}};g.prototype.re=function(q){this.de=q};g.prototype.Pd=function(){var q=new XMLHttpRequest;q.open("HEAD",c,!1);q.send(null);if(!(200<=q.status&&300>q.status||304===q.status))throw Error("Couldn't load "+
c+". Status: "+q.status);var r=Number(q.getResponseHeader("Content-length")),y,F=(y=q.getResponseHeader("Accept-Ranges"))&&"bytes"===y;q=(y=q.getResponseHeader("Content-Encoding"))&&"gzip"===y;var n=1048576;F||(n=r);var v=this;v.re(function(w){var O=w*n,R=(w+1)*n-1;R=Math.min(R,r-1);if("undefined"===typeof v.xc[w]){var wb=v.xc;if(O>R)throw Error("invalid range ("+O+", "+R+") or no bytes requested!");if(R>r-1)throw Error("only "+r+" bytes available! programmer error!");var G=new XMLHttpRequest;G.open("GET",
c,!1);r!==n&&G.setRequestHeader("Range","bytes="+O+"-"+R);"undefined"!=typeof Uint8Array&&(G.responseType="arraybuffer");G.overrideMimeType&&G.overrideMimeType("text/plain; charset=x-user-defined");G.send(null);if(!(200<=G.status&&300>G.status||304===G.status))throw Error("Couldn't load "+c+". Status: "+G.status);O=void 0!==G.response?new Uint8Array(G.response||[]):Xb(G.responseText||"",!0);wb[w]=O}if("undefined"===typeof v.xc[w])throw Error("doXHR failed!");return v.xc[w]});if(q||!r)n=r=1,n=r=this.de(0).length,
ea("LazyFiles on gzip forces download of the whole file when length is accessed");this.we=r;this.ve=n;this.Ad=!0};if("undefined"!==typeof XMLHttpRequest){if(!l)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new g;Object.defineProperties(k,{length:{get:function(){this.Ad||this.Pd();return this.we}},chunkSize:{get:function(){this.Ad||this.Pd();return this.ve}}});k={zd:!1,Lb:k}}else k={zd:!1,url:c};var m=L.Ee(a,b,k,d,f);
k.Lb?m.Lb=k.Lb:k.url&&(m.Lb=null,m.url=k.url);Object.defineProperties(m,{Pb:{get:function(){return this.Lb.length}}});var p={};Object.keys(m.Kb).forEach(function(q){var r=m.Kb[q];p[q]=function(){L.$d(m);return r.apply(null,arguments)}});p.read=function(q,r,y,F,n){L.$d(m);q=q.node.Lb;if(n>=q.length)return 0;F=Math.min(q.length-n,F);if(q.slice)for(var v=0;v<F;v++)r[y+v]=q[n+v];else for(v=0;v<F;v++)r[y+v]=q.get(n+v);return F};m.Kb=p;return m},Jf:function(a,b,c,d,f,g,k,m,p,q){function r(F){function n(w){q&&
q();m||L.Rd(a,b,w,d,f,p);g&&g();fb()}var v=!1;e.preloadPlugins.forEach(function(w){!v&&w.canHandle(y)&&(w.handle(F,y,n,function(){k&&k();fb()}),v=!0)});v||n(F)}$b.Lc();var y=b?Sb(Qb(a,b)):a;eb();"string"==typeof c?$b.Cf(c,function(F){r(F)},k):r(c)},indexedDB:function(){return window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB},Kd:function(){return"EM_FS_"+window.location.pathname},Ld:20,Hc:"FILE_DATA",$f:function(a,b,c){b=b||function(){};c=c||function(){};var d=L.indexedDB();
try{var f=d.open(L.Kd(),L.Ld)}catch(g){return c(g)}f.onupgradeneeded=function(){ea("creating db");f.result.createObjectStore(L.Hc)};f.onsuccess=function(){var g=f.result.transaction([L.Hc],"readwrite"),k=g.objectStore(L.Hc),m=0,p=0,q=a.length;a.forEach(function(r){r=k.put(L.rd(r).object.Lb,r);r.onsuccess=function(){m++;m+p==q&&(0==p?b():c())};r.onerror=function(){p++;m+p==q&&(0==p?b():c())}});g.onerror=c};f.onerror=c},Sf:function(a,b,c){b=b||function(){};c=c||function(){};var d=L.indexedDB();try{var f=
d.open(L.Kd(),L.Ld)}catch(g){return c(g)}f.onupgradeneeded=c;f.onsuccess=function(){var g=f.result;try{var k=g.transaction([L.Hc],"readonly")}catch(y){c(y);return}var m=k.objectStore(L.Hc),p=0,q=0,r=a.length;a.forEach(function(y){var F=m.get(y);F.onsuccess=function(){L.rd(y).exists&&L.unlink(y);L.Rd(Ob(y),Pb(y),F.result,!0,!0,!0);p++;p+q==r&&(0==q?b():c())};F.onerror=function(){q++;p+q==r&&(0==q?b():c())}});k.onerror=c};f.onerror=c}},ac={};
function bc(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&Nb(b)!==Nb(L.mc(f.node)))return-54;throw f;}I[c>>2]=d.dev;I[c+4>>2]=0;I[c+8>>2]=d.ino;I[c+12>>2]=d.mode;I[c+16>>2]=d.nlink;I[c+20>>2]=d.uid;I[c+24>>2]=d.gid;I[c+28>>2]=d.rdev;I[c+32>>2]=0;Q=[d.size>>>0,(P=d.size,1<=+Math.abs(P)?0<P?(Math.min(+Math.floor(P/4294967296),4294967295)|0)>>>0:~~+Math.ceil((P-+(~~P>>>0))/4294967296)>>>0:0)];I[c+40>>2]=Q[0];I[c+44>>2]=Q[1];I[c+48>>2]=4096;I[c+52>>2]=d.blocks;I[c+56>>2]=d.atime.getTime()/1E3|0;I[c+60>>
2]=0;I[c+64>>2]=d.mtime.getTime()/1E3|0;I[c+68>>2]=0;I[c+72>>2]=d.ctime.getTime()/1E3|0;I[c+76>>2]=0;Q=[d.ino>>>0,(P=d.ino,1<=+Math.abs(P)?0<P?(Math.min(+Math.floor(P/4294967296),4294967295)|0)>>>0:~~+Math.ceil((P-+(~~P>>>0))/4294967296)>>>0:0)];I[c+80>>2]=Q[0];I[c+84>>2]=Q[1];return 0}var cc=void 0;function dc(){cc+=4;return I[cc-4>>2]}function ec(a){a=L.dc(a);if(!a)throw new L.Ib(8);return a}
function fc(a,b,c,d,f){if(u)return U(3,1,a,b,c,d,f);try{f=0;for(var g=b?I[b>>2]:0,k=b?I[b+4>>2]:0,m=c?I[c>>2]:0,p=c?I[c+4>>2]:0,q=d?I[d>>2]:0,r=d?I[d+4>>2]:0,y=0,F=0,n=0,v=0,w=0,O=0,R=(b?I[b>>2]:0)|(c?I[c>>2]:0)|(d?I[d>>2]:0),wb=(b?I[b+4>>2]:0)|(c?I[c+4>>2]:0)|(d?I[d+4>>2]:0),G=0;G<a;G++){var S=1<<G%32;if(32>G?R&S:wb&S){var Ya=L.dc(G);if(!Ya)throw new L.Ib(8);var Za=5;Ya.Kb.Cc&&(Za=Ya.Kb.Cc(Ya));Za&1&&(32>G?g&S:k&S)&&(32>G?y|=S:F|=S,f++);Za&4&&(32>G?m&S:p&S)&&(32>G?n|=S:v|=S,f++);Za&2&&(32>G?q&S:
r&S)&&(32>G?w|=S:O|=S,f++)}}b&&(I[b>>2]=y,I[b+4>>2]=F);c&&(I[c>>2]=n,I[c+4>>2]=v);d&&(I[d>>2]=w,I[d+4>>2]=O);return f}catch(zb){return"undefined"!==typeof L&&zb instanceof L.Ib||z(zb),-zb.Mb}}
var M={Ob:function(){e.websocket=e.websocket&&"object"===typeof e.websocket?e.websocket:{};e.websocket.od={};e.websocket.on=function(a,b){"function"===typeof b&&(this.od[a]=b);return this};e.websocket.emit=function(a,b){"function"===typeof this.od[a]&&this.od[a].call(this,b)};return L.createNode(null,"/",16895,0)},createSocket:function(a,b,c){b&=-526337;c&&assert(1==b==(6==c));a={family:a,type:b,protocol:c,Sb:null,error:null,Qc:{},pending:[],Dc:[],Zb:M.Vb};b=M.bd();c=L.createNode(M.root,b,49152,0);
c.Ec=a;b=L.Sd({path:b,node:c,flags:2,seekable:!1,Kb:M.Kb});a.stream=b;return a},Ne:function(a){return(a=L.dc(a))&&L.isSocket(a.node.mode)?a.node.Ec:null},Kb:{Cc:function(a){a=a.node.Ec;return a.Zb.Cc(a)},yc:function(a,b,c){a=a.node.Ec;return a.Zb.yc(a,b,c)},read:function(a,b,c,d){a=a.node.Ec;d=a.Zb.ke(a,d);if(!d)return 0;b.set(d.buffer,c);return d.buffer.length},write:function(a,b,c,d){a=a.node.Ec;return a.Zb.ne(a,b,c,d)},close:function(a){a=a.node.Ec;a.Zb.close(a)}},bd:function(){M.bd.current||(M.bd.current=
0);return"socket["+M.bd.current++ +"]"},Vb:{Wc:function(a,b,c){if("object"===typeof b){var d=b;c=b=null}if(d)if(d._socket)b=d._socket.remoteAddress,c=d._socket.remotePort;else{c=/ws[s]?:\/\/([^:]+):(\d+)/.exec(d.url);if(!c)throw Error("WebSocket URL must be in the format ws(s)://address:port");b=c[1];c=parseInt(c[2],10)}else try{var f=e.websocket&&"object"===typeof e.websocket,g="ws:#".replace("#","//");f&&"string"===typeof e.websocket.url&&(g=e.websocket.url);if("ws://"===g||"wss://"===g){var k=
b.split("/");g=g+k[0]+":"+c+"/"+k.slice(1).join("/")}k="binary";f&&"string"===typeof e.websocket.subprotocol&&(k=e.websocket.subprotocol);var m=void 0;"null"!==k&&(k=k.replace(/^ +| +$/g,"").split(/ *, */),m=t?{protocol:k.toString()}:k);f&&null===e.websocket.subprotocol&&(m=void 0);d=new (t?require("ws"):WebSocket)(g,m);d.binaryType="arraybuffer"}catch(p){throw new L.Ib(23);}b={Qb:b,port:c,socket:d,Xc:[]};M.Vb.Nd(a,b);M.Vb.Oe(a,b);2===a.type&&"undefined"!==typeof a.vc&&b.Xc.push(new Uint8Array([255,
255,255,255,112,111,114,116,(a.vc&65280)>>8,a.vc&255]));return b},Yc:function(a,b,c){return a.Qc[b+":"+c]},Nd:function(a,b){a.Qc[b.Qb+":"+b.port]=b},le:function(a,b){delete a.Qc[b.Qb+":"+b.port]},Oe:function(a,b){function c(){e.websocket.emit("open",a.stream.fd);try{for(var g=b.Xc.shift();g;)b.socket.send(g),g=b.Xc.shift()}catch(k){b.socket.close()}}function d(g){if("string"===typeof g)g=(new TextEncoder).encode(g);else{assert(void 0!==g.byteLength);if(0==g.byteLength)return;g=new Uint8Array(g)}var k=
f;f=!1;k&&10===g.length&&255===g[0]&&255===g[1]&&255===g[2]&&255===g[3]&&112===g[4]&&111===g[5]&&114===g[6]&&116===g[7]?(g=g[8]<<8|g[9],M.Vb.le(a,b),b.port=g,M.Vb.Nd(a,b)):(a.Dc.push({Qb:b.Qb,port:b.port,data:g}),e.websocket.emit("message",a.stream.fd))}var f=!0;t?(b.socket.on("open",c),b.socket.on("message",function(g,k){k.Df&&d((new Uint8Array(g)).buffer)}),b.socket.on("close",function(){e.websocket.emit("close",a.stream.fd)}),b.socket.on("error",function(){a.error=14;e.websocket.emit("error",[a.stream.fd,
a.error,"ECONNREFUSED: Connection refused"])})):(b.socket.onopen=c,b.socket.onclose=function(){e.websocket.emit("close",a.stream.fd)},b.socket.onmessage=function(g){d(g.data)},b.socket.onerror=function(){a.error=14;e.websocket.emit("error",[a.stream.fd,a.error,"ECONNREFUSED: Connection refused"])})},Cc:function(a){if(1===a.type&&a.Sb)return a.pending.length?65:0;var b=0,c=1===a.type?M.Vb.Yc(a,a.Yb,a.$b):null;if(a.Dc.length||!c||c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b|=
65;if(!c||c&&c.socket.readyState===c.socket.OPEN)b|=4;if(c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b|=16;return b},yc:function(a,b,c){switch(b){case 21531:return b=0,a.Dc.length&&(b=a.Dc[0].data.length),I[c>>2]=b,0;default:return 28}},close:function(a){if(a.Sb){try{a.Sb.close()}catch(f){}a.Sb=null}for(var b=Object.keys(a.Qc),c=0;c<b.length;c++){var d=a.Qc[b[c]];try{d.socket.close()}catch(f){}M.Vb.le(a,d)}return 0},bind:function(a,b,c){if("undefined"!==typeof a.ed||
"undefined"!==typeof a.vc)throw new L.Ib(28);a.ed=b;a.vc=c;if(2===a.type){a.Sb&&(a.Sb.close(),a.Sb=null);try{a.Zb.listen(a,0)}catch(d){if(!(d instanceof L.Ib))throw d;if(138!==d.Mb)throw d;}}},connect:function(a,b,c){if(a.Sb)throw new L.Ib(138);if("undefined"!==typeof a.Yb&&"undefined"!==typeof a.$b){var d=M.Vb.Yc(a,a.Yb,a.$b);if(d){if(d.socket.readyState===d.socket.CONNECTING)throw new L.Ib(7);throw new L.Ib(30);}}b=M.Vb.Wc(a,b,c);a.Yb=b.Qb;a.$b=b.port;throw new L.Ib(26);},listen:function(a){if(!t)throw new L.Ib(138);
if(a.Sb)throw new L.Ib(28);var b=require("ws").Server;a.Sb=new b({host:a.ed,port:a.vc});e.websocket.emit("listen",a.stream.fd);a.Sb.on("connection",function(c){if(1===a.type){var d=M.createSocket(a.family,a.type,a.protocol);c=M.Vb.Wc(d,c);d.Yb=c.Qb;d.$b=c.port;a.pending.push(d);e.websocket.emit("connection",d.stream.fd)}else M.Vb.Wc(a,c),e.websocket.emit("connection",a.stream.fd)});a.Sb.on("closed",function(){e.websocket.emit("close",a.stream.fd);a.Sb=null});a.Sb.on("error",function(){a.error=23;
e.websocket.emit("error",[a.stream.fd,a.error,"EHOSTUNREACH: Host is unreachable"])})},accept:function(a){if(!a.Sb)throw new L.Ib(28);var b=a.pending.shift();b.stream.flags=a.stream.flags;return b},Pf:function(a,b){if(b){if(void 0===a.Yb||void 0===a.$b)throw new L.Ib(53);b=a.Yb;a=a.$b}else b=a.ed||0,a=a.vc||0;return{Qb:b,port:a}},ne:function(a,b,c,d,f,g){if(2===a.type){if(void 0===f||void 0===g)f=a.Yb,g=a.$b;if(void 0===f||void 0===g)throw new L.Ib(17);}else f=a.Yb,g=a.$b;var k=M.Vb.Yc(a,f,g);if(1===
a.type){if(!k||k.socket.readyState===k.socket.CLOSING||k.socket.readyState===k.socket.CLOSED)throw new L.Ib(53);if(k.socket.readyState===k.socket.CONNECTING)throw new L.Ib(6);}ArrayBuffer.isView(b)&&(c+=b.byteOffset,b=b.buffer);var m;b instanceof SharedArrayBuffer?m=(new Uint8Array(new Uint8Array(b.slice(c,c+d)))).buffer:m=b.slice(c,c+d);if(2===a.type&&(!k||k.socket.readyState!==k.socket.OPEN))return k&&k.socket.readyState!==k.socket.CLOSING&&k.socket.readyState!==k.socket.CLOSED||(k=M.Vb.Wc(a,f,
g)),k.Xc.push(m),d;try{return k.socket.send(m),d}catch(p){throw new L.Ib(28);}},ke:function(a,b){if(1===a.type&&a.Sb)throw new L.Ib(53);var c=a.Dc.shift();if(!c){if(1===a.type){if(a=M.Vb.Yc(a,a.Yb,a.$b)){if(a.socket.readyState===a.socket.CLOSING||a.socket.readyState===a.socket.CLOSED)return null;throw new L.Ib(6);}throw new L.Ib(53);}throw new L.Ib(6);}var d=c.data.byteLength||c.data.length,f=c.data.byteOffset||0,g=c.data.buffer||c.data;b=Math.min(b,d);var k={buffer:new Uint8Array(g,f,b),Qb:c.Qb,
port:c.port};1===a.type&&b<d&&(c.data=new Uint8Array(g,f+b,d-b),a.Dc.unshift(c));return k}}};function X(a){a=M.Ne(a);if(!a)throw new L.Ib(8);return a}function hc(a){a=a.split(".");for(var b=0;4>b;b++){var c=Number(a[b]);if(isNaN(c))return null;a[b]=c}return(a[0]|a[1]<<8|a[2]<<16|a[3]<<24)>>>0}
function ic(a){var b,c,d=[];if(!/^((?=.*::)(?!.*::.+::)(::)?([\dA-F]{1,4}:(:|\b)|){5}|([\dA-F]{1,4}:){6})((([\dA-F]{1,4}((?!\3)::|:\b|$))|(?!\2\3)){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})$/i.test(a))return null;if("::"===a)return[0,0,0,0,0,0,0,0];a=a.startsWith("::")?a.replace("::","Z:"):a.replace("::",":Z:");0<a.indexOf(".")?(a=a.replace(/[.]/g,":"),a=a.split(":"),a[a.length-4]=parseInt(a[a.length-4])+256*parseInt(a[a.length-3]),a[a.length-3]=parseInt(a[a.length-2])+256*parseInt(a[a.length-
1]),a=a.slice(0,a.length-2)):a=a.split(":");for(b=c=0;b<a.length;b++)if("string"===typeof a[b])if("Z"===a[b]){for(c=0;c<8-a.length+1;c++)d[b+c]=0;--c}else d[b+c]=jc(parseInt(a[b],16));else d[b+c]=a[b];return[d[1]<<16|d[0],d[3]<<16|d[2],d[5]<<16|d[4],d[7]<<16|d[6]]}
function kc(a,b,c,d,f){switch(b){case 2:c=hc(c);f&&(I[f>>2]=16);H[a>>1]=b;I[a+4>>2]=c;H[a+2>>1]=jc(d);Q=[0,(P=0,1<=+Math.abs(P)?0<P?(Math.min(+Math.floor(P/4294967296),4294967295)|0)>>>0:~~+Math.ceil((P-+(~~P>>>0))/4294967296)>>>0:0)];I[a+8>>2]=Q[0];I[a+12>>2]=Q[1];break;case 10:c=ic(c);f&&(I[f>>2]=28);I[a>>2]=b;I[a+8>>2]=c[0];I[a+12>>2]=c[1];I[a+16>>2]=c[2];I[a+20>>2]=c[3];H[a+2>>1]=jc(d);I[a+4>>2]=0;I[a+24>>2]=0;break;default:return 5}return 0}var lc=1,mc={},nc={};
function oc(a){var b=hc(a);if(null!==b)return a;b=ic(a);if(null!==b)return a;mc[a]?b=mc[a]:(b=lc++,assert(65535>b,"exceeded max address mappings of 65535"),b="172.29."+(b&255)+"."+(b&65280),nc[b]=a,mc[a]=b);return b}function pc(a,b,c,d){if(u)return U(4,1,a,b,c,d);try{var f=X(a),g=f.Zb.accept(f);b&&kc(b,g.family,oc(g.Yb),g.$b,c);return g.stream.fd}catch(k){return"undefined"!==typeof L&&k instanceof L.Ib||z(k),-k.Mb}}
function qc(a,b){if(u)return U(5,1,a,b);try{a=C(a);if(b&-8)var c=-28;else{var d;(d=L.Nb(a,{ac:!0}).node)?(a="",b&4&&(a+="r"),b&2&&(a+="w"),b&1&&(a+="x"),c=a&&L.nc(d,a)?-2:0):c=-44}return c}catch(f){return"undefined"!==typeof L&&f instanceof L.Ib||z(f),-f.Mb}}function rc(a){return(a&255)+"."+(a>>8&255)+"."+(a>>16&255)+"."+(a>>24&255)}
function sc(a){var b="",c,d=0,f=0,g=0,k=0;a=[a[0]&65535,a[0]>>16,a[1]&65535,a[1]>>16,a[2]&65535,a[2]>>16,a[3]&65535,a[3]>>16];var m=!0;for(c=0;5>c;c++)if(0!==a[c]){m=!1;break}if(m){c=rc(a[6]|a[7]<<16);if(-1===a[5])return"::ffff:"+c;if(0===a[5])return"0.0.0.0"===c&&(c=""),"0.0.0.1"===c&&(c="1"),"::"+c}for(c=0;8>c;c++)0===a[c]&&(1<c-f&&(k=0),f=c,k++),k>d&&(d=k,g=c-d+1);for(c=0;8>c;c++)1<d&&0===a[c]&&c>=g&&c<g+d?c===g&&(b+=":",0===g&&(b+=":")):(b+=Number(tc(a[c]&65535)).toString(16),b+=7>c?":":"");return b}
function uc(a,b){var c=H[a>>1],d=tc(Oa[a+2>>1]);switch(c){case 2:if(16!==b)return{Mb:28};a=I[a+4>>2];a=rc(a);break;case 10:if(28!==b)return{Mb:28};a=[I[a+8>>2],I[a+12>>2],I[a+16>>2],I[a+20>>2]];a=sc(a);break;default:return{Mb:5}}return{family:c,Qb:a,port:d}}function vc(a,b,c){if(c&&0===a)return null;a=uc(a,b);if(a.Mb)throw new L.Ib(a.Mb);b=a.Qb;a.Qb=(nc[b]?nc[b]:null)||a.Qb;return a}
function wc(a,b,c){if(u)return U(6,1,a,b,c);try{var d=X(a),f=vc(b,c);d.Zb.bind(d,f.Qb,f.port);return 0}catch(g){return"undefined"!==typeof L&&g instanceof L.Ib||z(g),-g.Mb}}function xc(a,b,c){if(u)return U(7,1,a,b,c);try{var d=X(a),f=vc(b,c);d.Zb.connect(d,f.Qb,f.port);return 0}catch(g){return"undefined"!==typeof L&&g instanceof L.Ib||z(g),-g.Mb}}
function yc(a,b,c){if(u)return U(8,1,a,b,c);cc=c;try{var d=ec(a);switch(b){case 0:var f=dc();return 0>f?-28:L.open(d.path,d.flags,0,f).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return f=dc(),d.flags|=f,0;case 12:return f=dc(),H[f+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return I[Eb()>>2]=28,-1;default:return-28}}catch(g){return"undefined"!==typeof L&&g instanceof L.Ib||z(g),-g.Mb}}
function zc(a,b){if(u)return U(9,1,a,b);try{var c=ec(a);return bc(L.stat,c.path,b)}catch(d){return"undefined"!==typeof L&&d instanceof L.Ib||z(d),-d.Mb}}
function Ac(a,b,c){if(u)return U(10,1,a,b,c);try{var d=ec(a);d.qc||(d.qc=L.readdir(d.path));a=0;for(var f=L.Wb(d,0,1),g=Math.floor(f/280);g<d.qc.length&&a+280<=c;){var k=d.qc[g];if("."===k[0]){var m=1;var p=4}else{var q=L.ec(d.node,k);m=q.id;p=L.Mc(q.mode)?2:L.Rb(q.mode)?4:L.rc(q.mode)?10:8}Q=[m>>>0,(P=m,1<=+Math.abs(P)?0<P?(Math.min(+Math.floor(P/4294967296),4294967295)|0)>>>0:~~+Math.ceil((P-+(~~P>>>0))/4294967296)>>>0:0)];I[b+a>>2]=Q[0];I[b+a+4>>2]=Q[1];Q=[280*(g+1)>>>0,(P=280*(g+1),1<=+Math.abs(P)?
0<P?(Math.min(+Math.floor(P/4294967296),4294967295)|0)>>>0:~~+Math.ceil((P-+(~~P>>>0))/4294967296)>>>0:0)];I[b+a+8>>2]=Q[0];I[b+a+12>>2]=Q[1];H[b+a+16>>1]=280;A[b+a+18>>0]=p;Da(k,b+a+19,256);a+=280;g+=1}L.Wb(d,280*g,0);return a}catch(r){return"undefined"!==typeof L&&r instanceof L.Ib||z(r),-r.Mb}}function Bc(a,b,c){if(u)return U(11,1,a,b,c);try{var d=X(a);if(!d.Yb)return-53;kc(b,d.family,oc(d.Yb),d.$b,c);return 0}catch(f){return"undefined"!==typeof L&&f instanceof L.Ib||z(f),-f.Mb}}
function Cc(a,b){if(u)return U(12,1,a,b);try{return Dc(b,0,136),I[b>>2]=1,I[b+4>>2]=2,I[b+8>>2]=3,I[b+12>>2]=4,0}catch(c){return"undefined"!==typeof L&&c instanceof L.Ib||z(c),-c.Mb}}function Ec(a,b,c){if(u)return U(13,1,a,b,c);try{h("__sys_getsockname "+a);var d=X(a);kc(b,d.family,oc(d.ed||"0.0.0.0"),d.vc,c);return 0}catch(f){return"undefined"!==typeof L&&f instanceof L.Ib||z(f),-f.Mb}}
function Fc(a,b,c,d,f){if(u)return U(14,1,a,b,c,d,f);try{var g=X(a);return 1===b&&4===c?(I[d>>2]=g.error,I[f>>2]=4,g.error=null,0):-50}catch(k){return"undefined"!==typeof L&&k instanceof L.Ib||z(k),-k.Mb}}
function Gc(a,b,c){if(u)return U(15,1,a,b,c);cc=c;try{var d=ec(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var f=dc();return I[f>>2]=0;case 21520:return d.tty?-28:-59;case 21531:return f=dc(),L.yc(d,b,f);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:z("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof L&&g instanceof L.Ib||z(g),-g.Mb}}
function Hc(a,b){if(u)return U(16,1,a,b);try{var c=X(a);c.Zb.listen(c,b);return 0}catch(d){return"undefined"!==typeof L&&d instanceof L.Ib||z(d),-d.Mb}}function Ic(a,b){if(u)return U(17,1,a,b);try{return a=C(a),bc(L.lstat,a,b)}catch(c){return"undefined"!==typeof L&&c instanceof L.Ib||z(c),-c.Mb}}function Jc(a,b){if(u)return U(18,1,a,b);try{return a=C(a),a=Nb(a),"/"===a[a.length-1]&&(a=a.substr(0,a.length-1)),L.mkdir(a,b,0),0}catch(c){return"undefined"!==typeof L&&c instanceof L.Ib||z(c),-c.Mb}}
function Kc(a,b,c,d,f,g){if(u)return U(19,1,a,b,c,d,f,g);try{a:{g<<=12;var k=!1;if(0!==(d&16)&&0!==a%65536)var m=-28;else{if(0!==(d&32)){var p=Lc(65536,b);if(!p){m=-48;break a}Dc(p,0,b);k=!0}else{var q=L.dc(f);if(!q){m=-8;break a}var r=L.zc(q,a,b,g,c,d);p=r.gf;k=r.pd}ac[p]={Xe:p,Ue:b,pd:k,fd:f,ff:c,flags:d,offset:g};m=p}}return m}catch(y){return"undefined"!==typeof L&&y instanceof L.Ib||z(y),-y.Mb}}
function Mc(a,b){if(u)return U(20,1,a,b);try{if(-1===(a|0)||0===b)var c=-28;else{var d=ac[a];if(d&&b===d.Ue){var f=L.dc(d.fd);if(f&&d.ff&2){var g=d.flags,k=d.offset,m=Ha.slice(a,a+b);L.Ac(f,m,k,b,g)}ac[a]=null;d.pd&&tb(d.Xe)}c=0}return c}catch(p){return"undefined"!==typeof L&&p instanceof L.Ib||z(p),-p.Mb}}function Nc(a,b,c){if(u)return U(21,1,a,b,c);cc=c;try{var d=C(a),f=c?dc():0;return L.open(d,b,f).fd}catch(g){return"undefined"!==typeof L&&g instanceof L.Ib||z(g),-g.Mb}}
function Oc(a,b,c){if(u)return U(22,1,a,b,c);try{for(var d=c=0;d<b;d++){var f=a+8*d,g=H[f+4>>1],k=32,m=L.dc(I[f>>2]);m&&(k=5,m.Kb.Cc&&(k=m.Kb.Cc(m)));(k&=g|24)&&c++;H[f+6>>1]=k}return c}catch(p){return"undefined"!==typeof L&&p instanceof L.Ib||z(p),-p.Mb}}function Pc(a,b,c,d){if(u)return U(23,1,a,b,c,d);try{return d&&(I[d>>2]=-1,I[d+4>>2]=-1,I[d+8>>2]=-1,I[d+12>>2]=-1),0}catch(f){return"undefined"!==typeof L&&f instanceof L.Ib||z(f),-f.Mb}}
function Qc(a,b,c,d,f,g){if(u)return U(24,1,a,b,c,d,f,g);try{var k=X(a),m=k.Zb.ke(k,c);if(!m)return 0;f&&kc(f,k.family,oc(m.Qb),m.port,g);Ha.set(m.buffer,b);return m.buffer.byteLength}catch(p){return"undefined"!==typeof L&&p instanceof L.Ib||z(p),-p.Mb}}function Rc(a,b){if(u)return U(25,1,a,b);try{return a=C(a),b=C(b),L.rename(a,b),0}catch(c){return"undefined"!==typeof L&&c instanceof L.Ib||z(c),-c.Mb}}
function Sc(a){if(u)return U(26,1,a);try{return a=C(a),L.rmdir(a),0}catch(b){return"undefined"!==typeof L&&b instanceof L.Ib||z(b),-b.Mb}}function Tc(a,b,c,d,f,g){if(u)return U(27,1,a,b,c,d,f,g);try{var k=X(a),m=vc(f,g,!0);return m?k.Zb.ne(k,A,b,c,m.Qb,m.port):L.write(k.stream,A,b,c)}catch(p){return"undefined"!==typeof L&&p instanceof L.Ib||z(p),-p.Mb}}function Uc(a){return u?U(28,1,a):-50}
function Vc(a,b){if(u)return U(29,1,a,b);try{return X(a),-52}catch(c){return"undefined"!==typeof L&&c instanceof L.Ib||z(c),-c.Mb}}function Wc(a,b,c){if(u)return U(30,1,a,b,c);try{return M.createSocket(a,b,c).stream.fd}catch(d){return"undefined"!==typeof L&&d instanceof L.Ib||z(d),-d.Mb}}function Xc(a,b){if(u)return U(31,1,a,b);try{return a=C(a),bc(L.stat,a,b)}catch(c){return"undefined"!==typeof L&&c instanceof L.Ib||z(c),-c.Mb}}
function Yc(a){if(u)return U(32,1,a);try{return a=C(a),L.unlink(a),0}catch(b){return"undefined"!==typeof L&&b instanceof L.Ib||z(b),-b.Mb}}function Zc(){void 0===Zc.start&&(Zc.start=Date.now());return 1E3*(Date.now()-Zc.start)|0}var $c=[];
function ad(){t||l||(ua||(ua={}),ua["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(ua["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,h("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))}
function bd(a,b,c){if(0>=a||a>A.length||a&1)return-28;if(la){if(Atomics.load(I,a>>2)!=b)return-6;var d=performance.now();c=d+c;for(Atomics.exchange(I,mb>>2,a);;){d=performance.now();if(d>c)return Atomics.exchange(I,mb>>2,0),-73;d=Atomics.exchange(I,mb>>2,0);if(0==d)break;vb();if(Atomics.load(I,a>>2)!=b)return-6;Atomics.exchange(I,mb>>2,a)}return 0}a=Atomics.wait(I,a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+
a;}function U(a,b){for(var c=arguments.length-2,d=B(),f=Ca(8*c),g=f>>3,k=0;k<c;k++)Qa[g+k]=arguments[2+k];c=cd(a,c,f,b);D(d);return c}var dd=[],ed=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function fd(a){a=2<a?C(a):a;return ed[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function gd(a,b,c){var d=fd(a);if(!d)return-4;d.Vc&&(I[d.Vc>>2]=b,I[d.Vc+4>>2]=c);if(d.ie||!d.Gf)d.ie&&(d=d.ie),a=!1,d.Uc&&d.Uc.Tc&&(a=d.Uc.Tc.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.Uc.Tc.viewport(0,0,b,c);else{if(d.Vc){d=I[d.Vc+8>>2];a=a?C(a):"";var f=B(),g=Ca(12),k=0;if(a){k=Ja(a)+1;var m=E(k);Da(a,m,k);k=m}I[g>>2]=k;I[g+4>>2]=b;I[g+8>>2]=c;hd(0,d,657457152,0,k,g);D(f);return 1}return-4}return 0}
function jd(a,b,c){return u?U(33,1,a,b,c):gd(a,b,c)}function kd(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,g){b.drawArraysInstancedANGLE(c,d,f,g)},a.drawElementsInstanced=function(c,d,f,g,k){b.drawElementsInstancedANGLE(c,d,f,g,k)})}
function ld(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function md(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function nd(a,b){a.ae||(a.ae=a.getContext,a.getContext=function(d,f){f=a.ae(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl",b);return c?od(c,b):0}function od(a,b){var c=E(8);I[c+4>>2]=rb();var d={Qf:c,attributes:b,version:b.We,Tc:a};a.canvas&&(a.canvas.Uc=d);("undefined"===typeof b.Vd||b.Vd)&&pd(d);return c}
function pd(a){a||(a=qd);if(!a.Pe){a.Pe=!0;var b=a.Tc;kd(b);ld(b);md(b);b.Kf=b.getExtension("EXT_disjoint_timer_query");b.Wf=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var qd,rd=["default","low-power","high-performance"],sd={};
function td(){if(!ud){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ja||"./this.program"},b;for(b in sd)void 0===sd[b]?delete a[b]:a[b]=sd[b];var c=[];for(b in a)c.push(b+"="+a[b]);ud=c}return ud}var ud;
function vd(a,b){if(u)return U(34,1,a,b);try{var c=0;td().forEach(function(d,f){var g=b+c;I[a+4*f>>2]=g;Ma(d,g);c+=d.length+1});return 0}catch(d){return"undefined"!==typeof L&&d instanceof L.Ib||z(d),d.Mb}}function wd(a,b){if(u)return U(35,1,a,b);try{var c=td();I[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});I[b>>2]=d;return 0}catch(f){return"undefined"!==typeof L&&f instanceof L.Ib||z(f),f.Mb}}
function xd(a){if(u)return U(36,1,a);try{var b=ec(a);L.close(b);return 0}catch(c){return"undefined"!==typeof L&&c instanceof L.Ib||z(c),c.Mb}}function yd(a,b){if(u)return U(37,1,a,b);try{var c=ec(a);A[b>>0]=c.tty?2:L.Rb(c.mode)?3:L.rc(c.mode)?7:4;return 0}catch(d){return"undefined"!==typeof L&&d instanceof L.Ib||z(d),d.Mb}}
function zd(a,b,c,d){if(u)return U(38,1,a,b,c,d);try{a:{for(var f=ec(a),g=a=0;g<c;g++){var k=I[b+(8*g+4)>>2],m=L.read(f,A,I[b+8*g>>2],k,void 0);if(0>m){var p=-1;break a}a+=m;if(m<k)break}p=a}I[d>>2]=p;return 0}catch(q){return"undefined"!==typeof L&&q instanceof L.Ib||z(q),q.Mb}}
function Ad(a,b,c,d,f){if(u)return U(39,1,a,b,c,d,f);try{var g=ec(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;L.Wb(g,a,d);Q=[g.position>>>0,(P=g.position,1<=+Math.abs(P)?0<P?(Math.min(+Math.floor(P/4294967296),4294967295)|0)>>>0:~~+Math.ceil((P-+(~~P>>>0))/4294967296)>>>0:0)];I[f>>2]=Q[0];I[f+4>>2]=Q[1];g.qc&&0===a&&0===d&&(g.qc=null);return 0}catch(k){return"undefined"!==typeof L&&k instanceof L.Ib||z(k),k.Mb}}
function Bd(a,b,c,d){if(u)return U(40,1,a,b,c,d);try{a:{for(var f=ec(a),g=a=0;g<c;g++){var k=L.write(f,A,I[b+8*g>>2],I[b+(8*g+4)>>2],void 0);if(0>k){var m=-1;break a}a+=k}m=a}I[d>>2]=m;return 0}catch(p){return"undefined"!==typeof L&&p instanceof L.Ib||z(p),p.Mb}}var Y={};
function Cd(a){Cd.buffer||(Cd.buffer=E(256),Y["0"]="Success",Y["-1"]="Invalid value for 'ai_flags' field",Y["-2"]="NAME or SERVICE is unknown",Y["-3"]="Temporary failure in name resolution",Y["-4"]="Non-recoverable failure in name res",Y["-6"]="'ai_family' not supported",Y["-7"]="'ai_socktype' not supported",Y["-8"]="SERVICE not supported for 'ai_socktype'",Y["-10"]="Memory allocation failure",Y["-11"]="System error returned in 'errno'",Y["-12"]="Argument buffer overflow");var b="Unknown error";a in
Y&&(255<Y[a].length?b="Message too long":b=Y[a]);Ma(b,Cd.buffer);return Cd.buffer}
function Dd(a,b,c,d){function f(y,F,n,v,w,O){var R=10===y?28:16;w=10===y?sc(w):rc(w);R=E(R);w=kc(R,y,w,O);assert(!w);w=E(32);I[w+4>>2]=y;I[w+8>>2]=F;I[w+12>>2]=n;I[w+24>>2]=v;I[w+20>>2]=R;I[w+16>>2]=10===y?28:16;I[w+28>>2]=0;return w}if(u)return U(41,1,a,b,c,d);var g=0,k=0,m=0,p=0,q=0,r=0;c&&(m=I[c>>2],p=I[c+4>>2],q=I[c+8>>2],r=I[c+12>>2]);q&&!r&&(r=2===q?17:6);!q&&r&&(q=17===r?2:1);0===r&&(r=6);0===q&&(q=1);if(!a&&!b)return-2;if(m&-1088||0!==c&&I[c>>2]&2&&!a)return-1;if(m&32)return-2;if(0!==q&&1!==
q&&2!==q)return-7;if(0!==p&&2!==p&&10!==p)return-6;if(b&&(b=C(b),k=parseInt(b,10),isNaN(k)))return m&1024?-2:-8;if(!a)return 0===p&&(p=2),0===(m&1)&&(2===p?g=Ed(2130706433):g=[0,0,0,1]),a=f(p,q,r,null,g,k),I[d>>2]=a,0;a=C(a);g=hc(a);if(null!==g)if(0===p||2===p)p=2;else if(10===p&&m&8)g=[0,0,Ed(65535),g],p=10;else return-2;else if(g=ic(a),null!==g)if(0===p||10===p)p=10;else return-2;if(null!=g)return a=f(p,q,r,a,g,k),I[d>>2]=a,0;if(m&4)return-2;a=oc(a);g=hc(a);0===p?p=2:10===p&&(g=[0,0,Ed(65535),g]);
a=f(p,q,r,null,g,k);I[d>>2]=a;return 0}
function xb(a){if(u)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=T.Me();if(!b)return 6;if(void 0!==b.cc)throw"Internal error!";if(!a.cd)throw"Internal error, no pthread ptr!";T.oc.push(b);for(var c=E(512),d=0;128>d;++d)I[c+4*d>>2]=0;var f=a.wc+a.Fc;d=T.jc[a.cd]={worker:b,wc:a.wc,Fc:a.Fc,qd:a.qd,kc:a.cd};var g=d.kc>>2;Atomics.store(J,g+16,a.detached);Atomics.store(J,g+25,c);Atomics.store(J,g+10,d.kc);Atomics.store(J,g+20,a.Fc);Atomics.store(J,g+19,
f);Atomics.store(J,g+26,a.Fc);Atomics.store(J,g+28,f);Atomics.store(J,g+29,a.detached);c=Fd()+40;Atomics.store(J,g+43,c);b.cc=d;var k={cmd:"run",start_routine:a.pf,arg:a.Kc,threadInfoStruct:a.cd,stackBase:a.wc,stackSize:a.Fc};b.Rc=function(){k.time=performance.now();b.postMessage(k,a.zf)};b.loaded&&(b.Rc(),delete b.Rc);return 0}
function Gd(a,b){if(!a)return h("pthread_join attempted on a null thread pointer!"),71;if(u&&rb()==a)return h("PThread "+a+" is attempting to join to itself!"),16;if(!u&&Hd()==a)return h("Main thread "+a+" is attempting to join to itself!"),16;if(I[a+12>>2]!==a)return h("pthread_join attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;if(Atomics.load(J,a+64>>2))return h("Attempted to join thread "+a+", which was already detached!"),28;for(ad();;){var c=
Atomics.load(J,a>>2);if(1==c)return c=Atomics.load(J,a+4>>2),b&&(I[b>>2]=c),Atomics.store(J,a+64>>2,1),u?postMessage({cmd:"cleanupThread",thread:a}):ob(a),0;if(u){var d=rb();if(d&&!Atomics.load(J,d+56>>2)&&2==Atomics.load(J,d+0>>2))throw"Canceled!";}u||vb();bd(a,c,u?100:1)}}function Id(a){return 0===a%4&&(0!==a%100||0===a%400)}function Jd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Kd=[31,29,31,30,31,30,31,31,30,31,30,31],Ld=[31,28,31,30,31,30,31,31,30,31,30,31];
function Md(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Id(a.getFullYear())?Kd:Ld)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}function Nd(a,b,c,d){a||(a=this);this.parent=a;this.Ob=a.Ob;this.Oc=null;this.id=L.af++;this.name=b;this.mode=c;this.Jb={};this.Kb={};this.rdev=d}
Object.defineProperties(Nd.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Te:{get:function(){return L.Rb(this.mode)}},zd:{get:function(){return L.Mc(this.mode)}}});L.qe=Nd;L.qf();var $b;e.FS_mount=L.Ob;e.FS_unmount=L.Bf;e.FS_filesystems=L.Yd;
var Od=[null,function(a,b){if(u)return U(1,1,a,b)},Hb,fc,pc,qc,wc,xc,yc,zc,Ac,Bc,Cc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,jd,vd,wd,xd,yd,zd,Ad,Bd,Dd];function Xb(a,b){var c=Array(Ja(a)+1);a=Ia(a,c,0,c.length);b&&(c.length=a);return c}
var he={c:function(a,b,c,d){z("Assertion failed: "+C(a)+", at: "+[b?C(b):"unknown filename",c,d?C(d):"unknown function"])},Ja:function(a,b){Pd(a,b)},J:function(a,b){return Db(a,b)},Qa:function(a,b){return Fb(a,b)},na:function(a,b){return Gb(a,b)},ma:function(a,b){return Lb(a,b)},ya:fc,ca:pc,Ba:qc,fa:wc,ea:xc,q:yc,Ga:zc,ra:Ac,aa:Bc,ua:Cc,ba:Ec,Z:Fc,O:Gc,da:Hc,Ha:Ic,Ia:Jc,pa:Kc,qa:function(){return 0},oa:Mc,Ea:function(){return-63},Q:Nc,xa:Oc,ta:Pc,_:Qc,Fa:Rc,Ca:Sc,$:Tc,sa:function(){return 0},Y:Uc,
ga:Vc,I:Wc,R:Xc,va:function(a){try{if(!a)return-21;var b={__size__:390,domainname:325,machine:260,nodename:65,release:130,sysname:0,version:195};Ma("Emscripten",a+b.sysname);Ma("emscripten",a+b.nodename);Ma("1.0",a+b.release);Ma("#1",a+b.version);Ma("wasm32",a+b.machine);return 0}catch(c){return"undefined"!==typeof L&&c instanceof L.Ib||z(c),-c.Mb}},Da:Yc,Oa:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});else if(u)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=
(a=T.jc[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},ja:function(){throw"longjmp";},b:function(){z()},Pa:Zc,Ta:Db,W:function(){z("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},Ua:function(){z("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},T:function(a,b,c){$c.length=0;var d;for(c>>=2;d=Ha[b++];)(d=105>d)&&
c&1&&c++,$c.push(d?Qa[c++>>1]:I[c]),++c;return kb[a].apply(null,$c)},wa:ad,C:function(){},w:bd,v:lb,za:function(){return Ha.length},u:Cb,ha:function(a,b,c){Ha.copyWithin(a,b,b+c)},Aa:function(){return t?require("os").cpus().length:navigator.hardwareConcurrency},La:function(a,b,c){dd.length=b;c>>=3;for(var d=0;d<b;d++)dd[d]=Qa[c+d];return(0>a?kb[-a-1]:Od[a]).apply(null,dd)},ia:function(){z("OOM")},Ma:function(a,b,c){return fd(a)?gd(a,b,c):jd(a,b,c)},S:function(){},Ka:function(){},Na:function(a,b){b>>=
2;b={alpha:!!I[b],depth:!!I[b+1],stencil:!!I[b+2],antialias:!!I[b+3],premultipliedAlpha:!!I[b+4],preserveDrawingBuffer:!!I[b+5],powerPreference:rd[I[b+6]],failIfMajorPerformanceCaveat:!!I[b+7],We:I[b+8],Uf:I[b+9],Vd:I[b+10],Je:I[b+11],Yf:I[b+12],Zf:I[b+13]};a=fd(a);return!a||b.Je?0:nd(a,b)},ka:vd,la:wd,B:function(a){da(a)},A:xd,N:yd,P:zd,Va:Ad,E:Bd,x:Cd,d:function(){return va},t:Dd,r:function(a,b,c,d,f,g,k){b=uc(a,b);if(b.Mb)return-6;a=b.port;var m=b.Qb;b=!1;if(c&&d){var p;if(k&1||!(p=nc[m]?nc[m]:
null)){if(k&8)return-2}else m=p;c=Da(m,c,d);c+1>=d&&(b=!0)}f&&g&&(c=Da(""+a,f,g),c+1>=g&&(b=!0));return b?-12:0},i:function(a){var b=Date.now();I[a>>2]=b/1E3|0;I[a+4>>2]=b%1E3*1E3|0;return 0},o:Gb,Za:function(){T.Qe()},X:Qd,h:Rd,g:Sd,y:Td,H:Ud,V:Vd,G:Wd,Xa:Xd,Wa:Yd,j:Zd,s:$d,D:ae,f:be,F:ce,Sa:de,U:ee,Ya:fe,n:Lb,a:xa||e.wasmMemory,L:function(a){Hb();var b=new Date(I[a+20>>2]+1900,I[a+16>>2],I[a+12>>2],I[a+8>>2],I[a+4>>2],I[a>>2],0),c=I[a+32>>2],d=b.getTimezoneOffset(),f=new Date(b.getFullYear(),0,
1),g=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),k=f.getTimezoneOffset(),m=Math.min(k,g);0>c?I[a+32>>2]=Number(g!=k&&m==d):0<c!=(m==d)&&(g=Math.max(k,g),b.setTime(b.getTime()+6E4*((0<c?m:g)-d)));I[a+24>>2]=b.getDay();I[a+28>>2]=(b.getTime()-f.getTime())/864E5|0;I[a>>2]=b.getSeconds();I[a+4>>2]=b.getMinutes();I[a+8>>2]=b.getHours();I[a+12>>2]=b.getDate();I[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},Ra:function(a){if(a===Hd())return h("Main thread (id="+a+") cannot be canceled!"),71;if(!a)return h("pthread_cancel attempted on a null thread pointer!"),
71;if(I[a+12>>2]!==a)return h("pthread_cancel attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;Atomics.compareExchange(J,a>>2,0,2);u?postMessage({cmd:"cancelThread",thread:a}):nb(a);return 0},K:function(a){var b=T.hd.pop();a&&b()},M:Fb,l:function(a,b,c,d){if("undefined"===typeof SharedArrayBuffer)return h("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;if(!a)return h("pthread_create called with a null thread pointer!"),
28;var f=[];if(u&&0===f.length)return ge(687865856,a,b,c,d);var g=0,k=0;if(b&&-1!=b){var m=I[b>>2];m+=81920;g=I[b+8>>2];k=0!==I[b+12>>2]}else m=2097152;(b=0==g)?g=Lc(16,m):(g-=m,assert(0<g));for(var p=E(228),q=0;57>q;++q)J[(p>>2)+q]=0;I[a>>2]=p;I[p+12>>2]=p;a=p+152;I[a>>2]=a;c={wc:g,Fc:m,qd:b,detached:k,pf:c,cd:p,Kc:d,zf:f};return u?(c.Ff="spawnThread",postMessage(c,f),0):xb(c)},m:function(a,b){return Gd(a,b)},e:function(a){va=a},z:function(){return 0},k:function(a,b,c,d){function f(n,v,w){for(n=
"number"===typeof n?n.toString():n||"";n.length<v;)n=w[0]+n;return n}function g(n,v){return f(n,v,"0")}function k(n,v){function w(R){return 0>R?-1:0<R?1:0}var O;0===(O=w(n.getFullYear()-v.getFullYear()))&&0===(O=w(n.getMonth()-v.getMonth()))&&(O=w(n.getDate()-v.getDate()));return O}function m(n){switch(n.getDay()){case 0:return new Date(n.getFullYear()-1,11,29);case 1:return n;case 2:return new Date(n.getFullYear(),0,3);case 3:return new Date(n.getFullYear(),0,2);case 4:return new Date(n.getFullYear(),
0,1);case 5:return new Date(n.getFullYear()-1,11,31);case 6:return new Date(n.getFullYear()-1,11,30)}}function p(n){n=Md(new Date(n.Xb+1900,0,1),n.ld);var v=new Date(n.getFullYear()+1,0,4),w=m(new Date(n.getFullYear(),0,4));v=m(v);return 0>=k(w,n)?0>=k(v,n)?n.getFullYear()+1:n.getFullYear():n.getFullYear()-1}var q=I[d+40>>2];d={xf:I[d>>2],wf:I[d+4>>2],jd:I[d+8>>2],Sc:I[d+12>>2],Gc:I[d+16>>2],Xb:I[d+20>>2],kd:I[d+24>>2],ld:I[d+28>>2],bg:I[d+32>>2],vf:I[d+36>>2],yf:q?C(q):""};c=C(c);q={"%c":"%a %b %d %H:%M:%S %Y",
"%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in q)c=c.replace(new RegExp(r,"g"),q[r]);var y="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),F="January February March April May June July August September October November December".split(" ");
q={"%a":function(n){return y[n.kd].substring(0,3)},"%A":function(n){return y[n.kd]},"%b":function(n){return F[n.Gc].substring(0,3)},"%B":function(n){return F[n.Gc]},"%C":function(n){return g((n.Xb+1900)/100|0,2)},"%d":function(n){return g(n.Sc,2)},"%e":function(n){return f(n.Sc,2," ")},"%g":function(n){return p(n).toString().substring(2)},"%G":function(n){return p(n)},"%H":function(n){return g(n.jd,2)},"%I":function(n){n=n.jd;0==n?n=12:12<n&&(n-=12);return g(n,2)},"%j":function(n){return g(n.Sc+Jd(Id(n.Xb+
1900)?Kd:Ld,n.Gc-1),3)},"%m":function(n){return g(n.Gc+1,2)},"%M":function(n){return g(n.wf,2)},"%n":function(){return"\n"},"%p":function(n){return 0<=n.jd&&12>n.jd?"AM":"PM"},"%S":function(n){return g(n.xf,2)},"%t":function(){return"\t"},"%u":function(n){return n.kd||7},"%U":function(n){var v=new Date(n.Xb+1900,0,1),w=0===v.getDay()?v:Md(v,7-v.getDay());n=new Date(n.Xb+1900,n.Gc,n.Sc);return 0>k(w,n)?g(Math.ceil((31-w.getDate()+(Jd(Id(n.getFullYear())?Kd:Ld,n.getMonth()-1)-31)+n.getDate())/7),2):
0===k(w,v)?"01":"00"},"%V":function(n){var v=new Date(n.Xb+1901,0,4),w=m(new Date(n.Xb+1900,0,4));v=m(v);var O=Md(new Date(n.Xb+1900,0,1),n.ld);return 0>k(O,w)?"53":0>=k(v,O)?"01":g(Math.ceil((w.getFullYear()<n.Xb+1900?n.ld+32-w.getDate():n.ld+1-w.getDate())/7),2)},"%w":function(n){return n.kd},"%W":function(n){var v=new Date(n.Xb,0,1),w=1===v.getDay()?v:Md(v,0===v.getDay()?1:7-v.getDay()+1);n=new Date(n.Xb+1900,n.Gc,n.Sc);return 0>k(w,n)?g(Math.ceil((31-w.getDate()+(Jd(Id(n.getFullYear())?Kd:Ld,
n.getMonth()-1)-31)+n.getDate())/7),2):0===k(w,v)?"01":"00"},"%y":function(n){return(n.Xb+1900).toString().substring(2)},"%Y":function(n){return n.Xb+1900},"%z":function(n){n=n.vf;var v=0<=n;n=Math.abs(n)/60;return(v?"+":"-")+String("0000"+(n/60*100+n%60)).slice(-4)},"%Z":function(n){return n.yf},"%%":function(){return"%"}};for(r in q)c.includes(r)&&(c=c.replace(new RegExp(r,"g"),q[r](d)));r=Xb(c,!1);if(r.length>b)return 0;A.set(r,a);return r.length-1},p:function(a){var b=Date.now()/1E3|0;a&&(I[a>>
2]=b);return b}};
(function(){function a(f,g){e.asm=f.exports;K=e.asm.bb;Ua.unshift(e.asm._a);T.Jd.push(e.asm.hb);ya=g;u||fb()}function b(f){a(f.instance,f.module)}function c(f){return ib().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){h("failed to asynchronously prepare wasm: "+g);z(g)})}var d={a:he};u||eb();if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return h("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return wa||"function"!==typeof WebAssembly.instantiateStreaming||
gb()||N.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(N,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){h("wasm streaming compile failed: "+g);h("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm._a).apply(null,arguments)};
var tb=e._free=function(){return(tb=e._free=e.asm.$a).apply(null,arguments)},E=e._malloc=function(){return(E=e._malloc=e.asm.ab).apply(null,arguments)},Eb=e.___errno_location=function(){return(Eb=e.___errno_location=e.asm.cb).apply(null,arguments)},Lc=e._memalign=function(){return(Lc=e._memalign=e.asm.db).apply(null,arguments)},tc=e._ntohs=function(){return(tc=e._ntohs=e.asm.eb).apply(null,arguments)},jc=e._htons=function(){return(jc=e._htons=e.asm.fb).apply(null,arguments)},Pd=e._main=function(){return(Pd=
e._main=e.asm.gb).apply(null,arguments)};e._emscripten_tls_init=function(){return(e._emscripten_tls_init=e.asm.hb).apply(null,arguments)};var rb=e._pthread_self=function(){return(rb=e._pthread_self=e.asm.ib).apply(null,arguments)};e._emscripten_current_thread_process_queued_calls=function(){return(e._emscripten_current_thread_process_queued_calls=e.asm.jb).apply(null,arguments)};
var qb=e._emscripten_register_main_browser_thread_id=function(){return(qb=e._emscripten_register_main_browser_thread_id=e.asm.kb).apply(null,arguments)},Hd=e._emscripten_main_browser_thread_id=function(){return(Hd=e._emscripten_main_browser_thread_id=e.asm.lb).apply(null,arguments)},jb=e.__emscripten_do_dispatch_to_thread=function(){return(jb=e.__emscripten_do_dispatch_to_thread=e.asm.mb).apply(null,arguments)},ge=e._emscripten_sync_run_in_main_thread_4=function(){return(ge=e._emscripten_sync_run_in_main_thread_4=
e.asm.nb).apply(null,arguments)},vb=e._emscripten_main_thread_process_queued_calls=function(){return(vb=e._emscripten_main_thread_process_queued_calls=e.asm.ob).apply(null,arguments)},cd=e._emscripten_run_in_main_runtime_thread_js=function(){return(cd=e._emscripten_run_in_main_runtime_thread_js=e.asm.pb).apply(null,arguments)},hd=e.__emscripten_call_on_thread=function(){return(hd=e.__emscripten_call_on_thread=e.asm.qb).apply(null,arguments)};
e._emscripten_proxy_main=function(){return(e._emscripten_proxy_main=e.asm.rb).apply(null,arguments)};
var pb=e.__emscripten_thread_init=function(){return(pb=e.__emscripten_thread_init=e.asm.sb).apply(null,arguments)},Dc=e._memset=function(){return(Dc=e._memset=e.asm.tb).apply(null,arguments)},sb=e.___pthread_tsd_run_dtors=function(){return(sb=e.___pthread_tsd_run_dtors=e.asm.ub).apply(null,arguments)},Fd=e._emscripten_get_global_libc=function(){return(Fd=e._emscripten_get_global_libc=e.asm.vb).apply(null,arguments)},Ed=e._htonl=function(){return(Ed=e._htonl=e.asm.wb).apply(null,arguments)},Kb=e.__get_tzname=
function(){return(Kb=e.__get_tzname=e.asm.xb).apply(null,arguments)},Jb=e.__get_daylight=function(){return(Jb=e.__get_daylight=e.asm.yb).apply(null,arguments)},Ib=e.__get_timezone=function(){return(Ib=e.__get_timezone=e.asm.zb).apply(null,arguments)},B=e.stackSave=function(){return(B=e.stackSave=e.asm.Ab).apply(null,arguments)},D=e.stackRestore=function(){return(D=e.stackRestore=e.asm.Bb).apply(null,arguments)},Ca=e.stackAlloc=function(){return(Ca=e.stackAlloc=e.asm.Cb).apply(null,arguments)},yb=
e._emscripten_stack_set_limits=function(){return(yb=e._emscripten_stack_set_limits=e.asm.Db).apply(null,arguments)},Z=e._setThrew=function(){return(Z=e._setThrew=e.asm.Eb).apply(null,arguments)},ie=e.dynCall_vijjjid=function(){return(ie=e.dynCall_vijjjid=e.asm.Fb).apply(null,arguments)},je=e.dynCall_iiiijj=function(){return(je=e.dynCall_iiiijj=e.asm.Gb).apply(null,arguments)},ke=e.dynCall_iij=function(){return(ke=e.dynCall_iij=e.asm.Hb).apply(null,arguments)};e._ff_h264_cabac_tables=2558924;
var ub=e.__emscripten_allow_main_runtime_queued_calls=5410016,mb=e.__emscripten_main_thread_futex=16979940;function Sd(a,b,c){var d=B();try{return K.get(a)(b,c)}catch(f){D(d);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function Zd(a,b){var c=B();try{K.get(a)(b)}catch(d){D(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}function be(a,b,c,d,f){var g=B();try{K.get(a)(b,c,d,f)}catch(k){D(g);if(k!==k+0&&"longjmp"!==k)throw k;Z(1,0)}}
function $d(a,b,c){var d=B();try{K.get(a)(b,c)}catch(f){D(d);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function Rd(a,b){var c=B();try{return K.get(a)(b)}catch(d){D(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}function Ud(a,b,c,d,f){var g=B();try{return K.get(a)(b,c,d,f)}catch(k){D(g);if(k!==k+0&&"longjmp"!==k)throw k;Z(1,0)}}function Wd(a,b,c,d,f,g,k,m,p){var q=B();try{return K.get(a)(b,c,d,f,g,k,m,p)}catch(r){D(q);if(r!==r+0&&"longjmp"!==r)throw r;Z(1,0)}}
function ae(a,b,c,d){var f=B();try{K.get(a)(b,c,d)}catch(g){D(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}function Qd(a){var b=B();try{return K.get(a)()}catch(c){D(b);if(c!==c+0&&"longjmp"!==c)throw c;Z(1,0)}}function ce(a,b,c,d,f,g){var k=B();try{K.get(a)(b,c,d,f,g)}catch(m){D(k);if(m!==m+0&&"longjmp"!==m)throw m;Z(1,0)}}function Td(a,b,c,d){var f=B();try{return K.get(a)(b,c,d)}catch(g){D(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}
function Vd(a,b,c,d,f,g){var k=B();try{return K.get(a)(b,c,d,f,g)}catch(m){D(k);if(m!==m+0&&"longjmp"!==m)throw m;Z(1,0)}}function ee(a,b,c,d,f,g,k,m,p){var q=B();try{K.get(a)(b,c,d,f,g,k,m,p)}catch(r){D(q);if(r!==r+0&&"longjmp"!==r)throw r;Z(1,0)}}function de(a,b,c,d,f,g,k){var m=B();try{K.get(a)(b,c,d,f,g,k)}catch(p){D(m);if(p!==p+0&&"longjmp"!==p)throw p;Z(1,0)}}function fe(a,b,c,d,f,g,k,m,p,q){var r=B();try{ie(a,b,c,d,f,g,k,m,p,q)}catch(y){D(r);if(y!==y+0&&"longjmp"!==y)throw y;Z(1,0)}}
function Xd(a,b,c,d,f,g,k,m){var p=B();try{return je(a,b,c,d,f,g,k,m)}catch(q){D(p);if(q!==q+0&&"longjmp"!==q)throw q;Z(1,0)}}function Yd(a,b,c,d){var f=B();try{return ke(a,b,c,d)}catch(g){D(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}e.ccall=Ba;e.cwrap=function(a,b,c,d){c=c||[];var f=c.every(function(g){return"number"===g});return"string"!==b&&f&&!d?Aa(a):function(){return Ba(a,b,c,arguments,d)}};
e.setValue=function(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":A[a>>0]=b;break;case "i8":A[a>>0]=b;break;case "i16":H[a>>1]=b;break;case "i32":I[a>>2]=b;break;case "i64":Q=[b>>>0,(P=b,1<=+Math.abs(P)?0<P?(Math.min(+Math.floor(P/4294967296),4294967295)|0)>>>0:~~+Math.ceil((P-+(~~P>>>0))/4294967296)>>>0:0)];I[a>>2]=Q[0];I[a+4>>2]=Q[1];break;case "float":Pa[a>>2]=b;break;case "double":Qa[a>>3]=b;break;default:z("invalid type for setValue: "+c)}};e.stringToUTF8=Da;
e.lengthBytesUTF8=Ja;e.writeAsciiToMemory=Ma;e.callMain=le;e.FS=L;e.PThread=T;e.PThread=T;e.wasmMemory=xa;e.ExitStatus=ca;var me;function ca(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}db=function ne(){me||oe();me||(db=ne)};function le(a){var b=e._emscripten_proxy_main;a=a||[];var c=a.length+1,d=Ca(4*(c+1));I[d>>2]=La(ja);for(var f=1;f<c;f++)I[(d>>2)+f]=La(a[f-1]);I[(d>>2)+c]=0;b(c,d)}
function oe(a){function b(){if(!me&&(me=!0,e.calledRun=!0,!za)){Xa();u||$a(Va);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();pe&&le(a);if(!u){if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();Wa.unshift(c)}$a(Wa)}}}a=a||ia;if(!(0<bb))if(u)aa(e),Xa(),postMessage({cmd:"loaded"});else{if(!u){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)ab();$a(Ta)}0<bb||(e.setStatus?(e.setStatus("Running..."),
setTimeout(function(){setTimeout(function(){e.setStatus("")},1);b()},1)):b())}}e.run=oe;function da(a,b){if(!b||!Bb()||0!==a){if(!b&&u)throw postMessage({cmd:"exitProcess",returnCode:a}),new ca(a);if(!Bb()){T.rf();if(e.onExit)e.onExit(a);za=!0}ka(a,new ca(a))}}if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var pe=!1;e.noInitialRun&&(pe=!1);u&&(noExitRuntime=!1,T.Re());oe();


  return createFFmpegCore.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = createFFmpegCore;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return createFFmpegCore; });
else if (typeof exports === 'object')
  exports["createFFmpegCore"] = createFFmpegCore;
