
var createFFmpegCore = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(createFFmpegCore) {
  createFFmpegCore = createFFmpegCore || {};


var e;e||(e=typeof createFFmpegCore !== 'undefined' ? createFFmpegCore : {});var aa,ba;e.ready=new Promise(function(a,b){aa=a;ba=b});e.quit=function(a){if(e.onExit)e.onExit(a);throw new ca(a);};e.exit=da;ea=h=function(){};var fa={},ha;for(ha in e)e.hasOwnProperty(ha)&&(fa[ha]=e[ha]);var ia=[],ja="./this.program";function ka(a,b){throw b;}var la=!1,l=!1,t=!1,ma=!1;la="object"===typeof window;l="function"===typeof importScripts;
t="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ma=!la&&!t&&!l;var u=e.ENVIRONMENT_IS_PTHREAD||!1,x="";function na(a){return e.locateFile?e.locateFile(a,x):x+a}var oa,pa,qa,ra,sa;
if(t){x=l?require("path").dirname(x)+"/":__dirname+"/";oa=function(a,b){ra||(ra=require("fs"));sa||(sa=require("path"));a=sa.normalize(a);return ra.readFileSync(a,b?null:"utf8")};qa=function(a){a=oa(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ja=process.argv[1].replace(/\\/g,"/"));ia=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ca))throw a;});process.on("unhandledRejection",z);ka=function(a){process.exit(a)};e.inspect=
function(){return"[Emscripten Module object]"};var ta;try{ta=require("worker_threads")}catch(a){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),a;}global.Worker=ta.Worker}else if(ma)"undefined"!=typeof read&&(oa=function(a){return read(a)}),qa=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ia=scriptArgs:
"undefined"!=typeof arguments&&(ia=arguments),"function"===typeof quit&&(ka=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(la||l)l?x=self.location.href:"undefined"!==typeof document&&document.currentScript&&(x=document.currentScript.src),_scriptDir&&(x=_scriptDir),0!==x.indexOf("blob:")?x=x.substr(0,x.lastIndexOf("/")+1):x="",t?(oa=function(a,b){ra||(ra=
require("fs"));sa||(sa=require("path"));a=sa.normalize(a);return ra.readFileSync(a,b?null:"utf8")},qa=function(a){a=oa(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a}):(oa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(qa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),pa=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";
d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)});t&&"undefined"===typeof performance&&(global.performance=require("perf_hooks").performance);var ea=e.print||console.log.bind(console),h=e.printErr||console.warn.bind(console);for(ha in fa)fa.hasOwnProperty(ha)&&(e[ha]=fa[ha]);fa=null;e.arguments&&(ia=e.arguments);e.thisProgram&&(ja=e.thisProgram);e.quit&&(ka=e.quit);var ua,va=0,wa;e.wasmBinary&&(wa=e.wasmBinary);
var noExitRuntime=e.noExitRuntime||!1;"object"!==typeof WebAssembly&&z("no native wasm support detected");var xa,ya,za=!1;function assert(a,b){a||z("Assertion failed: "+b)}function Aa(a){var b=e["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function Ba(a,b,c,d){var f={string:function(q){var r=0;if(null!==q&&void 0!==q&&0!==q){var y=(q.length<<2)+1;r=Ca(y);Da(q,A,r,y)}return r},array:function(q){var r=Ca(q.length);B.set(q,r);return r}},g=Aa(a),k=[];a=0;if(d)for(var m=0;m<d.length;m++){var p=f[c[m]];p?(0===a&&(a=C()),k[m]=p(d[m])):k[m]=d[m]}c=g.apply(null,k);c=function(q){return"string"===b?D(q):"boolean"===b?!!q:q}(c);0!==a&&E(a);return c}
function Ea(a){var b=new TextDecoder(a);this.decode=function(c){c.buffer instanceof SharedArrayBuffer&&(c=new Uint8Array(c));return b.decode.call(b,c)}}var Fa="undefined"!==typeof TextDecoder?new Ea("utf8"):void 0;
function Ga(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Fa)return Fa.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function D(a){return a?Ga(A,a,void 0):""}
function Da(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var m=a.charCodeAt(++g);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}
function Ha(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new Ea("utf-16le");function Ia(a){var b=Ha(a)+1,c=H(b);c&&Da(a,B,c,b);return c}function Ja(a){var b=Ha(a)+1,c=Ca(b);Da(a,B,c,b);return c}function Ka(a,b,c){for(var d=0;d<a.length;++d)B[b++>>0]=a.charCodeAt(d);c||(B[b>>0]=0)}var La,B,A,I,Ma,J,K,Na,Oa;u&&(La=e.buffer);
var Pa=e.INITIAL_MEMORY||2146435072;
if(u)xa=e.wasmMemory,La=e.buffer;else if(e.wasmMemory)xa=e.wasmMemory;else if(xa=new WebAssembly.Memory({initial:Pa/65536,maximum:Pa/65536,shared:!0}),!(xa.buffer instanceof SharedArrayBuffer))throw h("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),t&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),Error("bad memory");
xa&&(La=xa.buffer);Pa=La.byteLength;var Qa=La;La=Qa;e.HEAP8=B=new Int8Array(Qa);e.HEAP16=I=new Int16Array(Qa);e.HEAP32=J=new Int32Array(Qa);e.HEAPU8=A=new Uint8Array(Qa);e.HEAPU16=Ma=new Uint16Array(Qa);e.HEAPU32=K=new Uint32Array(Qa);e.HEAPF32=Na=new Float32Array(Qa);e.HEAPF64=Oa=new Float64Array(Qa);var L,Ra=[],Sa=[],Ta=[],Ua=[],Va=[];function Wa(){u||(e.noFSInit||M.Nc.Ad||M.Nc(),M.ie=!1,N.root=M.Qb(N,{},null),Xa(Sa))}function $a(){var a=e.preRun.shift();Ra.unshift(a)}var ab=0,bb=null,cb=null;
function db(){assert(!u,"addRunDependency cannot be used in a pthread worker");ab++;e.monitorRunDependencies&&e.monitorRunDependencies(ab)}function eb(){ab--;e.monitorRunDependencies&&e.monitorRunDependencies(ab);if(0==ab&&(null!==bb&&(clearInterval(bb),bb=null),cb)){var a=cb;cb=null;a()}}e.preloadedImages={};e.preloadedAudios={};
function z(a){if(e.onAbort)e.onAbort(a);u&&console.error("Pthread aborting at "+Error().stack);h(a);za=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function fb(){return P.startsWith("data:application/octet-stream;base64,")}var P;P="ffmpeg-core.wasm";fb()||(P=na(P));function gb(){var a=P;try{if(a==P&&wa)return new Uint8Array(wa);if(qa)return qa(a);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function hb(){if(!wa&&(la||l)){if("function"===typeof fetch&&!P.startsWith("file://"))return fetch(P,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+P+"'";return a.arrayBuffer()}).catch(function(){return gb()});if(pa)return new Promise(function(a,b){pa(P,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return gb()})}
var Q,T,jb={5410468:function(){throw"Canceled!";},5410486:function(a,b){setTimeout(function(){ib(a,b)},0)}};function Xa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.Oe;"number"===typeof c?void 0===b.Ac?L.get(c)():L.get(c)(b.Ac):c(void 0===b.Ac?null:b.Ac)}}}
function kb(a,b){if(0>=a||a>B.length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(J,lb>>2),d=0;if(c==a&&Atomics.compareExchange(J,lb>>2,c,0)==c&&(--b,d=1,0>=b))return 1;a=Atomics.notify(J,a>>2,b);if(0<=a)return a+d;throw"Atomics.notify returned an unexpected value "+a;}e._emscripten_futex_wake=kb;
function mb(a){if(u)throw"Internal Error! cancelThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cancelThread!";U.lc[a].worker.postMessage({cmd:"cancel"})}function nb(a){if(u)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cleanupThread!";var b=U.lc[a];b&&(J[a+12>>2]=0,U.gd(b.worker))}
var U={rc:[],qc:[],Ld:[],Tf:function(){},Ue:function(){for(var a=H(228),b=0;57>b;++b)K[a/4+b]=0;J[a+12>>2]=a;b=a+152;J[b>>2]=b;var c=H(512);for(b=0;128>b;++b)K[c/4+b]=0;Atomics.store(K,a+100>>2,c);Atomics.store(K,a+40>>2,a);ob(a,!l,1);pb(a)},Ve:function(){U.receiveObjectTransfer=U.mf;U.threadInit=U.xf;U.threadCancel=U.vf;U.threadExit=U.wf;U.setExitStatus=U.rf},lc:{},kd:[],oe:function(){for(;0<U.kd.length;)U.kd.pop()();u&&qb()&&rb()},pe:function(a,b){Atomics.store(K,a+56>>2,1);Atomics.store(K,a+60>>
2,0);U.oe();Atomics.store(K,a+4>>2,b);Atomics.store(K,a+0>>2,1);kb(a+0,2147483647);ob(0,0,0)},rf:function(){},wf:function(a){var b=qb();b&&(U.pe(b,a),u&&postMessage({cmd:"exit"}))},vf:function(){U.pe(qb(),-1);postMessage({cmd:"cancelDone"})},uf:function(){for(var a in U.lc){var b=U.lc[a];b&&b.worker&&U.gd(b.worker)}U.lc={};for(a=0;a<U.rc.length;++a){var c=U.rc[a];c.terminate()}U.rc=[];for(a=0;a<U.qc.length;++a)c=U.qc[a],b=c.ec,U.wd(b),c.terminate();U.qc=[]},wd:function(a){if(a){if(a.mc){var b=J[a.mc+
100>>2];J[a.mc+100>>2]=0;sb(b);sb(a.mc)}a.mc=0;a.sd&&a.yc&&sb(a.yc);a.yc=0;a.worker&&(a.worker.ec=null)}},gd:function(a){U.pf(function(){delete U.lc[a.ec.mc];U.rc.push(a);U.qc.splice(U.qc.indexOf(a),1);U.wd(a.ec);a.ec=void 0})},pf:function(a){J[tb>>2]=0;try{a()}finally{J[tb>>2]=1}},mf:function(){},xf:function(){for(var a in U.Ld)U.Ld[a]()},Ze:function(a,b){a.onmessage=function(c){var d=c.data,f=d.cmd;a.ec&&(U.Ke=a.ec.mc);if(d.targetThread&&d.targetThread!=qb()){var g=U.lc[d.cg];g?g.worker.postMessage(c.data,
d.transferList):console.error('Internal error! Worker sent a message "'+f+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===f)ub();else if("spawnThread"===f)wb(c.data);else if("cleanupThread"===f)nb(d.thread);else if("killThread"===f){c=d.thread;if(u)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";J[c+12>>2]=0;c=U.lc[c];c.worker.terminate();
U.wd(c);U.qc.splice(U.qc.indexOf(c.worker),1);c.worker.ec=void 0}else if("cancelThread"===f)mb(d.thread);else if("loaded"===f)a.loaded=!0,b&&b(a),a.Tc&&(a.Tc(),delete a.Tc);else if("print"===f)ea("Thread "+d.threadId+": "+d.text);else if("printErr"===f)h("Thread "+d.threadId+": "+d.text);else if("alert"===f)alert("Thread "+d.threadId+": "+d.text);else if("exit"===f)a.ec&&Atomics.load(K,a.ec.mc+64>>2)&&U.gd(a);else if("exitProcess"===f)try{da(d.returnCode)}catch(k){if(k instanceof ca)return;throw k;
}else"cancelDone"===f?U.gd(a):"objectTransfer"!==f&&("setimmediate"===c.data.target?a.postMessage(c.data):h("worker sent an unknown command "+f));U.Ke=void 0};a.onerror=function(c){h("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message)};t&&(a.on("message",function(c){a.onmessage({data:c})}),a.on("error",function(c){a.onerror(c)}),a.on("exit",function(){}));a.postMessage({cmd:"load",urlOrBlob:e.mainScriptUrlOrBlob||_scriptDir,wasmMemory:xa,wasmModule:ya})},Ae:function(){var a=na("ffmpeg-core.worker.js");
U.rc.push(new Worker(a))},Qe:function(){0==U.rc.length&&(U.Ae(),U.Ze(U.rc[0]));return U.rc.pop()},Hf:function(a){for(a=performance.now()+a;performance.now()<a;);}};e.establishStackSpace=function(a,b){xb(a,b);E(a)};e.invokeEntryPoint=function(a,b){return L.get(a)(b)};var zb=0;function Ab(){return noExitRuntime||0<zb}e.keepRuntimeAlive=Ab;var Bb;
t?Bb=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:u?Bb=function(){return performance.now()-e.__performance_now_clock_drift}:"undefined"!==typeof dateNow?Bb=dateNow:Bb=function(){return performance.now()};function Cb(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Bb();else return J[Db()>>2]=28,-1;J[b>>2]=a/1E3|0;J[b+4>>2]=a%1E3*1E6|0;return 0}function Eb(a,b){if(u)return V(1,1,a,b);Ua.unshift({Oe:a,Ac:b})}function Fb(a,b){U.kd.push(function(){L.get(a)(b)})}
function Gb(a,b){a=new Date(1E3*J[a>>2]);J[b>>2]=a.getUTCSeconds();J[b+4>>2]=a.getUTCMinutes();J[b+8>>2]=a.getUTCHours();J[b+12>>2]=a.getUTCDate();J[b+16>>2]=a.getUTCMonth();J[b+20>>2]=a.getUTCFullYear()-1900;J[b+24>>2]=a.getUTCDay();J[b+36>>2]=0;J[b+32>>2]=0;J[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;Gb.Od||(Gb.Od=Ia("GMT"));J[b+40>>2]=Gb.Od;return b}
function Hb(){function a(k){return(k=k.toTimeString().match(/\(([A-Za-z ]+)\)$/))?k[1]:"GMT"}if(u)return V(2,1);if(!Hb.Be){Hb.Be=!0;var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var f=d.getTimezoneOffset(),g=Math.max(b,f);J[Ib()>>2]=60*g;J[Jb()>>2]=Number(b!=f);c=a(c);d=a(d);c=Ia(c);d=Ia(d);f<b?(J[Kb()>>2]=c,J[Kb()+4>>2]=d):(J[Kb()>>2]=d,J[Kb()+4>>2]=c)}}
function Lb(a,b){Hb();a=new Date(1E3*J[a>>2]);J[b>>2]=a.getSeconds();J[b+4>>2]=a.getMinutes();J[b+8>>2]=a.getHours();J[b+12>>2]=a.getDate();J[b+16>>2]=a.getMonth();J[b+20>>2]=a.getFullYear()-1900;J[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);J[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;J[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;J[b+32>>2]=a;a=J[Kb()+(a?4:0)>>2];
J[b+40>>2]=a;return b}function Mb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Nb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Mb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Ob(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Pb(a){if("/"===a)return"/";a=Nb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function Qb(a,b){return Nb(a+"/"+b)}
function Rb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(t)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){z("randomDevice")}}
function Sb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:M.cwd();if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Mb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}
function Tb(a,b){function c(k){for(var m=0;m<k.length&&""===k[m];m++);for(var p=k.length-1;0<=p&&""===k[p];p--);return m>p?[]:k.slice(m,p-m+1)}a=Sb(a).substr(1);b=Sb(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),f=d,g=0;g<d;g++)if(a[g]!==b[g]){f=g;break}d=[];for(g=f;g<a.length;g++)d.push("..");d=d.concat(b.slice(f));return d.join("/")}var Ub=[];function Vb(a,b){Ub[a]={input:[],output:[],Ec:b};M.Kd(a,Wb)}
var Wb={open:function(a){var b=Ub[a.node.rdev];if(!b)throw new M.Kb(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Ec.flush(a.tty)},flush:function(a){a.tty.Ec.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Ec.ee)throw new M.Kb(60);for(var f=0,g=0;g<d;g++){try{var k=a.tty.Ec.ee(a.tty)}catch(m){throw new M.Kb(29);}if(void 0===k&&0===f)throw new M.Kb(6);if(null===k||void 0===k)break;f++;b[c+g]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.Ec.Gd)throw new M.Kb(60);
try{for(var f=0;f<d;f++)a.tty.Ec.Gd(a.tty,b[c+f])}catch(g){throw new M.Kb(29);}d&&(a.node.timestamp=Date.now());return f}},Yb={ee:function(a){if(!a.input.length){var b=null;if(t){var c=Buffer.zc?Buffer.zc(256):new Buffer(256),d=0;try{d=ra.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(f.toString().includes("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Xb(b,!0)}return a.input.shift()},Gd:function(a,b){null===b||10===b?(ea(Ga(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ea(Ga(a.output,0)),a.output=[])}},Zb={Gd:function(a,b){null===b||10===b?(h(Ga(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(h(Ga(a.output,0)),a.output=[])}},W={kc:null,Qb:function(){return W.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(M.We(c)||M.isFIFO(c))throw new M.Kb(63);W.kc||(W.kc={dir:{node:{dc:W.Lb.dc,Vb:W.Lb.Vb,lookup:W.Lb.lookup,ic:W.Lb.ic,rename:W.Lb.rename,unlink:W.Lb.unlink,rmdir:W.Lb.rmdir,readdir:W.Lb.readdir,symlink:W.Lb.symlink},stream:{Yb:W.Mb.Yb}},file:{node:{dc:W.Lb.dc,Vb:W.Lb.Vb},stream:{Yb:W.Mb.Yb,read:W.Mb.read,write:W.Mb.write,Mc:W.Mb.Mc,Cc:W.Mb.Cc,Dc:W.Mb.Dc}},link:{node:{dc:W.Lb.dc,Vb:W.Lb.Vb,readlink:W.Lb.readlink},stream:{}},Sd:{node:{dc:W.Lb.dc,Vb:W.Lb.Vb},
stream:M.De}});c=M.createNode(a,b,c,d);M.Tb(c.mode)?(c.Lb=W.kc.dir.node,c.Mb=W.kc.dir.stream,c.Nb={}):M.isFile(c.mode)?(c.Lb=W.kc.file.node,c.Mb=W.kc.file.stream,c.Rb=0,c.Nb=null):M.tc(c.mode)?(c.Lb=W.kc.link.node,c.Mb=W.kc.link.stream):M.Oc(c.mode)&&(c.Lb=W.kc.Sd.node,c.Mb=W.kc.Sd.stream);c.timestamp=Date.now();a&&(a.Nb[b]=c,a.timestamp=c.timestamp);return c},Qf:function(a){return a.Nb?a.Nb.subarray?a.Nb.subarray(0,a.Rb):new Uint8Array(a.Nb):new Uint8Array(0)},Zd:function(a,b){var c=a.Nb?a.Nb.length:
0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Nb,a.Nb=new Uint8Array(b),0<a.Rb&&a.Nb.set(c.subarray(0,a.Rb),0))},nf:function(a,b){if(a.Rb!=b)if(0==b)a.Nb=null,a.Rb=0;else{var c=a.Nb;a.Nb=new Uint8Array(b);c&&a.Nb.set(c.subarray(0,Math.min(b,a.Rb)));a.Rb=b}},Lb:{dc:function(a){var b={};b.dev=M.Oc(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;M.Tb(a.mode)?b.size=4096:M.isFile(a.mode)?b.size=a.Rb:M.tc(a.mode)?b.size=a.link.length:b.size=
0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Qd=4096;b.blocks=Math.ceil(b.size/b.Qd);return b},Vb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&W.nf(a,b.size)},lookup:function(){throw M.xd[44];},ic:function(a,b,c,d){return W.createNode(a,b,c,d)},rename:function(a,b,c){if(M.Tb(a.mode)){try{var d=M.hc(b,c)}catch(g){}if(d)for(var f in d.Nb)throw new M.Kb(55);}delete a.parent.Nb[a.name];
a.parent.timestamp=Date.now();a.name=c;b.Nb[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.Nb[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=M.hc(a,b),d;for(d in c.Nb)throw new M.Kb(55);delete a.Nb[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.Nb)a.Nb.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=W.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(!M.tc(a.mode))throw new M.Kb(28);return a.link}},
Mb:{read:function(a,b,c,d,f){var g=a.node.Nb;if(f>=a.node.Rb)return 0;a=Math.min(a.node.Rb-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Nb||a.Nb.subarray)){if(g)return a.Nb=b.subarray(c,c+d),a.Rb=d;if(0===a.Rb&&0===f)return a.Nb=b.slice(c,c+d),a.Rb=d;if(f+d<=a.Rb)return a.Nb.set(b.subarray(c,c+d),f),d}W.Zd(a,f+d);if(a.Nb.subarray&&b.subarray)a.Nb.set(b.subarray(c,
c+d),f);else for(g=0;g<d;g++)a.Nb[f+g]=b[c+g];a.Rb=Math.max(a.Rb,f+d);return d},Yb:function(a,b,c){1===c?b+=a.position:2===c&&M.isFile(a.node.mode)&&(b+=a.node.Rb);if(0>b)throw new M.Kb(28);return b},Mc:function(a,b,c){W.Zd(a.node,b+c);a.node.Rb=Math.max(a.node.Rb,b+c)},Cc:function(a,b,c,d,f,g){if(0!==b)throw new M.Kb(28);if(!M.isFile(a.node.mode))throw new M.Kb(43);a=a.node.Nb;if(g&2||a.buffer!==La){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;g=
65536*Math.ceil(c/65536);for(b=H(g);c<g;)B[b+c++]=0;c=b;if(!c)throw new M.Kb(48);B.set(a,c)}else d=!1,c=a.byteOffset;return{lf:c,rd:d}},Dc:function(a,b,c,d,f){if(!M.isFile(a.node.mode))throw new M.Kb(43);if(f&2)return 0;W.Mb.write(a,b,0,d,c,!1);return 0}}},X={od:16895,Lc:33279,Id:null,Qb:function(a){function b(g){g=g.split("/");for(var k=d,m=0;m<g.length-1;m++){var p=g.slice(0,m+1).join("/");f[p]||(f[p]=X.createNode(k,g[m],X.od,0));k=f[p]}return k}function c(g){g=g.split("/");return g[g.length-1]}
assert(l);X.Id||(X.Id=new FileReaderSync);var d=X.createNode(null,"/",X.od,0),f={};Array.prototype.forEach.call(a.Fd.files||[],function(g){X.createNode(b(g.name),c(g.name),X.Lc,0,g,g.lastModifiedDate)});(a.Fd.blobs||[]).forEach(function(g){X.createNode(b(g.name),c(g.name),X.Lc,0,g.data)});(a.Fd.packages||[]).forEach(function(g){g.metadata.files.forEach(function(k){var m=k.filename.substr(1);X.createNode(b(m),c(m),X.Lc,0,g.blob.slice(k.start,k.end))})});return d},createNode:function(a,b,c,d,f,g){d=
M.createNode(a,b,c);d.mode=c;d.Lb=X.Lb;d.Mb=X.Mb;d.timestamp=(g||new Date).getTime();assert(X.Lc!==X.od);c===X.Lc?(d.size=f.size,d.Nb=f):(d.size=4096,d.Nb={});a&&(a.Nb[b]=d);return d},Lb:{dc:function(a){return{dev:1,ino:a.id,mode:a.mode,nlink:1,uid:0,gid:0,rdev:void 0,size:a.size,atime:new Date(a.timestamp),mtime:new Date(a.timestamp),ctime:new Date(a.timestamp),Qd:4096,blocks:Math.ceil(a.size/4096)}},Vb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp)},
lookup:function(){throw new M.Kb(44);},ic:function(){throw new M.Kb(63);},rename:function(){throw new M.Kb(63);},unlink:function(){throw new M.Kb(63);},rmdir:function(){throw new M.Kb(63);},readdir:function(a){var b=[".",".."],c;for(c in a.Nb)a.Nb.hasOwnProperty(c)&&b.push(c);return b},symlink:function(){throw new M.Kb(63);},readlink:function(){throw new M.Kb(63);}},Mb:{read:function(a,b,c,d,f){if(f>=a.node.size)return 0;a=a.node.Nb.slice(f,f+d);d=X.Id.readAsArrayBuffer(a);b.set(new Uint8Array(d),
c);return a.size},write:function(){throw new M.Kb(29);},Yb:function(a,b,c){1===c?b+=a.position:2===c&&M.isFile(a.node.mode)&&(b+=a.node.size);if(0>b)throw new M.Kb(28);return b}}},M={root:null,Rc:[],Wd:{},streams:[],ef:1,jc:null,Vd:"/",Ad:!1,ie:!0,Wb:{},se:{le:{we:1,xe:2}},Kb:null,xd:{},$d:null,jd:0,Pb:function(a,b){a=Sb(M.cwd(),a);b=b||{};if(!a)return{path:"",node:null};var c={vd:!0,Jd:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Jd)throw new M.Kb(32);a=Mb(a.split("/").filter(function(k){return!!k}),
!1);var f=M.root;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=M.hc(f,a[d]);c=Qb(c,a[d]);M.uc(f)&&(!g||g&&b.vd)&&(f=f.Qc.root);if(!g||b.cc)for(g=0;M.tc(f.mode);)if(f=M.readlink(c),c=Sb(Ob(c),f),f=M.Pb(c,{Jd:b.Jd}).node,40<g++)throw new M.Kb(32);}return{path:c,node:f}},oc:function(a){for(var b;;){if(M.ad(a))return a=a.Qb.je,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},zd:function(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|
0;return(a+c>>>0)%M.jc.length},ge:function(a){var b=M.zd(a.parent.id,a.name);a.wc=M.jc[b];M.jc[b]=a},he:function(a){var b=M.zd(a.parent.id,a.name);if(M.jc[b]===a)M.jc[b]=a.wc;else for(b=M.jc[b];b;){if(b.wc===a){b.wc=a.wc;break}b=b.wc}},hc:function(a,b){var c=M.bf(a);if(c)throw new M.Kb(c,a);for(c=M.jc[M.zd(a.id,b)];c;c=c.wc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return M.lookup(a,b)},createNode:function(a,b,c,d){a=new M.te(a,b,c,d);M.ge(a);return a},ud:function(a){M.he(a)},ad:function(a){return a===
a.parent},uc:function(a){return!!a.Qc},isFile:function(a){return 32768===(a&61440)},Tb:function(a){return 16384===(a&61440)},tc:function(a){return 40960===(a&61440)},Oc:function(a){return 8192===(a&61440)},We:function(a){return 24576===(a&61440)},isFIFO:function(a){return 4096===(a&61440)},isSocket:function(a){return 49152===(a&49152)},Ne:{r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},df:function(a){var b=M.Ne[a];if("undefined"===typeof b)throw Error("Unknown file open mode: "+a);return b},ae:function(a){var b=
["r","w","rw"][a&3];a&512&&(b+="w");return b},pc:function(a,b){if(M.ie)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},bf:function(a){var b=M.pc(a,"x");return b?b:a.Lb.lookup?0:2},Ed:function(a,b){try{return M.hc(a,b),20}catch(c){}return M.pc(a,"wx")},bd:function(a,b,c){try{var d=M.hc(a,b)}catch(f){return f.Ob}if(a=M.pc(a,"wx"))return a;if(c){if(!M.Tb(d.mode))return 54;if(M.ad(d)||M.oc(d)===M.cwd())return 10}else if(M.Tb(d.mode))return 31;
return 0},cf:function(a,b){return a?M.tc(a.mode)?32:M.Tb(a.mode)&&("r"!==M.ae(b)||b&512)?31:M.pc(a,M.ae(b)):44},ve:4096,ff:function(a,b){b=b||M.ve;for(a=a||0;a<=b;a++)if(!M.streams[a])return a;throw new M.Kb(33);},fc:function(a){return M.streams[a]},Ud:function(a,b,c){M.pd||(M.pd=function(){},M.pd.prototype={object:{get:function(){return this.node},set:function(g){this.node=g}}});var d=new M.pd,f;for(f in a)d[f]=a[f];a=d;b=M.ff(b,c);a.fd=b;return M.streams[b]=a},Ee:function(a){M.streams[a]=null},
De:{open:function(a){a.Mb=M.Pe(a.node.rdev).Mb;a.Mb.open&&a.Mb.open(a)},Yb:function(){throw new M.Kb(70);}},Dd:function(a){return a>>8},Vf:function(a){return a&255},vc:function(a,b){return a<<8|b},Kd:function(a,b){M.Wd[a]={Mb:b}},Pe:function(a){return M.Wd[a]},de:function(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.Rc)}return b},re:function(a,b){function c(k){M.jd--;return b(k)}function d(k){if(k){if(!d.Le)return d.Le=!0,c(k)}else++g>=f.length&&c(null)}"function"===typeof a&&
(b=a,a=!1);M.jd++;1<M.jd&&h("warning: "+M.jd+" FS.syncfs operations in flight at once, probably just doing extra work");var f=M.de(M.root.Qb),g=0;f.forEach(function(k){if(!k.type.re)return d(null);k.type.re(k,a,d)})},Qb:function(a,b,c){var d="/"===c,f=!c;if(d&&M.root)throw new M.Kb(10);if(!d&&!f){var g=M.Pb(c,{vd:!1});c=g.path;g=g.node;if(M.uc(g))throw new M.Kb(10);if(!M.Tb(g.mode))throw new M.Kb(54);}b={type:a,Fd:b,je:c,Rc:[]};a=a.Qb(b);a.Qb=b;b.root=a;d?M.root=a:g&&(g.Qc=b,g.Qb&&g.Qb.Rc.push(b));
return a},Ef:function(a){a=M.Pb(a,{vd:!1});if(!M.uc(a.node))throw new M.Kb(28);a=a.node;var b=a.Qc,c=M.de(b);Object.keys(M.jc).forEach(function(d){for(d=M.jc[d];d;){var f=d.wc;c.includes(d.Qb)&&M.ud(d);d=f}});a.Qc=null;a.Qb.Rc.splice(a.Qb.Rc.indexOf(b),1)},lookup:function(a,b){return a.Lb.lookup(a,b)},ic:function(a,b,c){var d=M.Pb(a,{parent:!0}).node;a=Pb(a);if(!a||"."===a||".."===a)throw new M.Kb(28);var f=M.Ed(d,a);if(f)throw new M.Kb(f);if(!d.Lb.ic)throw new M.Kb(63);return d.Lb.ic(d,a,b,c)},create:function(a,
b){return M.ic(a,(void 0!==b?b:438)&4095|32768,0)},mkdir:function(a,b){return M.ic(a,(void 0!==b?b:511)&1023|16384,0)},Xf:function(a,b){a=a.split("/");for(var c="",d=0;d<a.length;++d)if(a[d]){c+="/"+a[d];try{M.mkdir(c,b)}catch(f){if(20!=f.Ob)throw f;}}},cd:function(a,b,c){"undefined"===typeof c&&(c=b,b=438);return M.ic(a,b|8192,c)},symlink:function(a,b){if(!Sb(a))throw new M.Kb(44);var c=M.Pb(b,{parent:!0}).node;if(!c)throw new M.Kb(44);b=Pb(b);var d=M.Ed(c,b);if(d)throw new M.Kb(d);if(!c.Lb.symlink)throw new M.Kb(63);
return c.Lb.symlink(c,b,a)},rename:function(a,b){var c=Ob(a),d=Ob(b),f=Pb(a),g=Pb(b);var k=M.Pb(a,{parent:!0});var m=k.node;k=M.Pb(b,{parent:!0});k=k.node;if(!m||!k)throw new M.Kb(44);if(m.Qb!==k.Qb)throw new M.Kb(75);var p=M.hc(m,f);d=Tb(a,d);if("."!==d.charAt(0))throw new M.Kb(28);d=Tb(b,c);if("."!==d.charAt(0))throw new M.Kb(55);try{var q=M.hc(k,g)}catch(r){}if(p!==q){c=M.Tb(p.mode);if(f=M.bd(m,f,c))throw new M.Kb(f);if(f=q?M.bd(k,g,c):M.Ed(k,g))throw new M.Kb(f);if(!m.Lb.rename)throw new M.Kb(63);
if(M.uc(p)||q&&M.uc(q))throw new M.Kb(10);if(k!==m&&(f=M.pc(m,"w")))throw new M.Kb(f);try{M.Wb.willMovePath&&M.Wb.willMovePath(a,b)}catch(r){h("FS.trackingDelegate['willMovePath']('"+a+"', '"+b+"') threw an exception: "+r.message)}M.he(p);try{m.Lb.rename(p,k,g)}catch(r){throw r;}finally{M.ge(p)}try{if(M.Wb.onMovePath)M.Wb.onMovePath(a,b)}catch(r){h("FS.trackingDelegate['onMovePath']('"+a+"', '"+b+"') threw an exception: "+r.message)}}},rmdir:function(a){var b=M.Pb(a,{parent:!0}).node,c=Pb(a),d=M.hc(b,
c),f=M.bd(b,c,!0);if(f)throw new M.Kb(f);if(!b.Lb.rmdir)throw new M.Kb(63);if(M.uc(d))throw new M.Kb(10);try{M.Wb.willDeletePath&&M.Wb.willDeletePath(a)}catch(g){h("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.Lb.rmdir(b,c);M.ud(d);try{if(M.Wb.onDeletePath)M.Wb.onDeletePath(a)}catch(g){h("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}},readdir:function(a){a=M.Pb(a,{cc:!0}).node;if(!a.Lb.readdir)throw new M.Kb(54);return a.Lb.readdir(a)},
unlink:function(a){var b=M.Pb(a,{parent:!0}).node,c=Pb(a),d=M.hc(b,c),f=M.bd(b,c,!1);if(f)throw new M.Kb(f);if(!b.Lb.unlink)throw new M.Kb(63);if(M.uc(d))throw new M.Kb(10);try{M.Wb.willDeletePath&&M.Wb.willDeletePath(a)}catch(g){h("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.Lb.unlink(b,c);M.ud(d);try{if(M.Wb.onDeletePath)M.Wb.onDeletePath(a)}catch(g){h("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}},readlink:function(a){a=M.Pb(a).node;
if(!a)throw new M.Kb(44);if(!a.Lb.readlink)throw new M.Kb(28);return Sb(M.oc(a.parent),a.Lb.readlink(a))},stat:function(a,b){a=M.Pb(a,{cc:!b}).node;if(!a)throw new M.Kb(44);if(!a.Lb.dc)throw new M.Kb(63);return a.Lb.dc(a)},lstat:function(a){return M.stat(a,!0)},chmod:function(a,b,c){a="string"===typeof a?M.Pb(a,{cc:!c}).node:a;if(!a.Lb.Vb)throw new M.Kb(63);a.Lb.Vb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},lchmod:function(a,b){M.chmod(a,b,!0)},fchmod:function(a,b){a=M.fc(a);if(!a)throw new M.Kb(8);
M.chmod(a.node,b)},chown:function(a,b,c,d){a="string"===typeof a?M.Pb(a,{cc:!d}).node:a;if(!a.Lb.Vb)throw new M.Kb(63);a.Lb.Vb(a,{timestamp:Date.now()})},lchown:function(a,b,c){M.chown(a,b,c,!0)},fchown:function(a,b,c){a=M.fc(a);if(!a)throw new M.Kb(8);M.chown(a.node,b,c)},truncate:function(a,b){if(0>b)throw new M.Kb(28);a="string"===typeof a?M.Pb(a,{cc:!0}).node:a;if(!a.Lb.Vb)throw new M.Kb(63);if(M.Tb(a.mode))throw new M.Kb(31);if(!M.isFile(a.mode))throw new M.Kb(28);var c=M.pc(a,"w");if(c)throw new M.Kb(c);
a.Lb.Vb(a,{size:b,timestamp:Date.now()})},Pf:function(a,b){a=M.fc(a);if(!a)throw new M.Kb(8);if(0===(a.flags&2097155))throw new M.Kb(28);M.truncate(a.node,b)},eg:function(a,b,c){a=M.Pb(a,{cc:!0}).node;a.Lb.Vb(a,{timestamp:Math.max(b,c)})},open:function(a,b,c,d,f){if(""===a)throw new M.Kb(44);b="string"===typeof b?M.df(b):b;c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=Nb(a);try{g=M.Pb(a,{cc:!(b&131072)}).node}catch(m){}}var k=!1;if(b&64)if(g){if(b&128)throw new M.Kb(20);
}else g=M.ic(a,c,0),k=!0;if(!g)throw new M.Kb(44);M.Oc(g.mode)&&(b&=-513);if(b&65536&&!M.Tb(g.mode))throw new M.Kb(54);if(!k&&(c=M.cf(g,b)))throw new M.Kb(c);b&512&&M.truncate(g,0);b&=-131713;d=M.Ud({node:g,path:M.oc(g),flags:b,seekable:!0,position:0,Mb:g.Mb,Df:[],error:!1},d,f);d.Mb.open&&d.Mb.open(d);!e.logReadFiles||b&1||(M.Hd||(M.Hd={}),a in M.Hd||(M.Hd[a]=1,h("FS.trackingDelegate error on read file: "+a)));try{M.Wb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=M.se.le.we),0!==(b&2097155)&&(f|=M.se.le.xe),
M.Wb.onOpenFile(a,f))}catch(m){h("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d},close:function(a){if(M.Pc(a))throw new M.Kb(8);a.sc&&(a.sc=null);try{a.Mb.close&&a.Mb.close(a)}catch(b){throw b;}finally{M.Ee(a.fd)}a.fd=null},Pc:function(a){return null===a.fd},Yb:function(a,b,c){if(M.Pc(a))throw new M.Kb(8);if(!a.seekable||!a.Mb.Yb)throw new M.Kb(70);if(0!=c&&1!=c&&2!=c)throw new M.Kb(28);a.position=a.Mb.Yb(a,b,c);a.Df=[];return a.position},read:function(a,
b,c,d,f){if(0>d||0>f)throw new M.Kb(28);if(M.Pc(a))throw new M.Kb(8);if(1===(a.flags&2097155))throw new M.Kb(8);if(M.Tb(a.node.mode))throw new M.Kb(31);if(!a.Mb.read)throw new M.Kb(28);var g="undefined"!==typeof f;if(!g)f=a.position;else if(!a.seekable)throw new M.Kb(70);b=a.Mb.read(a,b,c,d,f);g||(a.position+=b);return b},write:function(a,b,c,d,f,g){if(0>d||0>f)throw new M.Kb(28);if(M.Pc(a))throw new M.Kb(8);if(0===(a.flags&2097155))throw new M.Kb(8);if(M.Tb(a.node.mode))throw new M.Kb(31);if(!a.Mb.write)throw new M.Kb(28);
a.seekable&&a.flags&1024&&M.Yb(a,0,2);var k="undefined"!==typeof f;if(!k)f=a.position;else if(!a.seekable)throw new M.Kb(70);b=a.Mb.write(a,b,c,d,f,g);k||(a.position+=b);try{if(a.path&&M.Wb.onWriteToFile)M.Wb.onWriteToFile(a.path)}catch(m){h("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+m.message)}return b},Mc:function(a,b,c){if(M.Pc(a))throw new M.Kb(8);if(0>b||0>=c)throw new M.Kb(28);if(0===(a.flags&2097155))throw new M.Kb(8);if(!M.isFile(a.node.mode)&&!M.Tb(a.node.mode))throw new M.Kb(43);
if(!a.Mb.Mc)throw new M.Kb(138);a.Mb.Mc(a,b,c)},Cc:function(a,b,c,d,f,g){if(0!==(f&2)&&0===(g&2)&&2!==(a.flags&2097155))throw new M.Kb(2);if(1===(a.flags&2097155))throw new M.Kb(2);if(!a.Mb.Cc)throw new M.Kb(43);return a.Mb.Cc(a,b,c,d,f,g)},Dc:function(a,b,c,d,f){return a&&a.Mb.Dc?a.Mb.Dc(a,b,c,d,f):0},Zf:function(){return 0},Bc:function(a,b,c){if(!a.Mb.Bc)throw new M.Kb(59);return a.Mb.Bc(a,b,c)},readFile:function(a,b){b=b||{};b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&
"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var c,d=M.open(a,b.flags);a=M.stat(a).size;var f=new Uint8Array(a);M.read(d,f,0,a,0);"utf8"===b.encoding?c=Ga(f,0):"binary"===b.encoding&&(c=f);M.close(d);return c},writeFile:function(a,b,c){c=c||{};c.flags=c.flags||577;a=M.open(a,c.flags,c.mode);if("string"===typeof b){var d=new Uint8Array(Ha(b)+1);b=Da(b,d,0,d.length);M.write(a,d,0,b,void 0,c.Ce)}else if(ArrayBuffer.isView(b))M.write(a,b,0,b.byteLength,void 0,c.Ce);else throw Error("Unsupported data type");
M.close(a)},cwd:function(){return M.Vd},chdir:function(a){a=M.Pb(a,{cc:!0});if(null===a.node)throw new M.Kb(44);if(!M.Tb(a.node.mode))throw new M.Kb(54);var b=M.pc(a.node,"x");if(b)throw new M.Kb(b);M.Vd=a.path},Ge:function(){M.mkdir("/tmp");M.mkdir("/home");M.mkdir("/home/web_user")},Fe:function(){M.mkdir("/dev");M.Kd(M.vc(1,3),{read:function(){return 0},write:function(b,c,d,f){return f}});M.cd("/dev/null",M.vc(1,3));Vb(M.vc(5,0),Yb);Vb(M.vc(6,0),Zb);M.cd("/dev/tty",M.vc(5,0));M.cd("/dev/tty1",M.vc(6,
0));var a=Rb();M.nc("/dev","random",a);M.nc("/dev","urandom",a);M.mkdir("/dev/shm");M.mkdir("/dev/shm/tmp")},Ie:function(){M.mkdir("/proc");var a=M.mkdir("/proc/self");M.mkdir("/proc/self/fd");M.Qb({Qb:function(){var b=M.createNode(a,"fd",16895,73);b.Lb={lookup:function(c,d){var f=M.fc(+d);if(!f)throw new M.Kb(8);c={parent:null,Qb:{je:"fake"},Lb:{readlink:function(){return f.path}}};return c.parent=c}};return b}},{},"/proc/self/fd")},Je:function(){e.stdin?M.nc("/dev","stdin",e.stdin):M.symlink("/dev/tty",
"/dev/stdin");e.stdout?M.nc("/dev","stdout",null,e.stdout):M.symlink("/dev/tty","/dev/stdout");e.stderr?M.nc("/dev","stderr",null,e.stderr):M.symlink("/dev/tty1","/dev/stderr");M.open("/dev/stdin",0);M.open("/dev/stdout",1);M.open("/dev/stderr",1)},Yd:function(){M.Kb||(M.Kb=function(a,b){this.node=b;this.qf=function(c){this.Ob=c};this.qf(a);this.message="FS error"},M.Kb.prototype=Error(),M.Kb.prototype.constructor=M.Kb,[44].forEach(function(a){M.xd[a]=new M.Kb(a);M.xd[a].stack="<generic error, no stack>"}))},
tf:function(){M.Yd();M.jc=Array(4096);M.Qb(W,{},"/");M.Ge();M.Fe();M.Ie();M.$d={MEMFS:W,WORKERFS:X}},Nc:function(a,b,c){M.Nc.Ad=!0;M.Yd();e.stdin=a||e.stdin;e.stdout=b||e.stdout;e.stderr=c||e.stderr;M.Je()},quit:function(){M.Nc.Ad=!1;var a=e._fflush;a&&a(0);for(a=0;a<M.streams.length;a++){var b=M.streams[a];b&&M.close(b)}},yd:function(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c},Of:function(a,b){a=M.td(a,b);return a.exists?a.object:null},td:function(a,b){try{var c=M.Pb(a,{cc:!b});a=c.path}catch(f){}var d=
{ad:!1,exists:!1,error:0,name:null,path:null,object:null,gf:!1,jf:null,hf:null};try{c=M.Pb(a,{parent:!0}),d.gf=!0,d.jf=c.path,d.hf=c.node,d.name=Pb(a),c=M.Pb(a,{cc:!b}),d.exists=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.ad="/"===c.path}catch(f){d.error=f.Ob}return d},Lf:function(a,b){a="string"===typeof a?a:M.oc(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Qb(a,c);try{M.mkdir(d)}catch(f){}a=d}}return d},He:function(a,b,c,d,f){a=Qb("string"===typeof a?a:M.oc(a),
b);return M.create(a,M.yd(d,f))},Td:function(a,b,c,d,f,g){a=b?Qb("string"===typeof a?a:M.oc(a),b):a;d=M.yd(d,f);f=M.create(a,d);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}M.chmod(f,d|146);a=M.open(f,577);M.write(a,c,0,c.length,0,g);M.close(a);M.chmod(f,d)}return f},nc:function(a,b,c,d){a=Qb("string"===typeof a?a:M.oc(a),b);b=M.yd(!!c,!!d);M.nc.Dd||(M.nc.Dd=64);var f=M.vc(M.nc.Dd++,0);M.Kd(f,{open:function(g){g.seekable=!1},close:function(){d&&
d.buffer&&d.buffer.length&&d(10)},read:function(g,k,m,p){for(var q=0,r=0;r<p;r++){try{var y=c()}catch(F){throw new M.Kb(29);}if(void 0===y&&0===q)throw new M.Kb(6);if(null===y||void 0===y)break;q++;k[m+r]=y}q&&(g.node.timestamp=Date.now());return q},write:function(g,k,m,p){for(var q=0;q<p;q++)try{d(k[m+q])}catch(r){throw new M.Kb(29);}p&&(g.node.timestamp=Date.now());return q}});return M.cd(a,b,f)},be:function(a){if(a.Bd||a.Xe||a.link||a.Nb)return!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");
if(oa)try{a.Nb=Xb(oa(a.url),!0),a.Rb=a.Nb.length}catch(b){throw new M.Kb(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");},Kf:function(a,b,c,d,f){function g(){this.Cd=!1;this.zc=[]}g.prototype.get=function(q){if(!(q>this.length-1||0>q)){var r=q%this.chunkSize;return this.fe(q/this.chunkSize|0)[r]}};g.prototype.ue=function(q){this.fe=q};g.prototype.Rd=function(){var q=new XMLHttpRequest;q.open("HEAD",c,!1);q.send(null);if(!(200<=q.status&&300>q.status||304===q.status))throw Error("Couldn't load "+
c+". Status: "+q.status);var r=Number(q.getResponseHeader("Content-length")),y,F=(y=q.getResponseHeader("Accept-Ranges"))&&"bytes"===y;q=(y=q.getResponseHeader("Content-Encoding"))&&"gzip"===y;var n=1048576;F||(n=r);var v=this;v.ue(function(w){var O=w*n,R=(w+1)*n-1;R=Math.min(R,r-1);if("undefined"===typeof v.zc[w]){var vb=v.zc;if(O>R)throw Error("invalid range ("+O+", "+R+") or no bytes requested!");if(R>r-1)throw Error("only "+r+" bytes available! programmer error!");var G=new XMLHttpRequest;G.open("GET",
c,!1);r!==n&&G.setRequestHeader("Range","bytes="+O+"-"+R);"undefined"!=typeof Uint8Array&&(G.responseType="arraybuffer");G.overrideMimeType&&G.overrideMimeType("text/plain; charset=x-user-defined");G.send(null);if(!(200<=G.status&&300>G.status||304===G.status))throw Error("Couldn't load "+c+". Status: "+G.status);O=void 0!==G.response?new Uint8Array(G.response||[]):Xb(G.responseText||"",!0);vb[w]=O}if("undefined"===typeof v.zc[w])throw Error("doXHR failed!");return v.zc[w]});if(q||!r)n=r=1,n=r=this.fe(0).length,
ea("LazyFiles on gzip forces download of the whole file when length is accessed");this.ze=r;this.ye=n;this.Cd=!0};if("undefined"!==typeof XMLHttpRequest){if(!l)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new g;Object.defineProperties(k,{length:{get:function(){this.Cd||this.Rd();return this.ze}},chunkSize:{get:function(){this.Cd||this.Rd();return this.ye}}});k={Bd:!1,Nb:k}}else k={Bd:!1,url:c};var m=M.He(a,b,k,d,f);
k.Nb?m.Nb=k.Nb:k.url&&(m.Nb=null,m.url=k.url);Object.defineProperties(m,{Rb:{get:function(){return this.Nb.length}}});var p={};Object.keys(m.Mb).forEach(function(q){var r=m.Mb[q];p[q]=function(){M.be(m);return r.apply(null,arguments)}});p.read=function(q,r,y,F,n){M.be(m);q=q.node.Nb;if(n>=q.length)return 0;F=Math.min(q.length-n,F);if(q.slice)for(var v=0;v<F;v++)r[y+v]=q[n+v];else for(v=0;v<F;v++)r[y+v]=q.get(n+v);return F};m.Mb=p;return m},Mf:function(a,b,c,d,f,g,k,m,p,q){function r(F){function n(w){q&&
q();m||M.Td(a,b,w,d,f,p);g&&g();eb()}var v=!1;e.preloadPlugins.forEach(function(w){!v&&w.canHandle(y)&&(w.handle(F,y,n,function(){k&&k();eb()}),v=!0)});v||n(F)}$b.Nc();var y=b?Sb(Qb(a,b)):a;db();"string"==typeof c?$b.Ff(c,function(F){r(F)},k):r(c)},indexedDB:function(){return window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB},Md:function(){return"EM_FS_"+window.location.pathname},Nd:20,Kc:"FILE_DATA",bg:function(a,b,c){b=b||function(){};c=c||function(){};var d=M.indexedDB();
try{var f=d.open(M.Md(),M.Nd)}catch(g){return c(g)}f.onupgradeneeded=function(){ea("creating db");f.result.createObjectStore(M.Kc)};f.onsuccess=function(){var g=f.result.transaction([M.Kc],"readwrite"),k=g.objectStore(M.Kc),m=0,p=0,q=a.length;a.forEach(function(r){r=k.put(M.td(r).object.Nb,r);r.onsuccess=function(){m++;m+p==q&&(0==p?b():c())};r.onerror=function(){p++;m+p==q&&(0==p?b():c())}});g.onerror=c};f.onerror=c},Uf:function(a,b,c){b=b||function(){};c=c||function(){};var d=M.indexedDB();try{var f=
d.open(M.Md(),M.Nd)}catch(g){return c(g)}f.onupgradeneeded=c;f.onsuccess=function(){var g=f.result;try{var k=g.transaction([M.Kc],"readonly")}catch(y){c(y);return}var m=k.objectStore(M.Kc),p=0,q=0,r=a.length;a.forEach(function(y){var F=m.get(y);F.onsuccess=function(){M.td(y).exists&&M.unlink(y);M.Td(Ob(y),Pb(y),F.result,!0,!0,!0);p++;p+q==r&&(0==q?b():c())};F.onerror=function(){q++;p+q==r&&(0==q?b():c())}});k.onerror=c};f.onerror=c}},ac={};
function bc(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&Nb(b)!==Nb(M.oc(f.node)))return-54;throw f;}J[c>>2]=d.dev;J[c+4>>2]=0;J[c+8>>2]=d.ino;J[c+12>>2]=d.mode;J[c+16>>2]=d.nlink;J[c+20>>2]=d.uid;J[c+24>>2]=d.gid;J[c+28>>2]=d.rdev;J[c+32>>2]=0;T=[d.size>>>0,(Q=d.size,1<=+Math.abs(Q)?0<Q?(Math.min(+Math.floor(Q/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Q-+(~~Q>>>0))/4294967296)>>>0:0)];J[c+40>>2]=T[0];J[c+44>>2]=T[1];J[c+48>>2]=4096;J[c+52>>2]=d.blocks;J[c+56>>2]=d.atime.getTime()/1E3|0;J[c+60>>
2]=0;J[c+64>>2]=d.mtime.getTime()/1E3|0;J[c+68>>2]=0;J[c+72>>2]=d.ctime.getTime()/1E3|0;J[c+76>>2]=0;T=[d.ino>>>0,(Q=d.ino,1<=+Math.abs(Q)?0<Q?(Math.min(+Math.floor(Q/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Q-+(~~Q>>>0))/4294967296)>>>0:0)];J[c+80>>2]=T[0];J[c+84>>2]=T[1];return 0}var cc=void 0;function dc(){cc+=4;return J[cc-4>>2]}function ec(a){a=M.fc(a);if(!a)throw new M.Kb(8);return a}
function fc(a,b,c,d,f){if(u)return V(3,1,a,b,c,d,f);try{f=0;for(var g=b?J[b>>2]:0,k=b?J[b+4>>2]:0,m=c?J[c>>2]:0,p=c?J[c+4>>2]:0,q=d?J[d>>2]:0,r=d?J[d+4>>2]:0,y=0,F=0,n=0,v=0,w=0,O=0,R=(b?J[b>>2]:0)|(c?J[c>>2]:0)|(d?J[d>>2]:0),vb=(b?J[b+4>>2]:0)|(c?J[c+4>>2]:0)|(d?J[d+4>>2]:0),G=0;G<a;G++){var S=1<<G%32;if(32>G?R&S:vb&S){var Ya=M.fc(G);if(!Ya)throw new M.Kb(8);var Za=5;Ya.Mb.Fc&&(Za=Ya.Mb.Fc(Ya));Za&1&&(32>G?g&S:k&S)&&(32>G?y|=S:F|=S,f++);Za&4&&(32>G?m&S:p&S)&&(32>G?n|=S:v|=S,f++);Za&2&&(32>G?q&S:
r&S)&&(32>G?w|=S:O|=S,f++)}}b&&(J[b>>2]=y,J[b+4>>2]=F);c&&(J[c>>2]=n,J[c+4>>2]=v);d&&(J[d>>2]=w,J[d+4>>2]=O);return f}catch(yb){return"undefined"!==typeof M&&yb instanceof M.Kb||z(yb),-yb.Ob}}
var N={Qb:function(){e.websocket=e.websocket&&"object"===typeof e.websocket?e.websocket:{};e.websocket.qd={};e.websocket.on=function(a,b){"function"===typeof b&&(this.qd[a]=b);return this};e.websocket.emit=function(a,b){"function"===typeof this.qd[a]&&this.qd[a].call(this,b)};return M.createNode(null,"/",16895,0)},createSocket:function(a,b,c){b&=-526337;c&&assert(1==b==(6==c));a={family:a,type:b,protocol:c,Ub:null,error:null,Sc:{},pending:[],Gc:[],ac:N.Xb};b=N.dd();c=M.createNode(N.root,b,49152,0);
c.Hc=a;b=M.Ud({path:b,node:c,flags:2,seekable:!1,Mb:N.Mb});a.stream=b;return a},Re:function(a){return(a=M.fc(a))&&M.isSocket(a.node.mode)?a.node.Hc:null},Mb:{Fc:function(a){a=a.node.Hc;return a.ac.Fc(a)},Bc:function(a,b,c){a=a.node.Hc;return a.ac.Bc(a,b,c)},read:function(a,b,c,d){a=a.node.Hc;d=a.ac.me(a,d);if(!d)return 0;b.set(d.buffer,c);return d.buffer.length},write:function(a,b,c,d){a=a.node.Hc;return a.ac.qe(a,b,c,d)},close:function(a){a=a.node.Hc;a.ac.close(a)}},dd:function(){N.dd.current||(N.dd.current=
0);return"socket["+N.dd.current++ +"]"},Xb:{Yc:function(a,b,c){if("object"===typeof b){var d=b;c=b=null}if(d)if(d._socket)b=d._socket.remoteAddress,c=d._socket.remotePort;else{c=/ws[s]?:\/\/([^:]+):(\d+)/.exec(d.url);if(!c)throw Error("WebSocket URL must be in the format ws(s)://address:port");b=c[1];c=parseInt(c[2],10)}else try{var f=e.websocket&&"object"===typeof e.websocket,g="ws:#".replace("#","//");f&&"string"===typeof e.websocket.url&&(g=e.websocket.url);if("ws://"===g||"wss://"===g){var k=
b.split("/");g=g+k[0]+":"+c+"/"+k.slice(1).join("/")}k="binary";f&&"string"===typeof e.websocket.subprotocol&&(k=e.websocket.subprotocol);var m=void 0;"null"!==k&&(k=k.replace(/^ +| +$/g,"").split(/ *, */),m=t?{protocol:k.toString()}:k);f&&null===e.websocket.subprotocol&&(m=void 0);d=new (t?require("ws"):WebSocket)(g,m);d.binaryType="arraybuffer"}catch(p){throw new M.Kb(23);}b={Sb:b,port:c,socket:d,Zc:[]};N.Xb.Pd(a,b);N.Xb.Se(a,b);2===a.type&&"undefined"!==typeof a.xc&&b.Zc.push(new Uint8Array([255,
255,255,255,112,111,114,116,(a.xc&65280)>>8,a.xc&255]));return b},$c:function(a,b,c){return a.Sc[b+":"+c]},Pd:function(a,b){a.Sc[b.Sb+":"+b.port]=b},ne:function(a,b){delete a.Sc[b.Sb+":"+b.port]},Se:function(a,b){function c(){e.websocket.emit("open",a.stream.fd);try{for(var g=b.Zc.shift();g;)b.socket.send(g),g=b.Zc.shift()}catch(k){b.socket.close()}}function d(g){if("string"===typeof g)g=(new TextEncoder).encode(g);else{assert(void 0!==g.byteLength);if(0==g.byteLength)return;g=new Uint8Array(g)}var k=
f;f=!1;k&&10===g.length&&255===g[0]&&255===g[1]&&255===g[2]&&255===g[3]&&112===g[4]&&111===g[5]&&114===g[6]&&116===g[7]?(g=g[8]<<8|g[9],N.Xb.ne(a,b),b.port=g,N.Xb.Pd(a,b)):(a.Gc.push({Sb:b.Sb,port:b.port,data:g}),e.websocket.emit("message",a.stream.fd))}var f=!0;t?(b.socket.on("open",c),b.socket.on("message",function(g,k){k.Gf&&d((new Uint8Array(g)).buffer)}),b.socket.on("close",function(){e.websocket.emit("close",a.stream.fd)}),b.socket.on("error",function(){a.error=14;e.websocket.emit("error",[a.stream.fd,
a.error,"ECONNREFUSED: Connection refused"])})):(b.socket.onopen=c,b.socket.onclose=function(){e.websocket.emit("close",a.stream.fd)},b.socket.onmessage=function(g){d(g.data)},b.socket.onerror=function(){a.error=14;e.websocket.emit("error",[a.stream.fd,a.error,"ECONNREFUSED: Connection refused"])})},Fc:function(a){if(1===a.type&&a.Ub)return a.pending.length?65:0;var b=0,c=1===a.type?N.Xb.$c(a,a.$b,a.bc):null;if(a.Gc.length||!c||c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b|=
65;if(!c||c&&c.socket.readyState===c.socket.OPEN)b|=4;if(c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b|=16;return b},Bc:function(a,b,c){switch(b){case 21531:return b=0,a.Gc.length&&(b=a.Gc[0].data.length),J[c>>2]=b,0;default:return 28}},close:function(a){if(a.Ub){try{a.Ub.close()}catch(f){}a.Ub=null}for(var b=Object.keys(a.Sc),c=0;c<b.length;c++){var d=a.Sc[b[c]];try{d.socket.close()}catch(f){}N.Xb.ne(a,d)}return 0},bind:function(a,b,c){if("undefined"!==typeof a.hd||
"undefined"!==typeof a.xc)throw new M.Kb(28);a.hd=b;a.xc=c;if(2===a.type){a.Ub&&(a.Ub.close(),a.Ub=null);try{a.ac.listen(a,0)}catch(d){if(!(d instanceof M.Kb))throw d;if(138!==d.Ob)throw d;}}},connect:function(a,b,c){if(a.Ub)throw new M.Kb(138);if("undefined"!==typeof a.$b&&"undefined"!==typeof a.bc){var d=N.Xb.$c(a,a.$b,a.bc);if(d){if(d.socket.readyState===d.socket.CONNECTING)throw new M.Kb(7);throw new M.Kb(30);}}b=N.Xb.Yc(a,b,c);a.$b=b.Sb;a.bc=b.port;throw new M.Kb(26);},listen:function(a){if(!t)throw new M.Kb(138);
if(a.Ub)throw new M.Kb(28);var b=require("ws").Server;a.Ub=new b({host:a.hd,port:a.xc});e.websocket.emit("listen",a.stream.fd);a.Ub.on("connection",function(c){if(1===a.type){var d=N.createSocket(a.family,a.type,a.protocol);c=N.Xb.Yc(d,c);d.$b=c.Sb;d.bc=c.port;a.pending.push(d);e.websocket.emit("connection",d.stream.fd)}else N.Xb.Yc(a,c),e.websocket.emit("connection",a.stream.fd)});a.Ub.on("closed",function(){e.websocket.emit("close",a.stream.fd);a.Ub=null});a.Ub.on("error",function(){a.error=23;
e.websocket.emit("error",[a.stream.fd,a.error,"EHOSTUNREACH: Host is unreachable"])})},accept:function(a){if(!a.Ub)throw new M.Kb(28);var b=a.pending.shift();b.stream.flags=a.stream.flags;return b},Rf:function(a,b){if(b){if(void 0===a.$b||void 0===a.bc)throw new M.Kb(53);b=a.$b;a=a.bc}else b=a.hd||0,a=a.xc||0;return{Sb:b,port:a}},qe:function(a,b,c,d,f,g){if(2===a.type){if(void 0===f||void 0===g)f=a.$b,g=a.bc;if(void 0===f||void 0===g)throw new M.Kb(17);}else f=a.$b,g=a.bc;var k=N.Xb.$c(a,f,g);if(1===
a.type){if(!k||k.socket.readyState===k.socket.CLOSING||k.socket.readyState===k.socket.CLOSED)throw new M.Kb(53);if(k.socket.readyState===k.socket.CONNECTING)throw new M.Kb(6);}ArrayBuffer.isView(b)&&(c+=b.byteOffset,b=b.buffer);var m;b instanceof SharedArrayBuffer?m=(new Uint8Array(new Uint8Array(b.slice(c,c+d)))).buffer:m=b.slice(c,c+d);if(2===a.type&&(!k||k.socket.readyState!==k.socket.OPEN))return k&&k.socket.readyState!==k.socket.CLOSING&&k.socket.readyState!==k.socket.CLOSED||(k=N.Xb.Yc(a,f,
g)),k.Zc.push(m),d;try{return k.socket.send(m),d}catch(p){throw new M.Kb(28);}},me:function(a,b){if(1===a.type&&a.Ub)throw new M.Kb(53);var c=a.Gc.shift();if(!c){if(1===a.type){if(a=N.Xb.$c(a,a.$b,a.bc)){if(a.socket.readyState===a.socket.CLOSING||a.socket.readyState===a.socket.CLOSED)return null;throw new M.Kb(6);}throw new M.Kb(53);}throw new M.Kb(6);}var d=c.data.byteLength||c.data.length,f=c.data.byteOffset||0,g=c.data.buffer||c.data;b=Math.min(b,d);var k={buffer:new Uint8Array(g,f,b),Sb:c.Sb,
port:c.port};1===a.type&&b<d&&(c.data=new Uint8Array(g,f+b,d-b),a.Gc.unshift(c));return k}}};function hc(a){a=N.Re(a);if(!a)throw new M.Kb(8);return a}function ic(a){a=a.split(".");for(var b=0;4>b;b++){var c=Number(a[b]);if(isNaN(c))return null;a[b]=c}return(a[0]|a[1]<<8|a[2]<<16|a[3]<<24)>>>0}
function jc(a){var b,c,d=[];if(!/^((?=.*::)(?!.*::.+::)(::)?([\dA-F]{1,4}:(:|\b)|){5}|([\dA-F]{1,4}:){6})((([\dA-F]{1,4}((?!\3)::|:\b|$))|(?!\2\3)){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})$/i.test(a))return null;if("::"===a)return[0,0,0,0,0,0,0,0];a=a.startsWith("::")?a.replace("::","Z:"):a.replace("::",":Z:");0<a.indexOf(".")?(a=a.replace(/[.]/g,":"),a=a.split(":"),a[a.length-4]=parseInt(a[a.length-4])+256*parseInt(a[a.length-3]),a[a.length-3]=parseInt(a[a.length-2])+256*parseInt(a[a.length-
1]),a=a.slice(0,a.length-2)):a=a.split(":");for(b=c=0;b<a.length;b++)if("string"===typeof a[b])if("Z"===a[b]){for(c=0;c<8-a.length+1;c++)d[b+c]=0;--c}else d[b+c]=kc(parseInt(a[b],16));else d[b+c]=a[b];return[d[1]<<16|d[0],d[3]<<16|d[2],d[5]<<16|d[4],d[7]<<16|d[6]]}
function lc(a,b,c,d,f){switch(b){case 2:c=ic(c);f&&(J[f>>2]=16);I[a>>1]=b;J[a+4>>2]=c;I[a+2>>1]=kc(d);T=[0,(Q=0,1<=+Math.abs(Q)?0<Q?(Math.min(+Math.floor(Q/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Q-+(~~Q>>>0))/4294967296)>>>0:0)];J[a+8>>2]=T[0];J[a+12>>2]=T[1];break;case 10:c=jc(c);f&&(J[f>>2]=28);J[a>>2]=b;J[a+8>>2]=c[0];J[a+12>>2]=c[1];J[a+16>>2]=c[2];J[a+20>>2]=c[3];I[a+2>>1]=kc(d);J[a+4>>2]=0;J[a+24>>2]=0;break;default:return 5}return 0}var mc=1,nc={},oc={};
function pc(a){var b=ic(a);if(null!==b)return a;b=jc(a);if(null!==b)return a;nc[a]?b=nc[a]:(b=mc++,assert(65535>b,"exceeded max address mappings of 65535"),b="172.29."+(b&255)+"."+(b&65280),oc[b]=a,nc[a]=b);return b}function qc(a,b,c,d){if(u)return V(4,1,a,b,c,d);try{var f=hc(a),g=f.ac.accept(f);b&&lc(b,g.family,pc(g.$b),g.bc,c);return g.stream.fd}catch(k){return"undefined"!==typeof M&&k instanceof M.Kb||z(k),-k.Ob}}
function rc(a,b){if(u)return V(5,1,a,b);try{a=D(a);if(b&-8)var c=-28;else{var d;(d=M.Pb(a,{cc:!0}).node)?(a="",b&4&&(a+="r"),b&2&&(a+="w"),b&1&&(a+="x"),c=a&&M.pc(d,a)?-2:0):c=-44}return c}catch(f){return"undefined"!==typeof M&&f instanceof M.Kb||z(f),-f.Ob}}function sc(a){return(a&255)+"."+(a>>8&255)+"."+(a>>16&255)+"."+(a>>24&255)}
function tc(a){var b="",c,d=0,f=0,g=0,k=0;a=[a[0]&65535,a[0]>>16,a[1]&65535,a[1]>>16,a[2]&65535,a[2]>>16,a[3]&65535,a[3]>>16];var m=!0;for(c=0;5>c;c++)if(0!==a[c]){m=!1;break}if(m){c=sc(a[6]|a[7]<<16);if(-1===a[5])return"::ffff:"+c;if(0===a[5])return"0.0.0.0"===c&&(c=""),"0.0.0.1"===c&&(c="1"),"::"+c}for(c=0;8>c;c++)0===a[c]&&(1<c-f&&(k=0),f=c,k++),k>d&&(d=k,g=c-d+1);for(c=0;8>c;c++)1<d&&0===a[c]&&c>=g&&c<g+d?c===g&&(b+=":",0===g&&(b+=":")):(b+=Number(uc(a[c]&65535)).toString(16),b+=7>c?":":"");return b}
function vc(a,b){var c=I[a>>1],d=uc(Ma[a+2>>1]);switch(c){case 2:if(16!==b)return{Ob:28};a=J[a+4>>2];a=sc(a);break;case 10:if(28!==b)return{Ob:28};a=[J[a+8>>2],J[a+12>>2],J[a+16>>2],J[a+20>>2]];a=tc(a);break;default:return{Ob:5}}return{family:c,Sb:a,port:d}}function wc(a,b,c){if(c&&0===a)return null;a=vc(a,b);if(a.Ob)throw new M.Kb(a.Ob);b=a.Sb;a.Sb=(oc[b]?oc[b]:null)||a.Sb;return a}
function xc(a,b,c){if(u)return V(6,1,a,b,c);try{var d=hc(a),f=wc(b,c);d.ac.bind(d,f.Sb,f.port);return 0}catch(g){return"undefined"!==typeof M&&g instanceof M.Kb||z(g),-g.Ob}}function yc(a,b,c){if(u)return V(7,1,a,b,c);try{var d=hc(a),f=wc(b,c);d.ac.connect(d,f.Sb,f.port);return 0}catch(g){return"undefined"!==typeof M&&g instanceof M.Kb||z(g),-g.Ob}}
function zc(a,b,c){if(u)return V(8,1,a,b,c);cc=c;try{var d=ec(a);switch(b){case 0:var f=dc();return 0>f?-28:M.open(d.path,d.flags,0,f).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return f=dc(),d.flags|=f,0;case 12:return f=dc(),I[f+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return J[Db()>>2]=28,-1;default:return-28}}catch(g){return"undefined"!==typeof M&&g instanceof M.Kb||z(g),-g.Ob}}
function Ac(a,b){if(u)return V(9,1,a,b);try{var c=ec(a);return bc(M.stat,c.path,b)}catch(d){return"undefined"!==typeof M&&d instanceof M.Kb||z(d),-d.Ob}}
function Bc(a,b,c){if(u)return V(10,1,a,b,c);try{var d=ec(a);d.sc||(d.sc=M.readdir(d.path));a=0;for(var f=M.Yb(d,0,1),g=Math.floor(f/280);g<d.sc.length&&a+280<=c;){var k=d.sc[g];if("."===k[0]){var m=1;var p=4}else{var q=M.hc(d.node,k);m=q.id;p=M.Oc(q.mode)?2:M.Tb(q.mode)?4:M.tc(q.mode)?10:8}T=[m>>>0,(Q=m,1<=+Math.abs(Q)?0<Q?(Math.min(+Math.floor(Q/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Q-+(~~Q>>>0))/4294967296)>>>0:0)];J[b+a>>2]=T[0];J[b+a+4>>2]=T[1];T=[280*(g+1)>>>0,(Q=280*(g+1),1<=+Math.abs(Q)?
0<Q?(Math.min(+Math.floor(Q/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Q-+(~~Q>>>0))/4294967296)>>>0:0)];J[b+a+8>>2]=T[0];J[b+a+12>>2]=T[1];I[b+a+16>>1]=280;B[b+a+18>>0]=p;Da(k,A,b+a+19,256);a+=280;g+=1}M.Yb(d,280*g,0);return a}catch(r){return"undefined"!==typeof M&&r instanceof M.Kb||z(r),-r.Ob}}function Cc(a,b,c){if(u)return V(11,1,a,b,c);try{var d=hc(a);if(!d.$b)return-53;lc(b,d.family,pc(d.$b),d.bc,c);return 0}catch(f){return"undefined"!==typeof M&&f instanceof M.Kb||z(f),-f.Ob}}
function Dc(a,b){if(u)return V(12,1,a,b);try{return Ec(b,0,136),J[b>>2]=1,J[b+4>>2]=2,J[b+8>>2]=3,J[b+12>>2]=4,0}catch(c){return"undefined"!==typeof M&&c instanceof M.Kb||z(c),-c.Ob}}function Fc(a,b,c){if(u)return V(13,1,a,b,c);try{h("__sys_getsockname "+a);var d=hc(a);lc(b,d.family,pc(d.hd||"0.0.0.0"),d.xc,c);return 0}catch(f){return"undefined"!==typeof M&&f instanceof M.Kb||z(f),-f.Ob}}
function Gc(a,b,c,d,f){if(u)return V(14,1,a,b,c,d,f);try{var g=hc(a);return 1===b&&4===c?(J[d>>2]=g.error,J[f>>2]=4,g.error=null,0):-50}catch(k){return"undefined"!==typeof M&&k instanceof M.Kb||z(k),-k.Ob}}
function Hc(a,b,c){if(u)return V(15,1,a,b,c);cc=c;try{var d=ec(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var f=dc();return J[f>>2]=0;case 21520:return d.tty?-28:-59;case 21531:return f=dc(),M.Bc(d,b,f);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:z("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof M&&g instanceof M.Kb||z(g),-g.Ob}}
function Ic(a,b){if(u)return V(16,1,a,b);try{var c=hc(a);c.ac.listen(c,b);return 0}catch(d){return"undefined"!==typeof M&&d instanceof M.Kb||z(d),-d.Ob}}function Jc(a,b){if(u)return V(17,1,a,b);try{return a=D(a),bc(M.lstat,a,b)}catch(c){return"undefined"!==typeof M&&c instanceof M.Kb||z(c),-c.Ob}}function Kc(a,b){if(u)return V(18,1,a,b);try{return a=D(a),a=Nb(a),"/"===a[a.length-1]&&(a=a.substr(0,a.length-1)),M.mkdir(a,b,0),0}catch(c){return"undefined"!==typeof M&&c instanceof M.Kb||z(c),-c.Ob}}
function Lc(a,b,c,d,f,g){if(u)return V(19,1,a,b,c,d,f,g);try{a:{g<<=12;var k=!1;if(0!==(d&16)&&0!==a%65536)var m=-28;else{if(0!==(d&32)){var p=Mc(65536,b);if(!p){m=-48;break a}Ec(p,0,b);k=!0}else{var q=M.fc(f);if(!q){m=-8;break a}var r=M.Cc(q,a,b,g,c,d);p=r.lf;k=r.rd}ac[p]={af:p,Ye:b,rd:k,fd:f,kf:c,flags:d,offset:g};m=p}}return m}catch(y){return"undefined"!==typeof M&&y instanceof M.Kb||z(y),-y.Ob}}
function Nc(a,b){if(u)return V(20,1,a,b);try{if(-1===(a|0)||0===b)var c=-28;else{var d=ac[a];if(d&&b===d.Ye){var f=M.fc(d.fd);if(f&&d.kf&2){var g=d.flags,k=d.offset,m=A.slice(a,a+b);M.Dc(f,m,k,b,g)}ac[a]=null;d.rd&&sb(d.af)}c=0}return c}catch(p){return"undefined"!==typeof M&&p instanceof M.Kb||z(p),-p.Ob}}function Oc(a,b,c){if(u)return V(21,1,a,b,c);cc=c;try{var d=D(a),f=c?dc():0;return M.open(d,b,f).fd}catch(g){return"undefined"!==typeof M&&g instanceof M.Kb||z(g),-g.Ob}}
function Pc(a,b,c){if(u)return V(22,1,a,b,c);try{for(var d=c=0;d<b;d++){var f=a+8*d,g=I[f+4>>1],k=32,m=M.fc(J[f>>2]);m&&(k=5,m.Mb.Fc&&(k=m.Mb.Fc(m)));(k&=g|24)&&c++;I[f+6>>1]=k}return c}catch(p){return"undefined"!==typeof M&&p instanceof M.Kb||z(p),-p.Ob}}function Qc(a,b,c,d){if(u)return V(23,1,a,b,c,d);try{return d&&(J[d>>2]=-1,J[d+4>>2]=-1,J[d+8>>2]=-1,J[d+12>>2]=-1),0}catch(f){return"undefined"!==typeof M&&f instanceof M.Kb||z(f),-f.Ob}}
function Rc(a,b,c,d,f,g){if(u)return V(24,1,a,b,c,d,f,g);try{var k=hc(a),m=k.ac.me(k,c);if(!m)return 0;f&&lc(f,k.family,pc(m.Sb),m.port,g);A.set(m.buffer,b);return m.buffer.byteLength}catch(p){return"undefined"!==typeof M&&p instanceof M.Kb||z(p),-p.Ob}}function Sc(a,b){if(u)return V(25,1,a,b);try{return a=D(a),b=D(b),M.rename(a,b),0}catch(c){return"undefined"!==typeof M&&c instanceof M.Kb||z(c),-c.Ob}}
function Tc(a){if(u)return V(26,1,a);try{return a=D(a),M.rmdir(a),0}catch(b){return"undefined"!==typeof M&&b instanceof M.Kb||z(b),-b.Ob}}function Uc(a,b,c,d,f,g){if(u)return V(27,1,a,b,c,d,f,g);try{var k=hc(a),m=wc(f,g,!0);return m?k.ac.qe(k,B,b,c,m.Sb,m.port):M.write(k.stream,B,b,c)}catch(p){return"undefined"!==typeof M&&p instanceof M.Kb||z(p),-p.Ob}}function Vc(a){return u?V(28,1,a):-50}
function Wc(a,b){if(u)return V(29,1,a,b);try{return hc(a),-52}catch(c){return"undefined"!==typeof M&&c instanceof M.Kb||z(c),-c.Ob}}function Xc(a,b,c){if(u)return V(30,1,a,b,c);try{return N.createSocket(a,b,c).stream.fd}catch(d){return"undefined"!==typeof M&&d instanceof M.Kb||z(d),-d.Ob}}function Yc(a,b){if(u)return V(31,1,a,b);try{return a=D(a),bc(M.stat,a,b)}catch(c){return"undefined"!==typeof M&&c instanceof M.Kb||z(c),-c.Ob}}
function Zc(a){if(u)return V(32,1,a);try{return a=D(a),M.unlink(a),0}catch(b){return"undefined"!==typeof M&&b instanceof M.Kb||z(b),-b.Ob}}function $c(){void 0===$c.start&&($c.start=Date.now());return 1E3*(Date.now()-$c.start)|0}var ad=[];
function bd(){t||l||(ua||(ua={}),ua["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(ua["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,h("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))}
function cd(a,b,c){if(0>=a||a>B.length||a&1)return-28;if(la){if(Atomics.load(J,a>>2)!=b)return-6;var d=performance.now();c=d+c;for(Atomics.exchange(J,lb>>2,a);;){d=performance.now();if(d>c)return Atomics.exchange(J,lb>>2,0),-73;d=Atomics.exchange(J,lb>>2,0);if(0==d)break;ub();if(Atomics.load(J,a>>2)!=b)return-6;Atomics.exchange(J,lb>>2,a)}return 0}a=Atomics.wait(J,a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+
a;}function V(a,b){for(var c=arguments.length-2,d=C(),f=Ca(8*c),g=f>>3,k=0;k<c;k++)Oa[g+k]=arguments[2+k];c=dd(a,c,f,b);E(d);return c}var ed=[],fd=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function gd(a){a=2<a?D(a):a;return fd[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function hd(a,b,c){var d=gd(a);if(!d)return-4;d.Xc&&(J[d.Xc>>2]=b,J[d.Xc+4>>2]=c);if(d.ke||!d.Jf)d.ke&&(d=d.ke),a=!1,d.Wc&&d.Wc.Vc&&(a=d.Wc.Vc.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.Wc.Vc.viewport(0,0,b,c);else{if(d.Xc){d=J[d.Xc+8>>2];a=a?D(a):"";var f=C(),g=Ca(12),k=0;if(a){k=Ha(a)+1;var m=H(k);Da(a,A,m,k);k=m}J[g>>2]=k;J[g+4>>2]=b;J[g+8>>2]=c;jd(0,d,657457152,0,k,g);E(f);return 1}return-4}return 0}
function kd(a,b,c){return u?V(33,1,a,b,c):hd(a,b,c)}function ld(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,g){b.drawArraysInstancedANGLE(c,d,f,g)},a.drawElementsInstanced=function(c,d,f,g,k){b.drawElementsInstancedANGLE(c,d,f,g,k)})}
function md(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function nd(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function od(a,b){a.ce||(a.ce=a.getContext,a.getContext=function(d,f){f=a.ce(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl",b);return c?pd(c,b):0}function pd(a,b){var c=H(8);J[c+4>>2]=qb();var d={Sf:c,attributes:b,version:b.$e,Vc:a};a.canvas&&(a.canvas.Wc=d);("undefined"===typeof b.Xd||b.Xd)&&qd(d);return c}
function qd(a){a||(a=rd);if(!a.Te){a.Te=!0;var b=a.Vc;ld(b);md(b);nd(b);b.Nf=b.getExtension("EXT_disjoint_timer_query");b.Yf=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var rd,sd=["default","low-power","high-performance"],td={};
function ud(){if(!vd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ja||"./this.program"},b;for(b in td)void 0===td[b]?delete a[b]:a[b]=td[b];var c=[];for(b in a)c.push(b+"="+a[b]);vd=c}return vd}var vd;
function wd(a,b){if(u)return V(34,1,a,b);try{var c=0;ud().forEach(function(d,f){var g=b+c;J[a+4*f>>2]=g;Ka(d,g);c+=d.length+1});return 0}catch(d){return"undefined"!==typeof M&&d instanceof M.Kb||z(d),d.Ob}}function xd(a,b){if(u)return V(35,1,a,b);try{var c=ud();J[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});J[b>>2]=d;return 0}catch(f){return"undefined"!==typeof M&&f instanceof M.Kb||z(f),f.Ob}}
function yd(a){if(u)return V(36,1,a);try{var b=ec(a);M.close(b);return 0}catch(c){return"undefined"!==typeof M&&c instanceof M.Kb||z(c),c.Ob}}function zd(a,b){if(u)return V(37,1,a,b);try{var c=ec(a);B[b>>0]=c.tty?2:M.Tb(c.mode)?3:M.tc(c.mode)?7:4;return 0}catch(d){return"undefined"!==typeof M&&d instanceof M.Kb||z(d),d.Ob}}
function Ad(a,b,c,d){if(u)return V(38,1,a,b,c,d);try{a:{for(var f=ec(a),g=a=0;g<c;g++){var k=J[b+(8*g+4)>>2],m=M.read(f,B,J[b+8*g>>2],k,void 0);if(0>m){var p=-1;break a}a+=m;if(m<k)break}p=a}J[d>>2]=p;return 0}catch(q){return"undefined"!==typeof M&&q instanceof M.Kb||z(q),q.Ob}}
function Bd(a,b,c,d,f){if(u)return V(39,1,a,b,c,d,f);try{var g=ec(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;M.Yb(g,a,d);T=[g.position>>>0,(Q=g.position,1<=+Math.abs(Q)?0<Q?(Math.min(+Math.floor(Q/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Q-+(~~Q>>>0))/4294967296)>>>0:0)];J[f>>2]=T[0];J[f+4>>2]=T[1];g.sc&&0===a&&0===d&&(g.sc=null);return 0}catch(k){return"undefined"!==typeof M&&k instanceof M.Kb||z(k),k.Ob}}
function Cd(a,b,c,d){if(u)return V(40,1,a,b,c,d);try{a:{for(var f=ec(a),g=a=0;g<c;g++){var k=M.write(f,B,J[b+8*g>>2],J[b+(8*g+4)>>2],void 0);if(0>k){var m=-1;break a}a+=k}m=a}J[d>>2]=m;return 0}catch(p){return"undefined"!==typeof M&&p instanceof M.Kb||z(p),p.Ob}}var Y={};
function Dd(a){Dd.buffer||(Dd.buffer=H(256),Y["0"]="Success",Y["-1"]="Invalid value for 'ai_flags' field",Y["-2"]="NAME or SERVICE is unknown",Y["-3"]="Temporary failure in name resolution",Y["-4"]="Non-recoverable failure in name res",Y["-6"]="'ai_family' not supported",Y["-7"]="'ai_socktype' not supported",Y["-8"]="SERVICE not supported for 'ai_socktype'",Y["-10"]="Memory allocation failure",Y["-11"]="System error returned in 'errno'",Y["-12"]="Argument buffer overflow");var b="Unknown error";a in
Y&&(255<Y[a].length?b="Message too long":b=Y[a]);Ka(b,Dd.buffer);return Dd.buffer}
function Ed(a,b,c,d){function f(y,F,n,v,w,O){var R=10===y?28:16;w=10===y?tc(w):sc(w);R=H(R);w=lc(R,y,w,O);assert(!w);w=H(32);J[w+4>>2]=y;J[w+8>>2]=F;J[w+12>>2]=n;J[w+24>>2]=v;J[w+20>>2]=R;J[w+16>>2]=10===y?28:16;J[w+28>>2]=0;return w}if(u)return V(41,1,a,b,c,d);var g=0,k=0,m=0,p=0,q=0,r=0;c&&(m=J[c>>2],p=J[c+4>>2],q=J[c+8>>2],r=J[c+12>>2]);q&&!r&&(r=2===q?17:6);!q&&r&&(q=17===r?2:1);0===r&&(r=6);0===q&&(q=1);if(!a&&!b)return-2;if(m&-1088||0!==c&&J[c>>2]&2&&!a)return-1;if(m&32)return-2;if(0!==q&&1!==
q&&2!==q)return-7;if(0!==p&&2!==p&&10!==p)return-6;if(b&&(b=D(b),k=parseInt(b,10),isNaN(k)))return m&1024?-2:-8;if(!a)return 0===p&&(p=2),0===(m&1)&&(2===p?g=Fd(2130706433):g=[0,0,0,1]),a=f(p,q,r,null,g,k),J[d>>2]=a,0;a=D(a);g=ic(a);if(null!==g)if(0===p||2===p)p=2;else if(10===p&&m&8)g=[0,0,Fd(65535),g],p=10;else return-2;else if(g=jc(a),null!==g)if(0===p||10===p)p=10;else return-2;if(null!=g)return a=f(p,q,r,a,g,k),J[d>>2]=a,0;if(m&4)return-2;a=pc(a);g=ic(a);0===p?p=2:10===p&&(g=[0,0,Fd(65535),g]);
a=f(p,q,r,null,g,k);J[d>>2]=a;return 0}
function wb(a){if(u)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=U.Qe();if(!b)return 6;if(void 0!==b.ec)throw"Internal error!";if(!a.ed)throw"Internal error, no pthread ptr!";U.qc.push(b);for(var c=H(512),d=0;128>d;++d)J[c+4*d>>2]=0;var f=a.yc+a.Ic;d=U.lc[a.ed]={worker:b,yc:a.yc,Ic:a.Ic,sd:a.sd,mc:a.ed};var g=d.mc>>2;Atomics.store(K,g+16,a.detached);Atomics.store(K,g+25,c);Atomics.store(K,g+10,d.mc);Atomics.store(K,g+20,a.Ic);Atomics.store(K,g+19,
f);Atomics.store(K,g+26,a.Ic);Atomics.store(K,g+28,f);Atomics.store(K,g+29,a.detached);c=Gd()+40;Atomics.store(K,g+43,c);b.ec=d;var k={cmd:"run",start_routine:a.sf,arg:a.Ac,threadInfoStruct:a.ed,stackBase:a.yc,stackSize:a.Ic};b.Tc=function(){k.time=performance.now();b.postMessage(k,a.Cf)};b.loaded&&(b.Tc(),delete b.Tc);return 0}
function Hd(a,b){if(!a)return h("pthread_join attempted on a null thread pointer!"),71;if(u&&qb()==a)return h("PThread "+a+" is attempting to join to itself!"),16;if(!u&&Id()==a)return h("Main thread "+a+" is attempting to join to itself!"),16;if(J[a+12>>2]!==a)return h("pthread_join attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;if(Atomics.load(K,a+64>>2))return h("Attempted to join thread "+a+", which was already detached!"),28;for(bd();;){var c=
Atomics.load(K,a>>2);if(1==c)return c=Atomics.load(K,a+4>>2),b&&(J[b>>2]=c),Atomics.store(K,a+64>>2,1),u?postMessage({cmd:"cleanupThread",thread:a}):nb(a),0;if(u){var d=qb();if(d&&!Atomics.load(K,d+56>>2)&&2==Atomics.load(K,d+0>>2))throw"Canceled!";}u||ub();cd(a,c,u?100:1)}}function Jd(a){return 0===a%4&&(0!==a%100||0===a%400)}function Kd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Ld=[31,29,31,30,31,30,31,31,30,31,30,31],Md=[31,28,31,30,31,30,31,31,30,31,30,31];
function Nd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Jd(a.getFullYear())?Ld:Md)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}function Od(a,b,c,d){a||(a=this);this.parent=a;this.Qb=a.Qb;this.Qc=null;this.id=M.ef++;this.name=b;this.mode=c;this.Lb={};this.Mb={};this.rdev=d}
Object.defineProperties(Od.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Xe:{get:function(){return M.Tb(this.mode)}},Bd:{get:function(){return M.Oc(this.mode)}}});M.te=Od;M.tf();var $b;e.FS_mount=M.Qb;e.FS_unmount=M.Ef;e.FS_filesystems=M.$d;
var Pd=[null,Eb,Hb,fc,qc,rc,xc,yc,zc,Ac,Bc,Cc,Dc,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,kd,wd,xd,yd,zd,Ad,Bd,Cd,Ed];function Xb(a,b){var c=Array(Ha(a)+1);a=Da(a,c,0,c.length);b&&(c.length=a);return c}
var ie={c:function(a,b,c,d){z("Assertion failed: "+D(a)+", at: "+[b?D(b):"unknown filename",c,d?D(d):"unknown function"])},Ja:function(a,b){a=Qd(a,b);if(!Ab())return postMessage({cmd:"exitProcess",returnCode:a}),a},K:function(a,b){return Cb(a,b)},F:function(a,b){return Eb(a,b)},Qa:function(a,b){return Fb(a,b)},na:function(a,b){return Gb(a,b)},ma:function(a,b){return Lb(a,b)},ya:fc,ca:qc,Ba:rc,fa:xc,ea:yc,q:zc,Ga:Ac,ra:Bc,aa:Cc,ua:Dc,ba:Fc,Z:Gc,P:Hc,da:Ic,Ha:Jc,Ia:Kc,pa:Lc,qa:function(){return 0},
oa:Nc,Ea:function(){return-63},R:Oc,xa:Pc,ta:Qc,_:Rc,Fa:Sc,Ca:Tc,$:Uc,sa:function(){return 0},_a:Vc,ga:Wc,J:Xc,S:Yc,va:function(a){try{if(!a)return-21;var b={__size__:390,domainname:325,machine:260,nodename:65,release:130,sysname:0,version:195};Ka("Emscripten",a+b.sysname);Ka("emscripten",a+b.nodename);Ka("1.0",a+b.release);Ka("#1",a+b.version);Ka("wasm32",a+b.machine);return 0}catch(c){return"undefined"!==typeof M&&c instanceof M.Kb||z(c),-c.Ob}},Da:Zc,Oa:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});
else if(u)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=U.lc[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},ja:function(){throw"longjmp";},b:function(){z()},Pa:$c,Ta:Cb,X:function(){z("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},Ua:function(){z("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},
U:function(a,b,c){ad.length=0;var d;for(c>>=2;d=A[b++];)(d=105>d)&&c&1&&c++,ad.push(d?Oa[c++>>1]:J[c]),++c;return jb[a].apply(null,ad)},wa:bd,C:function(){},w:cd,v:kb,za:function(){return A.length},u:Bb,ha:function(a,b,c){A.copyWithin(a,b,b+c)},Aa:function(){return t?require("os").cpus().length:navigator.hardwareConcurrency},La:function(a,b,c){ed.length=b;c>>=3;for(var d=0;d<b;d++)ed[d]=Oa[c+d];return(0>a?jb[-a-1]:Pd[a]).apply(null,ed)},ia:function(){z("OOM")},Ma:function(a,b,c){return gd(a)?hd(a,
b,c):kd(a,b,c)},T:function(){},Ka:function(){},Na:function(a,b){b>>=2;b={alpha:!!J[b],depth:!!J[b+1],stencil:!!J[b+2],antialias:!!J[b+3],premultipliedAlpha:!!J[b+4],preserveDrawingBuffer:!!J[b+5],powerPreference:sd[J[b+6]],failIfMajorPerformanceCaveat:!!J[b+7],$e:J[b+8],Wf:J[b+9],Xd:J[b+10],Me:J[b+11],$f:J[b+12],ag:J[b+13]};a=gd(a);return!a||b.Me?0:od(a,b)},ka:wd,la:xd,B:function(a){da(a)},A:yd,O:zd,Q:Ad,Va:Bd,E:Cd,x:Dd,d:function(){return va},t:Ed,r:function(a,b,c,d,f,g,k){b=vc(a,b);if(b.Ob)return-6;
a=b.port;var m=b.Sb;b=!1;if(c&&d){var p;if(k&1||!(p=oc[m]?oc[m]:null)){if(k&8)return-2}else m=p;c=Da(m,A,c,d);c+1>=d&&(b=!0)}f&&g&&(c=Da(""+a,A,f,g),c+1>=g&&(b=!0));return b?-12:0},i:function(a){var b=Date.now();J[a>>2]=b/1E3|0;J[a+4>>2]=b%1E3*1E3|0;return 0},o:Gb,Za:function(){U.Ue()},Y:Rd,h:Sd,g:Td,y:Ud,I:Vd,W:Wd,H:Xd,Xa:Yd,Wa:Zd,j:$d,s:ae,D:be,f:ce,G:de,Sa:ee,V:fe,Ya:ge,n:Lb,a:xa||e.wasmMemory,N:function(a){Hb();var b=new Date(J[a+20>>2]+1900,J[a+16>>2],J[a+12>>2],J[a+8>>2],J[a+4>>2],J[a>>2],0),
c=J[a+32>>2],d=b.getTimezoneOffset(),f=new Date(b.getFullYear(),0,1),g=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),k=f.getTimezoneOffset(),m=Math.min(k,g);0>c?J[a+32>>2]=Number(g!=k&&m==d):0<c!=(m==d)&&(g=Math.max(k,g),b.setTime(b.getTime()+6E4*((0<c?m:g)-d)));J[a+24>>2]=b.getDay();J[a+28>>2]=(b.getTime()-f.getTime())/864E5|0;J[a>>2]=b.getSeconds();J[a+4>>2]=b.getMinutes();J[a+8>>2]=b.getHours();J[a+12>>2]=b.getDate();J[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},Ra:function(a){if(a===
Id())return h("Main thread (id="+a+") cannot be canceled!"),71;if(!a)return h("pthread_cancel attempted on a null thread pointer!"),71;if(J[a+12>>2]!==a)return h("pthread_cancel attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;Atomics.compareExchange(K,a>>2,0,2);u?postMessage({cmd:"cancelThread",thread:a}):mb(a);return 0},L:function(a){var b=U.kd.pop();a&&b()},M:Fb,l:function(a,b,c,d){if("undefined"===typeof SharedArrayBuffer)return h("Current environment does not support SharedArrayBuffer, pthreads are not available!"),
6;if(!a)return h("pthread_create called with a null thread pointer!"),28;var f=[];if(u&&0===f.length)return he(687865856,a,b,c,d);var g=0,k=0;if(b&&-1!=b){var m=J[b>>2];m+=81920;g=J[b+8>>2];k=0!==J[b+12>>2]}else m=2097152;(b=0==g)?g=Mc(16,m):(g-=m,assert(0<g));for(var p=H(228),q=0;57>q;++q)K[(p>>2)+q]=0;J[a>>2]=p;J[p+12>>2]=p;a=p+152;J[a>>2]=a;c={yc:g,Ic:m,sd:b,detached:k,sf:c,ed:p,Ac:d,Cf:f};return u?(c.If="spawnThread",postMessage(c,f),0):wb(c)},m:function(a,b){return Hd(a,b)},e:function(a){va=
a},z:function(){return 0},k:function(a,b,c,d){function f(n,v,w){for(n="number"===typeof n?n.toString():n||"";n.length<v;)n=w[0]+n;return n}function g(n,v){return f(n,v,"0")}function k(n,v){function w(R){return 0>R?-1:0<R?1:0}var O;0===(O=w(n.getFullYear()-v.getFullYear()))&&0===(O=w(n.getMonth()-v.getMonth()))&&(O=w(n.getDate()-v.getDate()));return O}function m(n){switch(n.getDay()){case 0:return new Date(n.getFullYear()-1,11,29);case 1:return n;case 2:return new Date(n.getFullYear(),0,3);case 3:return new Date(n.getFullYear(),
0,2);case 4:return new Date(n.getFullYear(),0,1);case 5:return new Date(n.getFullYear()-1,11,31);case 6:return new Date(n.getFullYear()-1,11,30)}}function p(n){n=Nd(new Date(n.Zb+1900,0,1),n.nd);var v=new Date(n.getFullYear()+1,0,4),w=m(new Date(n.getFullYear(),0,4));v=m(v);return 0>=k(w,n)?0>=k(v,n)?n.getFullYear()+1:n.getFullYear():n.getFullYear()-1}var q=J[d+40>>2];d={Af:J[d>>2],zf:J[d+4>>2],ld:J[d+8>>2],Uc:J[d+12>>2],Jc:J[d+16>>2],Zb:J[d+20>>2],md:J[d+24>>2],nd:J[d+28>>2],dg:J[d+32>>2],yf:J[d+
36>>2],Bf:q?D(q):""};c=D(c);q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in q)c=c.replace(new RegExp(r,"g"),q[r]);var y="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
F="January February March April May June July August September October November December".split(" ");q={"%a":function(n){return y[n.md].substring(0,3)},"%A":function(n){return y[n.md]},"%b":function(n){return F[n.Jc].substring(0,3)},"%B":function(n){return F[n.Jc]},"%C":function(n){return g((n.Zb+1900)/100|0,2)},"%d":function(n){return g(n.Uc,2)},"%e":function(n){return f(n.Uc,2," ")},"%g":function(n){return p(n).toString().substring(2)},"%G":function(n){return p(n)},"%H":function(n){return g(n.ld,
2)},"%I":function(n){n=n.ld;0==n?n=12:12<n&&(n-=12);return g(n,2)},"%j":function(n){return g(n.Uc+Kd(Jd(n.Zb+1900)?Ld:Md,n.Jc-1),3)},"%m":function(n){return g(n.Jc+1,2)},"%M":function(n){return g(n.zf,2)},"%n":function(){return"\n"},"%p":function(n){return 0<=n.ld&&12>n.ld?"AM":"PM"},"%S":function(n){return g(n.Af,2)},"%t":function(){return"\t"},"%u":function(n){return n.md||7},"%U":function(n){var v=new Date(n.Zb+1900,0,1),w=0===v.getDay()?v:Nd(v,7-v.getDay());n=new Date(n.Zb+1900,n.Jc,n.Uc);return 0>
k(w,n)?g(Math.ceil((31-w.getDate()+(Kd(Jd(n.getFullYear())?Ld:Md,n.getMonth()-1)-31)+n.getDate())/7),2):0===k(w,v)?"01":"00"},"%V":function(n){var v=new Date(n.Zb+1901,0,4),w=m(new Date(n.Zb+1900,0,4));v=m(v);var O=Nd(new Date(n.Zb+1900,0,1),n.nd);return 0>k(O,w)?"53":0>=k(v,O)?"01":g(Math.ceil((w.getFullYear()<n.Zb+1900?n.nd+32-w.getDate():n.nd+1-w.getDate())/7),2)},"%w":function(n){return n.md},"%W":function(n){var v=new Date(n.Zb,0,1),w=1===v.getDay()?v:Nd(v,0===v.getDay()?1:7-v.getDay()+1);n=
new Date(n.Zb+1900,n.Jc,n.Uc);return 0>k(w,n)?g(Math.ceil((31-w.getDate()+(Kd(Jd(n.getFullYear())?Ld:Md,n.getMonth()-1)-31)+n.getDate())/7),2):0===k(w,v)?"01":"00"},"%y":function(n){return(n.Zb+1900).toString().substring(2)},"%Y":function(n){return n.Zb+1900},"%z":function(n){n=n.yf;var v=0<=n;n=Math.abs(n)/60;return(v?"+":"-")+String("0000"+(n/60*100+n%60)).slice(-4)},"%Z":function(n){return n.Bf},"%%":function(){return"%"}};for(r in q)c.includes(r)&&(c=c.replace(new RegExp(r,"g"),q[r](d)));r=Xb(c,
!1);if(r.length>b)return 0;B.set(r,a);return r.length-1},p:function(a){var b=Date.now()/1E3|0;a&&(J[a>>2]=b);return b}};
(function(){function a(f,g){e.asm=f.exports;L=e.asm.cb;Sa.unshift(e.asm.$a);U.Ld.push(e.asm.jb);ya=g;u||eb()}function b(f){a(f.instance,f.module)}function c(f){return hb().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){h("failed to asynchronously prepare wasm: "+g);z(g)})}var d={a:ie};u||db();if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return h("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return wa||"function"!==typeof WebAssembly.instantiateStreaming||
fb()||P.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(P,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){h("wasm streaming compile failed: "+g);h("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.$a).apply(null,arguments)};
var sb=e._free=function(){return(sb=e._free=e.asm.ab).apply(null,arguments)},H=e._malloc=function(){return(H=e._malloc=e.asm.bb).apply(null,arguments)},Db=e.___errno_location=function(){return(Db=e.___errno_location=e.asm.db).apply(null,arguments)};e._fflush=function(){return(e._fflush=e.asm.eb).apply(null,arguments)};
var Mc=e._memalign=function(){return(Mc=e._memalign=e.asm.fb).apply(null,arguments)},uc=e._ntohs=function(){return(uc=e._ntohs=e.asm.gb).apply(null,arguments)},kc=e._htons=function(){return(kc=e._htons=e.asm.hb).apply(null,arguments)},Qd=e._main=function(){return(Qd=e._main=e.asm.ib).apply(null,arguments)};e._emscripten_tls_init=function(){return(e._emscripten_tls_init=e.asm.jb).apply(null,arguments)};var qb=e._pthread_self=function(){return(qb=e._pthread_self=e.asm.kb).apply(null,arguments)};
e._emscripten_current_thread_process_queued_calls=function(){return(e._emscripten_current_thread_process_queued_calls=e.asm.lb).apply(null,arguments)};
var pb=e._emscripten_register_main_browser_thread_id=function(){return(pb=e._emscripten_register_main_browser_thread_id=e.asm.mb).apply(null,arguments)},Id=e._emscripten_main_browser_thread_id=function(){return(Id=e._emscripten_main_browser_thread_id=e.asm.nb).apply(null,arguments)},ib=e.__emscripten_do_dispatch_to_thread=function(){return(ib=e.__emscripten_do_dispatch_to_thread=e.asm.ob).apply(null,arguments)},he=e._emscripten_sync_run_in_main_thread_4=function(){return(he=e._emscripten_sync_run_in_main_thread_4=
e.asm.pb).apply(null,arguments)},ub=e._emscripten_main_thread_process_queued_calls=function(){return(ub=e._emscripten_main_thread_process_queued_calls=e.asm.qb).apply(null,arguments)},dd=e._emscripten_run_in_main_runtime_thread_js=function(){return(dd=e._emscripten_run_in_main_runtime_thread_js=e.asm.rb).apply(null,arguments)},jd=e.__emscripten_call_on_thread=function(){return(jd=e.__emscripten_call_on_thread=e.asm.sb).apply(null,arguments)};
e._emscripten_proxy_main=function(){return(e._emscripten_proxy_main=e.asm.tb).apply(null,arguments)};
var ob=e.__emscripten_thread_init=function(){return(ob=e.__emscripten_thread_init=e.asm.ub).apply(null,arguments)},Ec=e._memset=function(){return(Ec=e._memset=e.asm.vb).apply(null,arguments)},rb=e.___pthread_tsd_run_dtors=function(){return(rb=e.___pthread_tsd_run_dtors=e.asm.wb).apply(null,arguments)},Gd=e._emscripten_get_global_libc=function(){return(Gd=e._emscripten_get_global_libc=e.asm.xb).apply(null,arguments)},Fd=e._htonl=function(){return(Fd=e._htonl=e.asm.yb).apply(null,arguments)},Kb=e.__get_tzname=
function(){return(Kb=e.__get_tzname=e.asm.zb).apply(null,arguments)},Jb=e.__get_daylight=function(){return(Jb=e.__get_daylight=e.asm.Ab).apply(null,arguments)},Ib=e.__get_timezone=function(){return(Ib=e.__get_timezone=e.asm.Bb).apply(null,arguments)},C=e.stackSave=function(){return(C=e.stackSave=e.asm.Cb).apply(null,arguments)},E=e.stackRestore=function(){return(E=e.stackRestore=e.asm.Db).apply(null,arguments)},Ca=e.stackAlloc=function(){return(Ca=e.stackAlloc=e.asm.Eb).apply(null,arguments)},xb=
e._emscripten_stack_set_limits=function(){return(xb=e._emscripten_stack_set_limits=e.asm.Fb).apply(null,arguments)},Z=e._setThrew=function(){return(Z=e._setThrew=e.asm.Gb).apply(null,arguments)},je=e.dynCall_vijjjid=function(){return(je=e.dynCall_vijjjid=e.asm.Hb).apply(null,arguments)},ke=e.dynCall_iiiijj=function(){return(ke=e.dynCall_iiiijj=e.asm.Ib).apply(null,arguments)},le=e.dynCall_iij=function(){return(le=e.dynCall_iij=e.asm.Jb).apply(null,arguments)};e._ff_h264_cabac_tables=2558924;
var tb=e.__emscripten_allow_main_runtime_queued_calls=5410016,lb=e.__emscripten_main_thread_futex=16979940;function Td(a,b,c){var d=C();try{return L.get(a)(b,c)}catch(f){E(d);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function $d(a,b){var c=C();try{L.get(a)(b)}catch(d){E(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}function ce(a,b,c,d,f){var g=C();try{L.get(a)(b,c,d,f)}catch(k){E(g);if(k!==k+0&&"longjmp"!==k)throw k;Z(1,0)}}
function ae(a,b,c){var d=C();try{L.get(a)(b,c)}catch(f){E(d);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function Sd(a,b){var c=C();try{return L.get(a)(b)}catch(d){E(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}function Vd(a,b,c,d,f){var g=C();try{return L.get(a)(b,c,d,f)}catch(k){E(g);if(k!==k+0&&"longjmp"!==k)throw k;Z(1,0)}}function Xd(a,b,c,d,f,g,k,m,p){var q=C();try{return L.get(a)(b,c,d,f,g,k,m,p)}catch(r){E(q);if(r!==r+0&&"longjmp"!==r)throw r;Z(1,0)}}
function be(a,b,c,d){var f=C();try{L.get(a)(b,c,d)}catch(g){E(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}function Rd(a){var b=C();try{return L.get(a)()}catch(c){E(b);if(c!==c+0&&"longjmp"!==c)throw c;Z(1,0)}}function de(a,b,c,d,f,g){var k=C();try{L.get(a)(b,c,d,f,g)}catch(m){E(k);if(m!==m+0&&"longjmp"!==m)throw m;Z(1,0)}}function Ud(a,b,c,d){var f=C();try{return L.get(a)(b,c,d)}catch(g){E(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}
function Wd(a,b,c,d,f,g){var k=C();try{return L.get(a)(b,c,d,f,g)}catch(m){E(k);if(m!==m+0&&"longjmp"!==m)throw m;Z(1,0)}}function fe(a,b,c,d,f,g,k,m,p){var q=C();try{L.get(a)(b,c,d,f,g,k,m,p)}catch(r){E(q);if(r!==r+0&&"longjmp"!==r)throw r;Z(1,0)}}function ee(a,b,c,d,f,g,k){var m=C();try{L.get(a)(b,c,d,f,g,k)}catch(p){E(m);if(p!==p+0&&"longjmp"!==p)throw p;Z(1,0)}}function ge(a,b,c,d,f,g,k,m,p,q){var r=C();try{je(a,b,c,d,f,g,k,m,p,q)}catch(y){E(r);if(y!==y+0&&"longjmp"!==y)throw y;Z(1,0)}}
function Yd(a,b,c,d,f,g,k,m){var p=C();try{return ke(a,b,c,d,f,g,k,m)}catch(q){E(p);if(q!==q+0&&"longjmp"!==q)throw q;Z(1,0)}}function Zd(a,b,c,d){var f=C();try{return le(a,b,c,d)}catch(g){E(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}e.ccall=Ba;e.cwrap=function(a,b,c,d){c=c||[];var f=c.every(function(g){return"number"===g});return"string"!==b&&f&&!d?Aa(a):function(){return Ba(a,b,c,arguments,d)}};
e.setValue=function(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":B[a>>0]=b;break;case "i8":B[a>>0]=b;break;case "i16":I[a>>1]=b;break;case "i32":J[a>>2]=b;break;case "i64":T=[b>>>0,(Q=b,1<=+Math.abs(Q)?0<Q?(Math.min(+Math.floor(Q/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Q-+(~~Q>>>0))/4294967296)>>>0:0)];J[a>>2]=T[0];J[a+4>>2]=T[1];break;case "float":Na[a>>2]=b;break;case "double":Oa[a>>3]=b;break;default:z("invalid type for setValue: "+c)}};e.writeAsciiToMemory=Ka;
e.FS=M;e.PThread=U;e.PThread=U;e.wasmMemory=xa;e.ExitStatus=ca;var me;function ca(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}cb=function ne(){me||oe();me||(cb=ne)};
function oe(a){function b(){if(!me&&(me=!0,e.calledRun=!0,!za)){Wa();u||Xa(Ta);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(pe){var c=a,d=e._emscripten_proxy_main;c=c||[];var f=c.length+1,g=Ca(4*(f+1));J[g>>2]=Ja(ja);for(var k=1;k<f;k++)J[(g>>2)+k]=Ja(c[k-1]);J[(g>>2)+f]=0;d(f,g)}if(!u){if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)c=e.postRun.shift(),Va.unshift(c);Xa(Va)}}}a=a||ia;if(!(0<ab))if(u)aa(e),Wa(),postMessage({cmd:"loaded"});else{if(!u){if(e.preRun)for("function"==
typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)$a();Xa(Ra)}0<ab||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);b()},1)):b())}}e.run=oe;function da(a,b){if(!b||!Ab()||0!==a){if(!b&&u)throw postMessage({cmd:"exitProcess",returnCode:a}),new ca(a);if(!Ab()){U.uf();u||(Xa(Ua),M.quit(),U.oe());if(e.onExit)e.onExit(a);za=!0}ka(a,new ca(a))}}if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();
var pe=!1;e.noInitialRun&&(pe=!1);u&&(noExitRuntime=!1,U.Ve());oe();


  return createFFmpegCore.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = createFFmpegCore;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return createFFmpegCore; });
else if (typeof exports === 'object')
  exports["createFFmpegCore"] = createFFmpegCore;
